use crate::items::{ItemGen3, ItemMetadataPastGen};

#[cfg(feature = "wasm")]
use wasm_bindgen::prelude::*;

pub const ITEM_MAX_GEN3: usize = 376;

#[cfg_attr(feature = "wasm", wasm_bindgen(js_name = "getAllItemsGen3"))]
#[allow(clippy::missing_const_for_fn)]
pub fn get_all_items_gen3() -> Vec<ItemMetadataPastGen> {
    ALL_ITEMS_GEN3.into_iter().copied().collect()
}

impl ItemGen3 {
    pub fn from_modern_index(modern_index: u16) -> Option<Self> {
        match modern_index {
            1 => Self::new(1),
            2 => Self::new(2),
            3 => Self::new(3),
            4 => Self::new(4),
            5 => Self::new(5),
            6 => Self::new(6),
            7 => Self::new(7),
            8 => Self::new(8),
            9 => Self::new(9),
            10 => Self::new(10),
            11 => Self::new(11),
            12 => Self::new(12),
            17 => Self::new(13),
            18 => Self::new(14),
            19 => Self::new(15),
            20 => Self::new(16),
            21 => Self::new(17),
            22 => Self::new(18),
            23 => Self::new(19),
            24 => Self::new(20),
            25 => Self::new(21),
            26 => Self::new(22),
            27 => Self::new(23),
            28 => Self::new(24),
            29 => Self::new(25),
            30 => Self::new(26),
            31 => Self::new(27),
            32 => Self::new(28),
            33 => Self::new(29),
            34 => Self::new(30),
            35 => Self::new(31),
            36 => Self::new(32),
            37 => Self::new(33),
            38 => Self::new(34),
            39 => Self::new(35),
            40 => Self::new(36),
            41 => Self::new(37),
            42 => Self::new(38),
            43 => Self::new(44),
            44 => Self::new(45),
            45 => Self::new(63),
            46 => Self::new(64),
            47 => Self::new(65),
            48 => Self::new(66),
            49 => Self::new(67),
            50 => Self::new(68),
            51 => Self::new(69),
            52 => Self::new(70),
            53 => Self::new(71),
            55 => Self::new(73),
            56 => Self::new(74),
            57 => Self::new(75),
            58 => Self::new(76),
            59 => Self::new(77),
            60 => Self::new(78),
            63 => Self::new(80),
            64 => Self::new(81),
            65 => Self::new(39),
            66 => Self::new(40),
            67 => Self::new(41),
            68 => Self::new(42),
            69 => Self::new(43),
            70 => Self::new(46),
            71 => Self::new(47),
            72 => Self::new(48),
            73 => Self::new(49),
            74 => Self::new(50),
            75 => Self::new(51),
            76 => Self::new(83),
            77 => Self::new(84),
            78 => Self::new(85),
            79 => Self::new(86),
            80 => Self::new(93),
            81 => Self::new(94),
            82 => Self::new(95),
            83 => Self::new(96),
            84 => Self::new(97),
            85 => Self::new(98),
            86 => Self::new(103),
            87 => Self::new(104),
            88 => Self::new(106),
            89 => Self::new(107),
            90 => Self::new(108),
            91 => Self::new(109),
            92 => Self::new(110),
            93 => Self::new(111),
            99 => Self::new(286),
            100 => Self::new(287),
            101 => Self::new(357),
            102 => Self::new(358),
            103 => Self::new(354),
            113 => Self::new(369),
            114 => Self::new(52),
            123 => Self::new(364),
            149 => Self::new(133),
            150 => Self::new(134),
            151 => Self::new(135),
            152 => Self::new(136),
            153 => Self::new(137),
            154 => Self::new(138),
            155 => Self::new(139),
            156 => Self::new(140),
            157 => Self::new(141),
            158 => Self::new(142),
            159 => Self::new(143),
            160 => Self::new(144),
            161 => Self::new(145),
            162 => Self::new(146),
            163 => Self::new(147),
            164 => Self::new(148),
            165 => Self::new(149),
            166 => Self::new(150),
            167 => Self::new(151),
            168 => Self::new(152),
            169 => Self::new(153),
            170 => Self::new(154),
            171 => Self::new(155),
            172 => Self::new(156),
            173 => Self::new(157),
            174 => Self::new(158),
            175 => Self::new(159),
            176 => Self::new(160),
            177 => Self::new(161),
            178 => Self::new(162),
            179 => Self::new(163),
            180 => Self::new(164),
            181 => Self::new(165),
            182 => Self::new(166),
            183 => Self::new(167),
            201 => Self::new(168),
            202 => Self::new(169),
            203 => Self::new(170),
            204 => Self::new(171),
            205 => Self::new(172),
            206 => Self::new(173),
            207 => Self::new(174),
            208 => Self::new(175),
            213 => Self::new(179),
            214 => Self::new(180),
            215 => Self::new(181),
            216 => Self::new(182),
            217 => Self::new(183),
            218 => Self::new(184),
            219 => Self::new(185),
            220 => Self::new(186),
            221 => Self::new(187),
            222 => Self::new(188),
            223 => Self::new(189),
            224 => Self::new(190),
            225 => Self::new(191),
            226 => Self::new(192),
            227 => Self::new(193),
            228 => Self::new(194),
            229 => Self::new(195),
            230 => Self::new(196),
            231 => Self::new(197),
            232 => Self::new(198),
            233 => Self::new(199),
            234 => Self::new(200),
            235 => Self::new(201),
            236 => Self::new(202),
            237 => Self::new(203),
            238 => Self::new(204),
            239 => Self::new(205),
            240 => Self::new(206),
            241 => Self::new(207),
            242 => Self::new(208),
            243 => Self::new(209),
            244 => Self::new(210),
            245 => Self::new(211),
            246 => Self::new(212),
            247 => Self::new(213),
            248 => Self::new(214),
            249 => Self::new(215),
            250 => Self::new(216),
            251 => Self::new(217),
            252 => Self::new(218),
            253 => Self::new(219),
            254 => Self::new(220),
            255 => Self::new(221),
            256 => Self::new(222),
            257 => Self::new(223),
            258 => Self::new(224),
            259 => Self::new(225),
            260 => Self::new(254),
            261 => Self::new(255),
            262 => Self::new(256),
            263 => Self::new(257),
            264 => Self::new(258),
            328 => Self::new(289),
            329 => Self::new(290),
            330 => Self::new(291),
            331 => Self::new(292),
            332 => Self::new(293),
            333 => Self::new(294),
            334 => Self::new(295),
            335 => Self::new(296),
            336 => Self::new(297),
            337 => Self::new(298),
            338 => Self::new(299),
            339 => Self::new(300),
            340 => Self::new(301),
            341 => Self::new(302),
            342 => Self::new(303),
            343 => Self::new(304),
            344 => Self::new(305),
            345 => Self::new(306),
            346 => Self::new(307),
            347 => Self::new(308),
            348 => Self::new(309),
            349 => Self::new(310),
            350 => Self::new(311),
            351 => Self::new(312),
            352 => Self::new(313),
            353 => Self::new(314),
            354 => Self::new(315),
            355 => Self::new(316),
            356 => Self::new(317),
            357 => Self::new(318),
            358 => Self::new(319),
            359 => Self::new(320),
            360 => Self::new(321),
            361 => Self::new(322),
            362 => Self::new(323),
            363 => Self::new(324),
            364 => Self::new(325),
            365 => Self::new(326),
            366 => Self::new(327),
            367 => Self::new(328),
            368 => Self::new(329),
            369 => Self::new(330),
            370 => Self::new(331),
            371 => Self::new(332),
            372 => Self::new(333),
            373 => Self::new(334),
            374 => Self::new(335),
            375 => Self::new(336),
            376 => Self::new(337),
            377 => Self::new(338),
            420 => Self::new(339),
            421 => Self::new(340),
            422 => Self::new(341),
            423 => Self::new(342),
            424 => Self::new(343),
            425 => Self::new(344),
            442 => Self::new(361),
            443 => Self::new(362),
            444 => Self::new(260),
            445 => Self::new(262),
            446 => Self::new(263),
            447 => Self::new(264),
            450 => Self::new(360),
            456 => Self::new(265),
            457 => Self::new(266),
            459 => Self::new(349),
            463 => Self::new(285),
            467 => Self::new(351),
            471 => Self::new(261),
            475 => Self::new(355),
            476 => Self::new(271),
            534 => Self::new(276),
            535 => Self::new(277),
            651 => Self::new(350),
            718 => Self::new(259),
            719 => Self::new(272),
            720 => Self::new(268),
            721 => Self::new(269),
            722 => Self::new(270),
            725 => Self::new(274),
            726 => Self::new(275),
            727 => Self::new(278),
            728 => Self::new(279),
            729 => Self::new(280),
            730 => Self::new(281),
            731 => Self::new(282),
            732 => Self::new(283),
            733 => Self::new(284),
            735 => Self::new(288),
            737 => Self::new(345),
            874 => Self::new(359),
            877 => Self::new(353),
            878 => Self::new(356),
            _ => None,
        }
    }
}

pub static ALL_ITEMS_GEN3: [&ItemMetadataPastGen; ITEM_MAX_GEN3] = [
    &ItemMetadataPastGen {
        id: 1,
        modern_id: Some(1),
        name: "Master Ball",
    },
    &ItemMetadataPastGen {
        id: 2,
        modern_id: Some(2),
        name: "Ultra Ball",
    },
    &ItemMetadataPastGen {
        id: 3,
        modern_id: Some(3),
        name: "Great Ball",
    },
    &ItemMetadataPastGen {
        id: 4,
        modern_id: Some(4),
        name: "Poké Ball",
    },
    &ItemMetadataPastGen {
        id: 5,
        modern_id: Some(5),
        name: "Safari Ball",
    },
    &ItemMetadataPastGen {
        id: 6,
        modern_id: Some(6),
        name: "Net Ball",
    },
    &ItemMetadataPastGen {
        id: 7,
        modern_id: Some(7),
        name: "Dive Ball",
    },
    &ItemMetadataPastGen {
        id: 8,
        modern_id: Some(8),
        name: "Nest Ball",
    },
    &ItemMetadataPastGen {
        id: 9,
        modern_id: Some(9),
        name: "Repeat Ball",
    },
    &ItemMetadataPastGen {
        id: 10,
        modern_id: Some(10),
        name: "Timer Ball",
    },
    &ItemMetadataPastGen {
        id: 11,
        modern_id: Some(11),
        name: "Luxury Ball",
    },
    &ItemMetadataPastGen {
        id: 12,
        modern_id: Some(12),
        name: "Premier Ball",
    },
    &ItemMetadataPastGen {
        id: 13,
        modern_id: Some(17),
        name: "Potion",
    },
    &ItemMetadataPastGen {
        id: 14,
        modern_id: Some(18),
        name: "Antidote",
    },
    &ItemMetadataPastGen {
        id: 15,
        modern_id: Some(19),
        name: "Burn Heal",
    },
    &ItemMetadataPastGen {
        id: 16,
        modern_id: Some(20),
        name: "Ice Heal",
    },
    &ItemMetadataPastGen {
        id: 17,
        modern_id: Some(21),
        name: "Awakening",
    },
    &ItemMetadataPastGen {
        id: 18,
        modern_id: Some(22),
        name: "Parlyz Heal",
    },
    &ItemMetadataPastGen {
        id: 19,
        modern_id: Some(23),
        name: "Full Restore",
    },
    &ItemMetadataPastGen {
        id: 20,
        modern_id: Some(24),
        name: "Max Potion",
    },
    &ItemMetadataPastGen {
        id: 21,
        modern_id: Some(25),
        name: "Hyper Potion",
    },
    &ItemMetadataPastGen {
        id: 22,
        modern_id: Some(26),
        name: "Super Potion",
    },
    &ItemMetadataPastGen {
        id: 23,
        modern_id: Some(27),
        name: "Full Heal",
    },
    &ItemMetadataPastGen {
        id: 24,
        modern_id: Some(28),
        name: "Revive",
    },
    &ItemMetadataPastGen {
        id: 25,
        modern_id: Some(29),
        name: "Max Revive",
    },
    &ItemMetadataPastGen {
        id: 26,
        modern_id: Some(30),
        name: "Fresh Water",
    },
    &ItemMetadataPastGen {
        id: 27,
        modern_id: Some(31),
        name: "Soda Pop",
    },
    &ItemMetadataPastGen {
        id: 28,
        modern_id: Some(32),
        name: "Lemonade",
    },
    &ItemMetadataPastGen {
        id: 29,
        modern_id: Some(33),
        name: "Moomoo Milk",
    },
    &ItemMetadataPastGen {
        id: 30,
        modern_id: Some(34),
        name: "EnergyPowder",
    },
    &ItemMetadataPastGen {
        id: 31,
        modern_id: Some(35),
        name: "Energy Root",
    },
    &ItemMetadataPastGen {
        id: 32,
        modern_id: Some(36),
        name: "Heal Powder",
    },
    &ItemMetadataPastGen {
        id: 33,
        modern_id: Some(37),
        name: "Revival Herb",
    },
    &ItemMetadataPastGen {
        id: 34,
        modern_id: Some(38),
        name: "Ether",
    },
    &ItemMetadataPastGen {
        id: 35,
        modern_id: Some(39),
        name: "Max Ether",
    },
    &ItemMetadataPastGen {
        id: 36,
        modern_id: Some(40),
        name: "Elixir",
    },
    &ItemMetadataPastGen {
        id: 37,
        modern_id: Some(41),
        name: "Max Elixir",
    },
    &ItemMetadataPastGen {
        id: 38,
        modern_id: Some(42),
        name: "Lava Cookie",
    },
    &ItemMetadataPastGen {
        id: 39,
        modern_id: Some(65),
        name: "Blue Flute",
    },
    &ItemMetadataPastGen {
        id: 40,
        modern_id: Some(66),
        name: "Yellow Flute",
    },
    &ItemMetadataPastGen {
        id: 41,
        modern_id: Some(67),
        name: "Red Flute",
    },
    &ItemMetadataPastGen {
        id: 42,
        modern_id: Some(68),
        name: "Black Flute",
    },
    &ItemMetadataPastGen {
        id: 43,
        modern_id: Some(69),
        name: "White Flute",
    },
    &ItemMetadataPastGen {
        id: 44,
        modern_id: Some(43),
        name: "Berry Juice",
    },
    &ItemMetadataPastGen {
        id: 45,
        modern_id: Some(44),
        name: "Sacred Ash",
    },
    &ItemMetadataPastGen {
        id: 46,
        modern_id: Some(70),
        name: "Shoal Salt",
    },
    &ItemMetadataPastGen {
        id: 47,
        modern_id: Some(71),
        name: "Shoal Shell",
    },
    &ItemMetadataPastGen {
        id: 48,
        modern_id: Some(72),
        name: "Red Shard",
    },
    &ItemMetadataPastGen {
        id: 49,
        modern_id: Some(73),
        name: "Blue Shard",
    },
    &ItemMetadataPastGen {
        id: 50,
        modern_id: Some(74),
        name: "Yellow Shard",
    },
    &ItemMetadataPastGen {
        id: 51,
        modern_id: Some(75),
        name: "Green Shard",
    },
    &ItemMetadataPastGen {
        id: 52,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 53,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 54,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 55,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 56,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 57,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 58,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 59,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 60,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 61,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 62,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 63,
        modern_id: Some(45),
        name: "HP Up",
    },
    &ItemMetadataPastGen {
        id: 64,
        modern_id: Some(46),
        name: "Protein",
    },
    &ItemMetadataPastGen {
        id: 65,
        modern_id: Some(47),
        name: "Iron",
    },
    &ItemMetadataPastGen {
        id: 66,
        modern_id: Some(48),
        name: "Carbos",
    },
    &ItemMetadataPastGen {
        id: 67,
        modern_id: Some(49),
        name: "Calcium",
    },
    &ItemMetadataPastGen {
        id: 68,
        modern_id: Some(50),
        name: "Rare Candy",
    },
    &ItemMetadataPastGen {
        id: 69,
        modern_id: Some(51),
        name: "PP Up",
    },
    &ItemMetadataPastGen {
        id: 70,
        modern_id: Some(52),
        name: "Zinc",
    },
    &ItemMetadataPastGen {
        id: 71,
        modern_id: Some(53),
        name: "PP Max",
    },
    &ItemMetadataPastGen {
        id: 72,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 73,
        modern_id: Some(55),
        name: "Guard Spec.",
    },
    &ItemMetadataPastGen {
        id: 74,
        modern_id: Some(56),
        name: "Dire Hit",
    },
    &ItemMetadataPastGen {
        id: 75,
        modern_id: Some(57),
        name: "X Attack",
    },
    &ItemMetadataPastGen {
        id: 76,
        modern_id: Some(58),
        name: "X Defend",
    },
    &ItemMetadataPastGen {
        id: 77,
        modern_id: Some(59),
        name: "X Speed",
    },
    &ItemMetadataPastGen {
        id: 78,
        modern_id: Some(60),
        name: "X Accuracy",
    },
    &ItemMetadataPastGen {
        id: 79,
        modern_id: None,
        name: "X Special",
    },
    &ItemMetadataPastGen {
        id: 80,
        modern_id: Some(63),
        name: "Poké Doll",
    },
    &ItemMetadataPastGen {
        id: 81,
        modern_id: Some(64),
        name: "Fluffy Tail",
    },
    &ItemMetadataPastGen {
        id: 82,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 83,
        modern_id: Some(76),
        name: "Super Repel",
    },
    &ItemMetadataPastGen {
        id: 84,
        modern_id: Some(77),
        name: "Max Repel",
    },
    &ItemMetadataPastGen {
        id: 85,
        modern_id: Some(78),
        name: "Escape Rope",
    },
    &ItemMetadataPastGen {
        id: 86,
        modern_id: Some(79),
        name: "Repel",
    },
    &ItemMetadataPastGen {
        id: 87,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 88,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 89,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 90,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 91,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 92,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 93,
        modern_id: Some(80),
        name: "Sun Stone",
    },
    &ItemMetadataPastGen {
        id: 94,
        modern_id: Some(81),
        name: "Moon Stone",
    },
    &ItemMetadataPastGen {
        id: 95,
        modern_id: Some(82),
        name: "Fire Stone",
    },
    &ItemMetadataPastGen {
        id: 96,
        modern_id: Some(83),
        name: "Thunder Stone",
    },
    &ItemMetadataPastGen {
        id: 97,
        modern_id: Some(84),
        name: "Water Stone",
    },
    &ItemMetadataPastGen {
        id: 98,
        modern_id: Some(85),
        name: "Leaf Stone",
    },
    &ItemMetadataPastGen {
        id: 99,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 100,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 101,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 102,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 103,
        modern_id: Some(86),
        name: "TinyMushroom",
    },
    &ItemMetadataPastGen {
        id: 104,
        modern_id: Some(87),
        name: "Big Mushroom",
    },
    &ItemMetadataPastGen {
        id: 105,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 106,
        modern_id: Some(88),
        name: "Pearl",
    },
    &ItemMetadataPastGen {
        id: 107,
        modern_id: Some(89),
        name: "Big Pearl",
    },
    &ItemMetadataPastGen {
        id: 108,
        modern_id: Some(90),
        name: "Stardust",
    },
    &ItemMetadataPastGen {
        id: 109,
        modern_id: Some(91),
        name: "Star Piece",
    },
    &ItemMetadataPastGen {
        id: 110,
        modern_id: Some(92),
        name: "Nugget",
    },
    &ItemMetadataPastGen {
        id: 111,
        modern_id: Some(93),
        name: "Heart Scale",
    },
    &ItemMetadataPastGen {
        id: 112,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 113,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 114,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 115,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 116,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 117,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 118,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 119,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 120,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 121,
        modern_id: None,
        name: "Orange Mail",
    },
    &ItemMetadataPastGen {
        id: 122,
        modern_id: None,
        name: "Harbor Mail",
    },
    &ItemMetadataPastGen {
        id: 123,
        modern_id: None,
        name: "Glitter Mail",
    },
    &ItemMetadataPastGen {
        id: 124,
        modern_id: None,
        name: "Mech Mail",
    },
    &ItemMetadataPastGen {
        id: 125,
        modern_id: None,
        name: "Wood Mail",
    },
    &ItemMetadataPastGen {
        id: 126,
        modern_id: None,
        name: "Wave Mail",
    },
    &ItemMetadataPastGen {
        id: 127,
        modern_id: None,
        name: "Bead Mail",
    },
    &ItemMetadataPastGen {
        id: 128,
        modern_id: None,
        name: "Shadow Mail",
    },
    &ItemMetadataPastGen {
        id: 129,
        modern_id: None,
        name: "Tropic Mail",
    },
    &ItemMetadataPastGen {
        id: 130,
        modern_id: None,
        name: "Dream Mail",
    },
    &ItemMetadataPastGen {
        id: 131,
        modern_id: None,
        name: "Fab Mail",
    },
    &ItemMetadataPastGen {
        id: 132,
        modern_id: None,
        name: "Retro Mail",
    },
    &ItemMetadataPastGen {
        id: 133,
        modern_id: Some(149),
        name: "Cheri Berry",
    },
    &ItemMetadataPastGen {
        id: 134,
        modern_id: Some(150),
        name: "Chesto Berry",
    },
    &ItemMetadataPastGen {
        id: 135,
        modern_id: Some(151),
        name: "Pecha Berry",
    },
    &ItemMetadataPastGen {
        id: 136,
        modern_id: Some(152),
        name: "Rawst Berry",
    },
    &ItemMetadataPastGen {
        id: 137,
        modern_id: Some(153),
        name: "Aspear Berry",
    },
    &ItemMetadataPastGen {
        id: 138,
        modern_id: Some(154),
        name: "Leppa Berry",
    },
    &ItemMetadataPastGen {
        id: 139,
        modern_id: Some(155),
        name: "Oran Berry",
    },
    &ItemMetadataPastGen {
        id: 140,
        modern_id: Some(156),
        name: "Persim Berry",
    },
    &ItemMetadataPastGen {
        id: 141,
        modern_id: Some(157),
        name: "Lum Berry",
    },
    &ItemMetadataPastGen {
        id: 142,
        modern_id: Some(158),
        name: "Sitrus Berry",
    },
    &ItemMetadataPastGen {
        id: 143,
        modern_id: Some(159),
        name: "Figy Berry",
    },
    &ItemMetadataPastGen {
        id: 144,
        modern_id: Some(160),
        name: "Wiki Berry",
    },
    &ItemMetadataPastGen {
        id: 145,
        modern_id: Some(161),
        name: "Mago Berry",
    },
    &ItemMetadataPastGen {
        id: 146,
        modern_id: Some(162),
        name: "Aguav Berry",
    },
    &ItemMetadataPastGen {
        id: 147,
        modern_id: Some(163),
        name: "Iapapa Berry",
    },
    &ItemMetadataPastGen {
        id: 148,
        modern_id: Some(164),
        name: "Razz Berry",
    },
    &ItemMetadataPastGen {
        id: 149,
        modern_id: Some(165),
        name: "Bluk Berry",
    },
    &ItemMetadataPastGen {
        id: 150,
        modern_id: Some(166),
        name: "Nanab Berry",
    },
    &ItemMetadataPastGen {
        id: 151,
        modern_id: Some(167),
        name: "Wepear Berry",
    },
    &ItemMetadataPastGen {
        id: 152,
        modern_id: Some(168),
        name: "Pinap Berry",
    },
    &ItemMetadataPastGen {
        id: 153,
        modern_id: Some(169),
        name: "Pomeg Berry",
    },
    &ItemMetadataPastGen {
        id: 154,
        modern_id: Some(170),
        name: "Kelpsy Berry",
    },
    &ItemMetadataPastGen {
        id: 155,
        modern_id: Some(171),
        name: "Qualot Berry",
    },
    &ItemMetadataPastGen {
        id: 156,
        modern_id: Some(172),
        name: "Hondew Berry",
    },
    &ItemMetadataPastGen {
        id: 157,
        modern_id: Some(173),
        name: "Grepa Berry",
    },
    &ItemMetadataPastGen {
        id: 158,
        modern_id: Some(174),
        name: "Tamato Berry",
    },
    &ItemMetadataPastGen {
        id: 159,
        modern_id: Some(175),
        name: "Cornn Berry",
    },
    &ItemMetadataPastGen {
        id: 160,
        modern_id: Some(176),
        name: "Magost Berry",
    },
    &ItemMetadataPastGen {
        id: 161,
        modern_id: Some(177),
        name: "Rabuta Berry",
    },
    &ItemMetadataPastGen {
        id: 162,
        modern_id: Some(178),
        name: "Nomel Berry",
    },
    &ItemMetadataPastGen {
        id: 163,
        modern_id: Some(179),
        name: "Spelon Berry",
    },
    &ItemMetadataPastGen {
        id: 164,
        modern_id: Some(180),
        name: "Pamtre Berry",
    },
    &ItemMetadataPastGen {
        id: 165,
        modern_id: Some(181),
        name: "Watmel Berry",
    },
    &ItemMetadataPastGen {
        id: 166,
        modern_id: Some(182),
        name: "Durin Berry",
    },
    &ItemMetadataPastGen {
        id: 167,
        modern_id: Some(183),
        name: "Belue Berry",
    },
    &ItemMetadataPastGen {
        id: 168,
        modern_id: Some(201),
        name: "Liechi Berry",
    },
    &ItemMetadataPastGen {
        id: 169,
        modern_id: Some(202),
        name: "Ganlon Berry",
    },
    &ItemMetadataPastGen {
        id: 170,
        modern_id: Some(203),
        name: "Salac Berry",
    },
    &ItemMetadataPastGen {
        id: 171,
        modern_id: Some(204),
        name: "Petaya Berry",
    },
    &ItemMetadataPastGen {
        id: 172,
        modern_id: Some(205),
        name: "Apicot Berry",
    },
    &ItemMetadataPastGen {
        id: 173,
        modern_id: Some(206),
        name: "Lansat Berry",
    },
    &ItemMetadataPastGen {
        id: 174,
        modern_id: Some(207),
        name: "Starf Berry",
    },
    &ItemMetadataPastGen {
        id: 175,
        modern_id: Some(208),
        name: "Enigma Berry",
    },
    &ItemMetadataPastGen {
        id: 176,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 177,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 178,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 179,
        modern_id: Some(213),
        name: "BrightPowder",
    },
    &ItemMetadataPastGen {
        id: 180,
        modern_id: Some(214),
        name: "White Herb",
    },
    &ItemMetadataPastGen {
        id: 181,
        modern_id: Some(215),
        name: "Macho Brace",
    },
    &ItemMetadataPastGen {
        id: 182,
        modern_id: Some(216),
        name: "Exp. Share",
    },
    &ItemMetadataPastGen {
        id: 183,
        modern_id: Some(217),
        name: "Quick Claw",
    },
    &ItemMetadataPastGen {
        id: 184,
        modern_id: Some(218),
        name: "Soothe Bell",
    },
    &ItemMetadataPastGen {
        id: 185,
        modern_id: Some(219),
        name: "Mental Herb",
    },
    &ItemMetadataPastGen {
        id: 186,
        modern_id: Some(220),
        name: "Choice Band",
    },
    &ItemMetadataPastGen {
        id: 187,
        modern_id: Some(221),
        name: "King's Rock",
    },
    &ItemMetadataPastGen {
        id: 188,
        modern_id: Some(222),
        name: "SilverPowder",
    },
    &ItemMetadataPastGen {
        id: 189,
        modern_id: Some(223),
        name: "Amulet Coin",
    },
    &ItemMetadataPastGen {
        id: 190,
        modern_id: Some(224),
        name: "Cleanse Tag",
    },
    &ItemMetadataPastGen {
        id: 191,
        modern_id: Some(225),
        name: "Soul Dew",
    },
    &ItemMetadataPastGen {
        id: 192,
        modern_id: Some(226),
        name: "DeepSeaTooth",
    },
    &ItemMetadataPastGen {
        id: 193,
        modern_id: Some(227),
        name: "DeepSeaScale",
    },
    &ItemMetadataPastGen {
        id: 194,
        modern_id: Some(228),
        name: "Smoke Ball",
    },
    &ItemMetadataPastGen {
        id: 195,
        modern_id: Some(229),
        name: "Everstone",
    },
    &ItemMetadataPastGen {
        id: 196,
        modern_id: Some(230),
        name: "Focus Band",
    },
    &ItemMetadataPastGen {
        id: 197,
        modern_id: Some(231),
        name: "Lucky Egg",
    },
    &ItemMetadataPastGen {
        id: 198,
        modern_id: Some(232),
        name: "Scope Lens",
    },
    &ItemMetadataPastGen {
        id: 199,
        modern_id: Some(233),
        name: "Metal Coat",
    },
    &ItemMetadataPastGen {
        id: 200,
        modern_id: Some(234),
        name: "Leftovers",
    },
    &ItemMetadataPastGen {
        id: 201,
        modern_id: Some(235),
        name: "Dragon Scale",
    },
    &ItemMetadataPastGen {
        id: 202,
        modern_id: Some(236),
        name: "Light Ball",
    },
    &ItemMetadataPastGen {
        id: 203,
        modern_id: Some(237),
        name: "Soft Sand",
    },
    &ItemMetadataPastGen {
        id: 204,
        modern_id: Some(238),
        name: "Hard Stone",
    },
    &ItemMetadataPastGen {
        id: 205,
        modern_id: Some(239),
        name: "Miracle Seed",
    },
    &ItemMetadataPastGen {
        id: 206,
        modern_id: Some(240),
        name: "BlackGlasses",
    },
    &ItemMetadataPastGen {
        id: 207,
        modern_id: Some(241),
        name: "Black Belt",
    },
    &ItemMetadataPastGen {
        id: 208,
        modern_id: Some(242),
        name: "Magnet",
    },
    &ItemMetadataPastGen {
        id: 209,
        modern_id: Some(243),
        name: "Mystic Water",
    },
    &ItemMetadataPastGen {
        id: 210,
        modern_id: Some(244),
        name: "Sharp Beak",
    },
    &ItemMetadataPastGen {
        id: 211,
        modern_id: Some(245),
        name: "Poison Barb",
    },
    &ItemMetadataPastGen {
        id: 212,
        modern_id: Some(246),
        name: "NeverMeltIce",
    },
    &ItemMetadataPastGen {
        id: 213,
        modern_id: Some(247),
        name: "Spell Tag",
    },
    &ItemMetadataPastGen {
        id: 214,
        modern_id: Some(248),
        name: "TwistedSpoon",
    },
    &ItemMetadataPastGen {
        id: 215,
        modern_id: Some(249),
        name: "Charcoal",
    },
    &ItemMetadataPastGen {
        id: 216,
        modern_id: Some(250),
        name: "Dragon Fang",
    },
    &ItemMetadataPastGen {
        id: 217,
        modern_id: Some(251),
        name: "Silk Scarf",
    },
    &ItemMetadataPastGen {
        id: 218,
        modern_id: Some(252),
        name: "Up-Grade",
    },
    &ItemMetadataPastGen {
        id: 219,
        modern_id: Some(253),
        name: "Shell Bell",
    },
    &ItemMetadataPastGen {
        id: 220,
        modern_id: Some(254),
        name: "Sea Incense",
    },
    &ItemMetadataPastGen {
        id: 221,
        modern_id: Some(255),
        name: "Lax Incense",
    },
    &ItemMetadataPastGen {
        id: 222,
        modern_id: Some(256),
        name: "Lucky Punch",
    },
    &ItemMetadataPastGen {
        id: 223,
        modern_id: Some(257),
        name: "Metal Powder",
    },
    &ItemMetadataPastGen {
        id: 224,
        modern_id: Some(258),
        name: "Thick Club",
    },
    &ItemMetadataPastGen {
        id: 225,
        modern_id: Some(259),
        name: "Stick",
    },
    &ItemMetadataPastGen {
        id: 226,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 227,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 228,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 229,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 230,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 231,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 232,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 233,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 234,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 235,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 236,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 237,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 238,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 239,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 240,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 241,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 242,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 243,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 244,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 245,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 246,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 247,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 248,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 249,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 250,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 251,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 252,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 253,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 254,
        modern_id: Some(260),
        name: "Red Scarf",
    },
    &ItemMetadataPastGen {
        id: 255,
        modern_id: Some(261),
        name: "Blue Scarf",
    },
    &ItemMetadataPastGen {
        id: 256,
        modern_id: Some(262),
        name: "Pink Scarf",
    },
    &ItemMetadataPastGen {
        id: 257,
        modern_id: Some(263),
        name: "Green Scarf",
    },
    &ItemMetadataPastGen {
        id: 258,
        modern_id: Some(264),
        name: "Yellow Scarf",
    },
    &ItemMetadataPastGen {
        id: 259,
        modern_id: Some(718),
        name: "Mach Bike",
    },
    &ItemMetadataPastGen {
        id: 260,
        modern_id: Some(444),
        name: "Coin Case",
    },
    &ItemMetadataPastGen {
        id: 261,
        modern_id: Some(471),
        name: "Itemfinder",
    },
    &ItemMetadataPastGen {
        id: 262,
        modern_id: Some(445),
        name: "Old Rod",
    },
    &ItemMetadataPastGen {
        id: 263,
        modern_id: Some(446),
        name: "Good Rod",
    },
    &ItemMetadataPastGen {
        id: 264,
        modern_id: Some(447),
        name: "Super Rod",
    },
    &ItemMetadataPastGen {
        id: 265,
        modern_id: Some(456),
        name: "S.S. Ticket",
    },
    &ItemMetadataPastGen {
        id: 266,
        modern_id: Some(457),
        name: "Contest Pass",
    },
    &ItemMetadataPastGen {
        id: 267,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 268,
        modern_id: Some(720),
        name: "Wailmer Pail",
    },
    &ItemMetadataPastGen {
        id: 269,
        modern_id: Some(721),
        name: "Devon Goods",
    },
    &ItemMetadataPastGen {
        id: 270,
        modern_id: Some(722),
        name: "Soot Sack",
    },
    &ItemMetadataPastGen {
        id: 271,
        modern_id: Some(476),
        name: "Basement Key",
    },
    &ItemMetadataPastGen {
        id: 272,
        modern_id: Some(719),
        name: "Acro Bike",
    },
    &ItemMetadataPastGen {
        id: 273,
        modern_id: None,
        name: "Pokéblock Case",
    },
    &ItemMetadataPastGen {
        id: 274,
        modern_id: Some(725),
        name: "Letter",
    },
    &ItemMetadataPastGen {
        id: 275,
        modern_id: Some(726),
        name: "Eon Ticket",
    },
    &ItemMetadataPastGen {
        id: 276,
        modern_id: Some(534),
        name: "Red Orb",
    },
    &ItemMetadataPastGen {
        id: 277,
        modern_id: Some(535),
        name: "Blue Orb",
    },
    &ItemMetadataPastGen {
        id: 278,
        modern_id: Some(727),
        name: "Scanner",
    },
    &ItemMetadataPastGen {
        id: 279,
        modern_id: Some(728),
        name: "Go-Goggles",
    },
    &ItemMetadataPastGen {
        id: 280,
        modern_id: Some(729),
        name: "Meteorite",
    },
    &ItemMetadataPastGen {
        id: 281,
        modern_id: Some(730),
        name: "Rm. 1 Key",
    },
    &ItemMetadataPastGen {
        id: 282,
        modern_id: Some(731),
        name: "Rm. 2 Key",
    },
    &ItemMetadataPastGen {
        id: 283,
        modern_id: Some(732),
        name: "Rm. 4 Key",
    },
    &ItemMetadataPastGen {
        id: 284,
        modern_id: Some(733),
        name: "Rm. 6 Key",
    },
    &ItemMetadataPastGen {
        id: 285,
        modern_id: Some(463),
        name: "Storage Key",
    },
    &ItemMetadataPastGen {
        id: 286,
        modern_id: Some(99),
        name: "Root Fossil",
    },
    &ItemMetadataPastGen {
        id: 287,
        modern_id: Some(100),
        name: "Claw Fossil",
    },
    &ItemMetadataPastGen {
        id: 288,
        modern_id: Some(735),
        name: "Devon Scope",
    },
    &ItemMetadataPastGen {
        id: 289,
        modern_id: Some(328),
        name: "TM01",
    },
    &ItemMetadataPastGen {
        id: 290,
        modern_id: Some(329),
        name: "TM02",
    },
    &ItemMetadataPastGen {
        id: 291,
        modern_id: Some(330),
        name: "TM03",
    },
    &ItemMetadataPastGen {
        id: 292,
        modern_id: Some(331),
        name: "TM04",
    },
    &ItemMetadataPastGen {
        id: 293,
        modern_id: Some(332),
        name: "TM05",
    },
    &ItemMetadataPastGen {
        id: 294,
        modern_id: Some(333),
        name: "TM06",
    },
    &ItemMetadataPastGen {
        id: 295,
        modern_id: Some(334),
        name: "TM07",
    },
    &ItemMetadataPastGen {
        id: 296,
        modern_id: Some(335),
        name: "TM08",
    },
    &ItemMetadataPastGen {
        id: 297,
        modern_id: Some(336),
        name: "TM09",
    },
    &ItemMetadataPastGen {
        id: 298,
        modern_id: Some(337),
        name: "TM10",
    },
    &ItemMetadataPastGen {
        id: 299,
        modern_id: Some(338),
        name: "TM11",
    },
    &ItemMetadataPastGen {
        id: 300,
        modern_id: Some(339),
        name: "TM12",
    },
    &ItemMetadataPastGen {
        id: 301,
        modern_id: Some(340),
        name: "TM13",
    },
    &ItemMetadataPastGen {
        id: 302,
        modern_id: Some(341),
        name: "TM14",
    },
    &ItemMetadataPastGen {
        id: 303,
        modern_id: Some(342),
        name: "TM15",
    },
    &ItemMetadataPastGen {
        id: 304,
        modern_id: Some(343),
        name: "TM16",
    },
    &ItemMetadataPastGen {
        id: 305,
        modern_id: Some(344),
        name: "TM17",
    },
    &ItemMetadataPastGen {
        id: 306,
        modern_id: Some(345),
        name: "TM18",
    },
    &ItemMetadataPastGen {
        id: 307,
        modern_id: Some(346),
        name: "TM19",
    },
    &ItemMetadataPastGen {
        id: 308,
        modern_id: Some(347),
        name: "TM20",
    },
    &ItemMetadataPastGen {
        id: 309,
        modern_id: Some(348),
        name: "TM21",
    },
    &ItemMetadataPastGen {
        id: 310,
        modern_id: Some(349),
        name: "TM22",
    },
    &ItemMetadataPastGen {
        id: 311,
        modern_id: Some(350),
        name: "TM23",
    },
    &ItemMetadataPastGen {
        id: 312,
        modern_id: Some(351),
        name: "TM24",
    },
    &ItemMetadataPastGen {
        id: 313,
        modern_id: Some(352),
        name: "TM25",
    },
    &ItemMetadataPastGen {
        id: 314,
        modern_id: Some(353),
        name: "TM26",
    },
    &ItemMetadataPastGen {
        id: 315,
        modern_id: Some(354),
        name: "TM27",
    },
    &ItemMetadataPastGen {
        id: 316,
        modern_id: Some(355),
        name: "TM28",
    },
    &ItemMetadataPastGen {
        id: 317,
        modern_id: Some(356),
        name: "TM29",
    },
    &ItemMetadataPastGen {
        id: 318,
        modern_id: Some(357),
        name: "TM30",
    },
    &ItemMetadataPastGen {
        id: 319,
        modern_id: Some(358),
        name: "TM31",
    },
    &ItemMetadataPastGen {
        id: 320,
        modern_id: Some(359),
        name: "TM32",
    },
    &ItemMetadataPastGen {
        id: 321,
        modern_id: Some(360),
        name: "TM33",
    },
    &ItemMetadataPastGen {
        id: 322,
        modern_id: Some(361),
        name: "TM34",
    },
    &ItemMetadataPastGen {
        id: 323,
        modern_id: Some(362),
        name: "TM35",
    },
    &ItemMetadataPastGen {
        id: 324,
        modern_id: Some(363),
        name: "TM36",
    },
    &ItemMetadataPastGen {
        id: 325,
        modern_id: Some(364),
        name: "TM37",
    },
    &ItemMetadataPastGen {
        id: 326,
        modern_id: Some(365),
        name: "TM38",
    },
    &ItemMetadataPastGen {
        id: 327,
        modern_id: Some(366),
        name: "TM39",
    },
    &ItemMetadataPastGen {
        id: 328,
        modern_id: Some(367),
        name: "TM40",
    },
    &ItemMetadataPastGen {
        id: 329,
        modern_id: Some(368),
        name: "TM41",
    },
    &ItemMetadataPastGen {
        id: 330,
        modern_id: Some(369),
        name: "TM42",
    },
    &ItemMetadataPastGen {
        id: 331,
        modern_id: Some(370),
        name: "TM43",
    },
    &ItemMetadataPastGen {
        id: 332,
        modern_id: Some(371),
        name: "TM44",
    },
    &ItemMetadataPastGen {
        id: 333,
        modern_id: Some(372),
        name: "TM45",
    },
    &ItemMetadataPastGen {
        id: 334,
        modern_id: Some(373),
        name: "TM46",
    },
    &ItemMetadataPastGen {
        id: 335,
        modern_id: Some(374),
        name: "TM47",
    },
    &ItemMetadataPastGen {
        id: 336,
        modern_id: Some(375),
        name: "TM48",
    },
    &ItemMetadataPastGen {
        id: 337,
        modern_id: Some(376),
        name: "TM49",
    },
    &ItemMetadataPastGen {
        id: 338,
        modern_id: Some(377),
        name: "TM50",
    },
    &ItemMetadataPastGen {
        id: 339,
        modern_id: Some(420),
        name: "HM01",
    },
    &ItemMetadataPastGen {
        id: 340,
        modern_id: Some(421),
        name: "HM02",
    },
    &ItemMetadataPastGen {
        id: 341,
        modern_id: Some(422),
        name: "HM03",
    },
    &ItemMetadataPastGen {
        id: 342,
        modern_id: Some(423),
        name: "HM04",
    },
    &ItemMetadataPastGen {
        id: 343,
        modern_id: Some(424),
        name: "HM05",
    },
    &ItemMetadataPastGen {
        id: 344,
        modern_id: Some(425),
        name: "HM06",
    },
    &ItemMetadataPastGen {
        id: 345,
        modern_id: Some(737),
        name: "HM07",
    },
    &ItemMetadataPastGen {
        id: 346,
        modern_id: None,
        name: "HM08",
    },
    &ItemMetadataPastGen {
        id: 347,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 348,
        modern_id: Some(114),
        name: "???",
    },
    &ItemMetadataPastGen {
        id: 349,
        modern_id: Some(459),
        name: "Oak's Parcel",
    },
    &ItemMetadataPastGen {
        id: 350,
        modern_id: Some(651),
        name: "Poké Flute",
    },
    &ItemMetadataPastGen {
        id: 351,
        modern_id: Some(467),
        name: "Secret Key",
    },
    &ItemMetadataPastGen {
        id: 352,
        modern_id: None,
        name: "Bike Voucher",
    },
    &ItemMetadataPastGen {
        id: 353,
        modern_id: Some(877),
        name: "Gold Teeth",
    },
    &ItemMetadataPastGen {
        id: 354,
        modern_id: Some(103),
        name: "Old Amber",
    },
    &ItemMetadataPastGen {
        id: 355,
        modern_id: Some(475),
        name: "Card Key",
    },
    &ItemMetadataPastGen {
        id: 356,
        modern_id: Some(878),
        name: "Lift Key",
    },
    &ItemMetadataPastGen {
        id: 357,
        modern_id: Some(101),
        name: "Helix Fossil",
    },
    &ItemMetadataPastGen {
        id: 358,
        modern_id: Some(102),
        name: "Dome Fossil",
    },
    &ItemMetadataPastGen {
        id: 359,
        modern_id: Some(874),
        name: "Silph Scope",
    },
    &ItemMetadataPastGen {
        id: 360,
        modern_id: Some(450),
        name: "Bicycle",
    },
    &ItemMetadataPastGen {
        id: 361,
        modern_id: Some(442),
        name: "Town Map",
    },
    &ItemMetadataPastGen {
        id: 362,
        modern_id: Some(443),
        name: "Vs. Seeker",
    },
    &ItemMetadataPastGen {
        id: 363,
        modern_id: None,
        name: "Fame Checker",
    },
    &ItemMetadataPastGen {
        id: 364,
        modern_id: Some(123),
        name: "TM Case",
    },
    &ItemMetadataPastGen {
        id: 365,
        modern_id: None,
        name: "Berry Pouch",
    },
    &ItemMetadataPastGen {
        id: 366,
        modern_id: None,
        name: "Teachy TV",
    },
    &ItemMetadataPastGen {
        id: 367,
        modern_id: None,
        name: "Tri-Pass",
    },
    &ItemMetadataPastGen {
        id: 368,
        modern_id: None,
        name: "Rainbow Pass",
    },
    &ItemMetadataPastGen {
        id: 369,
        modern_id: Some(113),
        name: "Tea",
    },
    &ItemMetadataPastGen {
        id: 370,
        modern_id: None,
        name: "MysticTicket",
    },
    &ItemMetadataPastGen {
        id: 371,
        modern_id: None,
        name: "AuroraTicket",
    },
    &ItemMetadataPastGen {
        id: 372,
        modern_id: None,
        name: "Powder Jar",
    },
    &ItemMetadataPastGen {
        id: 373,
        modern_id: None,
        name: "Ruby",
    },
    &ItemMetadataPastGen {
        id: 374,
        modern_id: None,
        name: "Sapphire",
    },
    &ItemMetadataPastGen {
        id: 375,
        modern_id: None,
        name: "Magma Emblem",
    },
    &ItemMetadataPastGen {
        id: 376,
        modern_id: None,
        name: "Old Sea Map",
    },
];
