
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getState() : Promise<Result<AppStateInner, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFileCreated(absolutePath: string) : Promise<Result<number | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_created", { absolutePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getImageData(absolutePath: string) : Promise<Result<ImageResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_image_data", { absolutePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeFileBytes(absolutePath: string, bytes: number[]) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_file_bytes", { absolutePath, bytes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAppTheme(appTheme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_app_theme", { appTheme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validateRecentSaves() : Promise<Result<Partial<{ [key in string]: SaveRef }>, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_recent_saves") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadPlugin(remoteUrl: string) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_plugin", { remoteUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listInstalledPlugins() : Promise<Result<PluginMetadataWithIcon[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_installed_plugins") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadPluginCode(pluginId: string) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_plugin_code", { pluginId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePlugin(pluginId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_plugin", { pluginId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async handleWindowsAccelerator(menuEventId: string) : Promise<void> {
    await TAURI_INVOKE("handle_windows_accelerator", { menuEventId });
},
async openDirectory(absolutePath: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_directory", { absolutePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openFileLocation(filePath: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_file_location", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async findSuggestedSaves(saveFolders: string[]) : Promise<Result<PossibleSaves, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("find_suggested_saves", { saveFolders }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDataDirPath() : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_data_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeDataDir() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadBanks() : Promise<Result<StoredBankData, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_banks") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeBanks(bankData: StoredBankData) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_banks", { bankData }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPokedex() : Promise<Result<Pokedex, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_pokedex") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePokedex(updates: PokedexUpdate[]) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_pokedex", { updates }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startTransaction() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_transaction") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rollbackTransaction() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rollback_transaction") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async commitTransaction() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("commit_transaction") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSyncedState() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_synced_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSyncedState(stateIdentifier: string, action: JsonValue) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_synced_state", { stateIdentifier, action }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConvertStrategies() : Promise<Result<ConvertStrategies, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_convert_strategies") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateConvertStrategies(updates: ConvertStrategies) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_convert_strategies", { updates }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLookups() : Promise<Result<LookupState, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_lookups") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addToLookups(newEntries: LookupState) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_to_lookups", { newEntries }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeDangling() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_dangling") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOhpkmStore() : Promise<Result<Partial<{ [key in string]: string }>, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_ohpkm_store") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async permanentlyDeleteOhpkms(openhomeIds: string[]) : Promise<Result<Partial<{ [key in string]: string | null }>, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("permanently_delete_ohpkms", { openhomeIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLogsToday(filter: LogFilterJs) : Promise<Result<LogsResponse, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_logs_today", { filter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async log(entry: JsLogEntry) : Promise<void> {
    await TAURI_INVOKE("log", { entry });
},
async clearLogsForRange(startEpochSeconds: number, endEpochSeconds: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_logs_for_range", { startEpochSeconds, endEpochSeconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppStateInner = { is_dev: boolean; new_features_since_update: UpdateFeatures[]; transaction: TransactionState }
export type Bank = { id?: string; name: string | null; index: number; boxes: Box[]; current_box?: number }
export type Box = { id?: string; name: string | null; index: number; identifiers: Partial<{ [key in number]: string }> }
export type CommandError = string
export type ConvertStrategies = { strategies_by_id: Partial<{ [key in string]: NamedStrategy }>; default_strategy_id: string | null }
export type ConvertStrategy = { nickname__capitalization: NicknameCapitalization; metData__originAndLocation: MetDataStrategy; ivs__maxIfHyperTrained: boolean; personalityValue__preserveShiny: boolean; personalityValue__preserveGender: boolean; personalityValue__preserveNature: NatureStrategy; personalityValue__preserveUnownForm: boolean }
export type ImageResponse = { base64: string; extension: string }
export type JsLogEntry = { level: LogLevel; message: string; context: JsonValue | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type LogEntry = { timestamp: string; level: LogLevel; target: string | null; message: string; event?: string | null; fields: JsonValue | null; context: JsonValue | null; ohpkm_id?: string | null; is_tauri: boolean }
export type LogFilter = { start: string; end: string; ohpkm_id: string | null }
export type LogFilterJs = { start_epoch_seconds: number; end_epoch_seconds: number; ohpkm_id: string | null }
export type LogLevel = "TRACE" | "DEBUG" | "INFO" | "WARN" | "ERROR"
export type LogsResponse = { current: LogFilter; next: LogFilter; remaining_file_lines: LogEntry[] }
export type LookupState = { gen12: Partial<{ [key in string]: string }>; gen345: Partial<{ [key in string]: string }> }
export type MetDataStrategy = "UseLocationNameMatch" | "MaximizeLegality"
export type NamedStrategy = { name: string; strategy: ConvertStrategy }
export type NatureStrategy = "KeepOriginalNature" | "KeepMintNature"
export type NicknameCapitalization = "GameDefault" | "Modern"
export type PathData = { raw: string; name: string; dir: string; ext: string; separator: string }
export type PluginMetadataWithIcon = { id: string; name: string; version: string; api_version: number; icon_image: ImageResponse | null }
export type Pokedex = { byDexNumber: Partial<{ [key in number]: PokedexEntry }> }
export type PokedexEntry = { formes: Partial<{ [key in number]: PokedexStatus }> }
export type PokedexStatus = "Seen" | "Caught" | "ShinyCaught"
export type PokedexUpdate = { dexNumber: number; formIndex: number; status: PokedexStatus }
export type PossibleSaves = { citra: PathData[]; desmume: PathData[]; open_emu: PathData[] }
export type SaveRef = { filePath: PathData; game: number; trainerName: string; trainerID: string; lastOpened: number | null; lastModified: number | null; valid: boolean; pluginIdentifier: string | null }
export type StoredBankData = { banks: Bank[]; current_bank?: number }
export type TransactionState = { open_transaction: boolean; temp_files: string[] }
export type UpdateFeatures = { version: string; feature_messages: string[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
