// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async getState(): Promise<Result<AppStateInner, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_state') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async getFileCreated(absolutePath: string): Promise<Result<number | null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_file_created', { absolutePath }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async getImageData(absolutePath: string): Promise<Result<ImageResponse, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_image_data', { absolutePath }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async writeFileBytes(absolutePath: string, bytes: number[]): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('write_file_bytes', { absolutePath, bytes }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async setAppTheme(appTheme: string): Promise<Result<null, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('set_app_theme', { appTheme }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async validateRecentSaves(): Promise<Result<[string, SaveRef][], CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('validate_recent_saves') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async downloadPlugin(remoteUrl: string): Promise<Result<string, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('download_plugin', { remoteUrl }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async listInstalledPlugins(): Promise<Result<PluginMetadataWithIcon[], CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('list_installed_plugins') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async loadPluginCode(pluginId: string): Promise<Result<string, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('load_plugin_code', { pluginId }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async deletePlugin(pluginId: string): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('delete_plugin', { pluginId }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async handleWindowsAccelerator(menuEventId: string): Promise<void> {
    await TAURI_INVOKE('handle_windows_accelerator', { menuEventId })
  },
  async openDirectory(absolutePath: string): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('open_directory', { absolutePath }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async openFileLocation(filePath: string): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('open_file_location', { filePath }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async findSuggestedSaves(saveFolders: string[]): Promise<Result<PossibleSaves, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('find_suggested_saves', { saveFolders }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async getDataDirPath(): Promise<Result<string, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_data_dir_path') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async changeDataDir(shouldMove: boolean): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('change_data_dir', { shouldMove }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async loadBanks(): Promise<Result<StoredBankDataWasm, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('load_banks') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async writeBanks(bankData: StoredBankDataWasm): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('write_banks', { bankData }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async getPokedex(): Promise<Result<Pokedex, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_pokedex') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async updatePokedex(updates: PokedexUpdate[]): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('update_pokedex', { updates }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async startTransaction(): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('start_transaction') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async rollbackTransaction(): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('rollback_transaction') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async commitTransaction(): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('commit_transaction') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async saveSyncedState(): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('save_synced_state') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async updateSyncedState(
    stateIdentifier: string,
    action: JsonValue
  ): Promise<Result<null, CommandError>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('update_synced_state', { stateIdentifier, action }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async getConvertStrategies(): Promise<Result<ConvertStrategyEntries, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_convert_strategies') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async updateConvertStrategies(
    updates: ConvertStrategyEntries
  ): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('update_convert_strategies', { updates }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async getLookups(): Promise<Result<LookupStateStringIds, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_lookups') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async addToLookups(newEntries: LookupStateStringIds): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('add_to_lookups', { newEntries }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async removeDangling(): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('remove_dangling') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async getOhpkmStore(): Promise<Result<[string, string][], CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_ohpkm_store') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async searchOhpkmStore(
    paginationCursor: PaginationCursor,
    filters: Filter[]
  ): Promise<Result<PaginatedPage<string>, CommandError>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('search_ohpkm_store', { paginationCursor, filters }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async getOhpkmBytesById(openhomeId: string): Promise<Result<number[] | null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_ohpkm_bytes_by_id', { openhomeId }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async permanentlyDeleteOhpkms(
    openhomeIds: string[]
  ): Promise<Result<Partial<{ [key in string]: string | null }>, CommandError>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('permanently_delete_ohpkms', { openhomeIds }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async getLogsToday(filter: LogFilterJs): Promise<Result<LogsResponse, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_logs_today', { filter }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async clearLogsForRange(
    startEpochSeconds: number,
    endEpochSeconds: number
  ): Promise<Result<null, CommandError>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('clear_logs_for_range', { startEpochSeconds, endEpochSeconds }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
}

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

export type AppStateInner = {
  is_dev: boolean
  new_features_since_update: UpdateFeatures[]
  transaction: TransactionState
}
export type BankWasm = {
  id?: string
  name: string | null
  index: number
  boxes: BoxWasm[]
  current_box?: number
}
export type BoxWasm = {
  id?: string
  name: string | null
  index: number
  identifiers: Partial<{ [key in number]: string }>
}
export type CommandError = string
export type ConvertStrategy = {
  nickname__capitalization: NicknameCapitalization
  metData__originAndLocation: MetDataStrategy
  ivs__maxIfHyperTrained: boolean
  personalityValue__preserveShiny: boolean
  personalityValue__preserveGender: boolean
  personalityValue__preserveNature: NatureStrategy
  personalityValue__preserveUnownForm: boolean
}
export type ConvertStrategyEntries = {
  ids_and_strategies: [string, NamedStrategy][]
  default_strategy_id: string
}
export type Filter =
  | { nationalDex: NationalDex }
  | { formIndex: number }
  | { hasType: PkmType }
  | { lastSave: OriginGame }
  | { originGame: OriginGame }
  | { nature: NatureIndex }
  | { isShiny: boolean }
  | { gender: Gender }
  | { level: number }
  | { move: [number, MoveIndex] }
export type Gender = 'Male' | 'Female' | 'Genderless' | 'Invalid'
export type ImageResponse = { base64: string; extension: string }
export type JsonValue =
  null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type LogEntry = {
  timestamp: string
  level: LogLevel
  target?: string | null
  message: string
  event?: string | null
  fields: JsonValue | null
  context: JsonValue | null
  ohpkm_id?: string | null
  is_tauri: boolean
}
export type LogFilter = { start: string; end: string; ohpkm_id?: string | null }
export type LogFilterJs = {
  start_epoch_seconds: number
  end_epoch_seconds: number
  ohpkm_id?: string | null
}
export type LogLevel = 'TRACE' | 'DEBUG' | 'INFO' | 'WARN' | 'ERROR'
export type LogsResponse = { current: LogFilter; next: LogFilter; remaining_file_lines: LogEntry[] }
export type LookupStateStringIds = {
  gen12: Partial<{ [key in string]: string }>
  gen345: Partial<{ [key in string]: string }>
}
export type MetDataStrategy = 'UseLocationNameMatch' | 'MaximizeLegality'
export type MoveIndex = number | null
export type NamedStrategy = { name: string; strategy: ConvertStrategy }
export type NationalDex =
  | 'Bulbasaur'
  | 'Ivysaur'
  | 'Venusaur'
  | 'Charmander'
  | 'Charmeleon'
  | 'Charizard'
  | 'Squirtle'
  | 'Wartortle'
  | 'Blastoise'
  | 'Caterpie'
  | 'Metapod'
  | 'Butterfree'
  | 'Weedle'
  | 'Kakuna'
  | 'Beedrill'
  | 'Pidgey'
  | 'Pidgeotto'
  | 'Pidgeot'
  | 'Rattata'
  | 'Raticate'
  | 'Spearow'
  | 'Fearow'
  | 'Ekans'
  | 'Arbok'
  | 'Pikachu'
  | 'Raichu'
  | 'Sandshrew'
  | 'Sandslash'
  | 'NidoranF'
  | 'Nidorina'
  | 'Nidoqueen'
  | 'NidoranM'
  | 'Nidorino'
  | 'Nidoking'
  | 'Clefairy'
  | 'Clefable'
  | 'Vulpix'
  | 'Ninetales'
  | 'Jigglypuff'
  | 'Wigglytuff'
  | 'Zubat'
  | 'Golbat'
  | 'Oddish'
  | 'Gloom'
  | 'Vileplume'
  | 'Paras'
  | 'Parasect'
  | 'Venonat'
  | 'Venomoth'
  | 'Diglett'
  | 'Dugtrio'
  | 'Meowth'
  | 'Persian'
  | 'Psyduck'
  | 'Golduck'
  | 'Mankey'
  | 'Primeape'
  | 'Growlithe'
  | 'Arcanine'
  | 'Poliwag'
  | 'Poliwhirl'
  | 'Poliwrath'
  | 'Abra'
  | 'Kadabra'
  | 'Alakazam'
  | 'Machop'
  | 'Machoke'
  | 'Machamp'
  | 'Bellsprout'
  | 'Weepinbell'
  | 'Victreebel'
  | 'Tentacool'
  | 'Tentacruel'
  | 'Geodude'
  | 'Graveler'
  | 'Golem'
  | 'Ponyta'
  | 'Rapidash'
  | 'Slowpoke'
  | 'Slowbro'
  | 'Magnemite'
  | 'Magneton'
  | 'Farfetchd'
  | 'Doduo'
  | 'Dodrio'
  | 'Seel'
  | 'Dewgong'
  | 'Grimer'
  | 'Muk'
  | 'Shellder'
  | 'Cloyster'
  | 'Gastly'
  | 'Haunter'
  | 'Gengar'
  | 'Onix'
  | 'Drowzee'
  | 'Hypno'
  | 'Krabby'
  | 'Kingler'
  | 'Voltorb'
  | 'Electrode'
  | 'Exeggcute'
  | 'Exeggutor'
  | 'Cubone'
  | 'Marowak'
  | 'Hitmonlee'
  | 'Hitmonchan'
  | 'Lickitung'
  | 'Koffing'
  | 'Weezing'
  | 'Rhyhorn'
  | 'Rhydon'
  | 'Chansey'
  | 'Tangela'
  | 'Kangaskhan'
  | 'Horsea'
  | 'Seadra'
  | 'Goldeen'
  | 'Seaking'
  | 'Staryu'
  | 'Starmie'
  | 'MrMime'
  | 'Scyther'
  | 'Jynx'
  | 'Electabuzz'
  | 'Magmar'
  | 'Pinsir'
  | 'Tauros'
  | 'Magikarp'
  | 'Gyarados'
  | 'Lapras'
  | 'Ditto'
  | 'Eevee'
  | 'Vaporeon'
  | 'Jolteon'
  | 'Flareon'
  | 'Porygon'
  | 'Omanyte'
  | 'Omastar'
  | 'Kabuto'
  | 'Kabutops'
  | 'Aerodactyl'
  | 'Snorlax'
  | 'Articuno'
  | 'Zapdos'
  | 'Moltres'
  | 'Dratini'
  | 'Dragonair'
  | 'Dragonite'
  | 'Mewtwo'
  | 'Mew'
  | 'Chikorita'
  | 'Bayleef'
  | 'Meganium'
  | 'Cyndaquil'
  | 'Quilava'
  | 'Typhlosion'
  | 'Totodile'
  | 'Croconaw'
  | 'Feraligatr'
  | 'Sentret'
  | 'Furret'
  | 'Hoothoot'
  | 'Noctowl'
  | 'Ledyba'
  | 'Ledian'
  | 'Spinarak'
  | 'Ariados'
  | 'Crobat'
  | 'Chinchou'
  | 'Lanturn'
  | 'Pichu'
  | 'Cleffa'
  | 'Igglybuff'
  | 'Togepi'
  | 'Togetic'
  | 'Natu'
  | 'Xatu'
  | 'Mareep'
  | 'Flaaffy'
  | 'Ampharos'
  | 'Bellossom'
  | 'Marill'
  | 'Azumarill'
  | 'Sudowoodo'
  | 'Politoed'
  | 'Hoppip'
  | 'Skiploom'
  | 'Jumpluff'
  | 'Aipom'
  | 'Sunkern'
  | 'Sunflora'
  | 'Yanma'
  | 'Wooper'
  | 'Quagsire'
  | 'Espeon'
  | 'Umbreon'
  | 'Murkrow'
  | 'Slowking'
  | 'Misdreavus'
  | 'Unown'
  | 'Wobbuffet'
  | 'Girafarig'
  | 'Pineco'
  | 'Forretress'
  | 'Dunsparce'
  | 'Gligar'
  | 'Steelix'
  | 'Snubbull'
  | 'Granbull'
  | 'Qwilfish'
  | 'Scizor'
  | 'Shuckle'
  | 'Heracross'
  | 'Sneasel'
  | 'Teddiursa'
  | 'Ursaring'
  | 'Slugma'
  | 'Magcargo'
  | 'Swinub'
  | 'Piloswine'
  | 'Corsola'
  | 'Remoraid'
  | 'Octillery'
  | 'Delibird'
  | 'Mantine'
  | 'Skarmory'
  | 'Houndour'
  | 'Houndoom'
  | 'Kingdra'
  | 'Phanpy'
  | 'Donphan'
  | 'Porygon2'
  | 'Stantler'
  | 'Smeargle'
  | 'Tyrogue'
  | 'Hitmontop'
  | 'Smoochum'
  | 'Elekid'
  | 'Magby'
  | 'Miltank'
  | 'Blissey'
  | 'Raikou'
  | 'Entei'
  | 'Suicune'
  | 'Larvitar'
  | 'Pupitar'
  | 'Tyranitar'
  | 'Lugia'
  | 'HoOh'
  | 'Celebi'
  | 'Treecko'
  | 'Grovyle'
  | 'Sceptile'
  | 'Torchic'
  | 'Combusken'
  | 'Blaziken'
  | 'Mudkip'
  | 'Marshtomp'
  | 'Swampert'
  | 'Poochyena'
  | 'Mightyena'
  | 'Zigzagoon'
  | 'Linoone'
  | 'Wurmple'
  | 'Silcoon'
  | 'Beautifly'
  | 'Cascoon'
  | 'Dustox'
  | 'Lotad'
  | 'Lombre'
  | 'Ludicolo'
  | 'Seedot'
  | 'Nuzleaf'
  | 'Shiftry'
  | 'Taillow'
  | 'Swellow'
  | 'Wingull'
  | 'Pelipper'
  | 'Ralts'
  | 'Kirlia'
  | 'Gardevoir'
  | 'Surskit'
  | 'Masquerain'
  | 'Shroomish'
  | 'Breloom'
  | 'Slakoth'
  | 'Vigoroth'
  | 'Slaking'
  | 'Nincada'
  | 'Ninjask'
  | 'Shedinja'
  | 'Whismur'
  | 'Loudred'
  | 'Exploud'
  | 'Makuhita'
  | 'Hariyama'
  | 'Azurill'
  | 'Nosepass'
  | 'Skitty'
  | 'Delcatty'
  | 'Sableye'
  | 'Mawile'
  | 'Aron'
  | 'Lairon'
  | 'Aggron'
  | 'Meditite'
  | 'Medicham'
  | 'Electrike'
  | 'Manectric'
  | 'Plusle'
  | 'Minun'
  | 'Volbeat'
  | 'Illumise'
  | 'Roselia'
  | 'Gulpin'
  | 'Swalot'
  | 'Carvanha'
  | 'Sharpedo'
  | 'Wailmer'
  | 'Wailord'
  | 'Numel'
  | 'Camerupt'
  | 'Torkoal'
  | 'Spoink'
  | 'Grumpig'
  | 'Spinda'
  | 'Trapinch'
  | 'Vibrava'
  | 'Flygon'
  | 'Cacnea'
  | 'Cacturne'
  | 'Swablu'
  | 'Altaria'
  | 'Zangoose'
  | 'Seviper'
  | 'Lunatone'
  | 'Solrock'
  | 'Barboach'
  | 'Whiscash'
  | 'Corphish'
  | 'Crawdaunt'
  | 'Baltoy'
  | 'Claydol'
  | 'Lileep'
  | 'Cradily'
  | 'Anorith'
  | 'Armaldo'
  | 'Feebas'
  | 'Milotic'
  | 'Castform'
  | 'Kecleon'
  | 'Shuppet'
  | 'Banette'
  | 'Duskull'
  | 'Dusclops'
  | 'Tropius'
  | 'Chimecho'
  | 'Absol'
  | 'Wynaut'
  | 'Snorunt'
  | 'Glalie'
  | 'Spheal'
  | 'Sealeo'
  | 'Walrein'
  | 'Clamperl'
  | 'Huntail'
  | 'Gorebyss'
  | 'Relicanth'
  | 'Luvdisc'
  | 'Bagon'
  | 'Shelgon'
  | 'Salamence'
  | 'Beldum'
  | 'Metang'
  | 'Metagross'
  | 'Regirock'
  | 'Regice'
  | 'Registeel'
  | 'Latias'
  | 'Latios'
  | 'Kyogre'
  | 'Groudon'
  | 'Rayquaza'
  | 'Jirachi'
  | 'Deoxys'
  | 'Turtwig'
  | 'Grotle'
  | 'Torterra'
  | 'Chimchar'
  | 'Monferno'
  | 'Infernape'
  | 'Piplup'
  | 'Prinplup'
  | 'Empoleon'
  | 'Starly'
  | 'Staravia'
  | 'Staraptor'
  | 'Bidoof'
  | 'Bibarel'
  | 'Kricketot'
  | 'Kricketune'
  | 'Shinx'
  | 'Luxio'
  | 'Luxray'
  | 'Budew'
  | 'Roserade'
  | 'Cranidos'
  | 'Rampardos'
  | 'Shieldon'
  | 'Bastiodon'
  | 'Burmy'
  | 'Wormadam'
  | 'Mothim'
  | 'Combee'
  | 'Vespiquen'
  | 'Pachirisu'
  | 'Buizel'
  | 'Floatzel'
  | 'Cherubi'
  | 'Cherrim'
  | 'Shellos'
  | 'Gastrodon'
  | 'Ambipom'
  | 'Drifloon'
  | 'Drifblim'
  | 'Buneary'
  | 'Lopunny'
  | 'Mismagius'
  | 'Honchkrow'
  | 'Glameow'
  | 'Purugly'
  | 'Chingling'
  | 'Stunky'
  | 'Skuntank'
  | 'Bronzor'
  | 'Bronzong'
  | 'Bonsly'
  | 'MimeJr'
  | 'Happiny'
  | 'Chatot'
  | 'Spiritomb'
  | 'Gible'
  | 'Gabite'
  | 'Garchomp'
  | 'Munchlax'
  | 'Riolu'
  | 'Lucario'
  | 'Hippopotas'
  | 'Hippowdon'
  | 'Skorupi'
  | 'Drapion'
  | 'Croagunk'
  | 'Toxicroak'
  | 'Carnivine'
  | 'Finneon'
  | 'Lumineon'
  | 'Mantyke'
  | 'Snover'
  | 'Abomasnow'
  | 'Weavile'
  | 'Magnezone'
  | 'Lickilicky'
  | 'Rhyperior'
  | 'Tangrowth'
  | 'Electivire'
  | 'Magmortar'
  | 'Togekiss'
  | 'Yanmega'
  | 'Leafeon'
  | 'Glaceon'
  | 'Gliscor'
  | 'Mamoswine'
  | 'PorygonZ'
  | 'Gallade'
  | 'Probopass'
  | 'Dusknoir'
  | 'Froslass'
  | 'Rotom'
  | 'Uxie'
  | 'Mesprit'
  | 'Azelf'
  | 'Dialga'
  | 'Palkia'
  | 'Heatran'
  | 'Regigigas'
  | 'Giratina'
  | 'Cresselia'
  | 'Phione'
  | 'Manaphy'
  | 'Darkrai'
  | 'Shaymin'
  | 'Arceus'
  | 'Victini'
  | 'Snivy'
  | 'Servine'
  | 'Serperior'
  | 'Tepig'
  | 'Pignite'
  | 'Emboar'
  | 'Oshawott'
  | 'Dewott'
  | 'Samurott'
  | 'Patrat'
  | 'Watchog'
  | 'Lillipup'
  | 'Herdier'
  | 'Stoutland'
  | 'Purrloin'
  | 'Liepard'
  | 'Pansage'
  | 'Simisage'
  | 'Pansear'
  | 'Simisear'
  | 'Panpour'
  | 'Simipour'
  | 'Munna'
  | 'Musharna'
  | 'Pidove'
  | 'Tranquill'
  | 'Unfezant'
  | 'Blitzle'
  | 'Zebstrika'
  | 'Roggenrola'
  | 'Boldore'
  | 'Gigalith'
  | 'Woobat'
  | 'Swoobat'
  | 'Drilbur'
  | 'Excadrill'
  | 'Audino'
  | 'Timburr'
  | 'Gurdurr'
  | 'Conkeldurr'
  | 'Tympole'
  | 'Palpitoad'
  | 'Seismitoad'
  | 'Throh'
  | 'Sawk'
  | 'Sewaddle'
  | 'Swadloon'
  | 'Leavanny'
  | 'Venipede'
  | 'Whirlipede'
  | 'Scolipede'
  | 'Cottonee'
  | 'Whimsicott'
  | 'Petilil'
  | 'Lilligant'
  | 'Basculin'
  | 'Sandile'
  | 'Krokorok'
  | 'Krookodile'
  | 'Darumaka'
  | 'Darmanitan'
  | 'Maractus'
  | 'Dwebble'
  | 'Crustle'
  | 'Scraggy'
  | 'Scrafty'
  | 'Sigilyph'
  | 'Yamask'
  | 'Cofagrigus'
  | 'Tirtouga'
  | 'Carracosta'
  | 'Archen'
  | 'Archeops'
  | 'Trubbish'
  | 'Garbodor'
  | 'Zorua'
  | 'Zoroark'
  | 'Minccino'
  | 'Cinccino'
  | 'Gothita'
  | 'Gothorita'
  | 'Gothitelle'
  | 'Solosis'
  | 'Duosion'
  | 'Reuniclus'
  | 'Ducklett'
  | 'Swanna'
  | 'Vanillite'
  | 'Vanillish'
  | 'Vanilluxe'
  | 'Deerling'
  | 'Sawsbuck'
  | 'Emolga'
  | 'Karrablast'
  | 'Escavalier'
  | 'Foongus'
  | 'Amoonguss'
  | 'Frillish'
  | 'Jellicent'
  | 'Alomomola'
  | 'Joltik'
  | 'Galvantula'
  | 'Ferroseed'
  | 'Ferrothorn'
  | 'Klink'
  | 'Klang'
  | 'Klinklang'
  | 'Tynamo'
  | 'Eelektrik'
  | 'Eelektross'
  | 'Elgyem'
  | 'Beheeyem'
  | 'Litwick'
  | 'Lampent'
  | 'Chandelure'
  | 'Axew'
  | 'Fraxure'
  | 'Haxorus'
  | 'Cubchoo'
  | 'Beartic'
  | 'Cryogonal'
  | 'Shelmet'
  | 'Accelgor'
  | 'Stunfisk'
  | 'Mienfoo'
  | 'Mienshao'
  | 'Druddigon'
  | 'Golett'
  | 'Golurk'
  | 'Pawniard'
  | 'Bisharp'
  | 'Bouffalant'
  | 'Rufflet'
  | 'Braviary'
  | 'Vullaby'
  | 'Mandibuzz'
  | 'Heatmor'
  | 'Durant'
  | 'Deino'
  | 'Zweilous'
  | 'Hydreigon'
  | 'Larvesta'
  | 'Volcarona'
  | 'Cobalion'
  | 'Terrakion'
  | 'Virizion'
  | 'Tornadus'
  | 'Thundurus'
  | 'Reshiram'
  | 'Zekrom'
  | 'Landorus'
  | 'Kyurem'
  | 'Keldeo'
  | 'Meloetta'
  | 'Genesect'
  | 'Chespin'
  | 'Quilladin'
  | 'Chesnaught'
  | 'Fennekin'
  | 'Braixen'
  | 'Delphox'
  | 'Froakie'
  | 'Frogadier'
  | 'Greninja'
  | 'Bunnelby'
  | 'Diggersby'
  | 'Fletchling'
  | 'Fletchinder'
  | 'Talonflame'
  | 'Scatterbug'
  | 'Spewpa'
  | 'Vivillon'
  | 'Litleo'
  | 'Pyroar'
  | 'Flabebe'
  | 'Floette'
  | 'Florges'
  | 'Skiddo'
  | 'Gogoat'
  | 'Pancham'
  | 'Pangoro'
  | 'Furfrou'
  | 'Espurr'
  | 'Meowstic'
  | 'Honedge'
  | 'Doublade'
  | 'Aegislash'
  | 'Spritzee'
  | 'Aromatisse'
  | 'Swirlix'
  | 'Slurpuff'
  | 'Inkay'
  | 'Malamar'
  | 'Binacle'
  | 'Barbaracle'
  | 'Skrelp'
  | 'Dragalge'
  | 'Clauncher'
  | 'Clawitzer'
  | 'Helioptile'
  | 'Heliolisk'
  | 'Tyrunt'
  | 'Tyrantrum'
  | 'Amaura'
  | 'Aurorus'
  | 'Sylveon'
  | 'Hawlucha'
  | 'Dedenne'
  | 'Carbink'
  | 'Goomy'
  | 'Sliggoo'
  | 'Goodra'
  | 'Klefki'
  | 'Phantump'
  | 'Trevenant'
  | 'Pumpkaboo'
  | 'Gourgeist'
  | 'Bergmite'
  | 'Avalugg'
  | 'Noibat'
  | 'Noivern'
  | 'Xerneas'
  | 'Yveltal'
  | 'Zygarde'
  | 'Diancie'
  | 'Hoopa'
  | 'Volcanion'
  | 'Rowlet'
  | 'Dartrix'
  | 'Decidueye'
  | 'Litten'
  | 'Torracat'
  | 'Incineroar'
  | 'Popplio'
  | 'Brionne'
  | 'Primarina'
  | 'Pikipek'
  | 'Trumbeak'
  | 'Toucannon'
  | 'Yungoos'
  | 'Gumshoos'
  | 'Grubbin'
  | 'Charjabug'
  | 'Vikavolt'
  | 'Crabrawler'
  | 'Crabominable'
  | 'Oricorio'
  | 'Cutiefly'
  | 'Ribombee'
  | 'Rockruff'
  | 'Lycanroc'
  | 'Wishiwashi'
  | 'Mareanie'
  | 'Toxapex'
  | 'Mudbray'
  | 'Mudsdale'
  | 'Dewpider'
  | 'Araquanid'
  | 'Fomantis'
  | 'Lurantis'
  | 'Morelull'
  | 'Shiinotic'
  | 'Salandit'
  | 'Salazzle'
  | 'Stufful'
  | 'Bewear'
  | 'Bounsweet'
  | 'Steenee'
  | 'Tsareena'
  | 'Comfey'
  | 'Oranguru'
  | 'Passimian'
  | 'Wimpod'
  | 'Golisopod'
  | 'Sandygast'
  | 'Palossand'
  | 'Pyukumuku'
  | 'TypeNull'
  | 'Silvally'
  | 'Minior'
  | 'Komala'
  | 'Turtonator'
  | 'Togedemaru'
  | 'Mimikyu'
  | 'Bruxish'
  | 'Drampa'
  | 'Dhelmise'
  | 'Jangmoo'
  | 'Hakamoo'
  | 'Kommoo'
  | 'TapuKoko'
  | 'TapuLele'
  | 'TapuBulu'
  | 'TapuFini'
  | 'Cosmog'
  | 'Cosmoem'
  | 'Solgaleo'
  | 'Lunala'
  | 'Nihilego'
  | 'Buzzwole'
  | 'Pheromosa'
  | 'Xurkitree'
  | 'Celesteela'
  | 'Kartana'
  | 'Guzzlord'
  | 'Necrozma'
  | 'Magearna'
  | 'Marshadow'
  | 'Poipole'
  | 'Naganadel'
  | 'Stakataka'
  | 'Blacephalon'
  | 'Zeraora'
  | 'Meltan'
  | 'Melmetal'
  | 'Grookey'
  | 'Thwackey'
  | 'Rillaboom'
  | 'Scorbunny'
  | 'Raboot'
  | 'Cinderace'
  | 'Sobble'
  | 'Drizzile'
  | 'Inteleon'
  | 'Skwovet'
  | 'Greedent'
  | 'Rookidee'
  | 'Corvisquire'
  | 'Corviknight'
  | 'Blipbug'
  | 'Dottler'
  | 'Orbeetle'
  | 'Nickit'
  | 'Thievul'
  | 'Gossifleur'
  | 'Eldegoss'
  | 'Wooloo'
  | 'Dubwool'
  | 'Chewtle'
  | 'Drednaw'
  | 'Yamper'
  | 'Boltund'
  | 'Rolycoly'
  | 'Carkol'
  | 'Coalossal'
  | 'Applin'
  | 'Flapple'
  | 'Appletun'
  | 'Silicobra'
  | 'Sandaconda'
  | 'Cramorant'
  | 'Arrokuda'
  | 'Barraskewda'
  | 'Toxel'
  | 'Toxtricity'
  | 'Sizzlipede'
  | 'Centiskorch'
  | 'Clobbopus'
  | 'Grapploct'
  | 'Sinistea'
  | 'Polteageist'
  | 'Hatenna'
  | 'Hattrem'
  | 'Hatterene'
  | 'Impidimp'
  | 'Morgrem'
  | 'Grimmsnarl'
  | 'Obstagoon'
  | 'Perrserker'
  | 'Cursola'
  | 'Sirfetchd'
  | 'MrRime'
  | 'Runerigus'
  | 'Milcery'
  | 'Alcremie'
  | 'Falinks'
  | 'Pincurchin'
  | 'Snom'
  | 'Frosmoth'
  | 'Stonjourner'
  | 'Eiscue'
  | 'Indeedee'
  | 'Morpeko'
  | 'Cufant'
  | 'Copperajah'
  | 'Dracozolt'
  | 'Arctozolt'
  | 'Dracovish'
  | 'Arctovish'
  | 'Duraludon'
  | 'Dreepy'
  | 'Drakloak'
  | 'Dragapult'
  | 'Zacian'
  | 'Zamazenta'
  | 'Eternatus'
  | 'Kubfu'
  | 'Urshifu'
  | 'Zarude'
  | 'Regieleki'
  | 'Regidrago'
  | 'Glastrier'
  | 'Spectrier'
  | 'Calyrex'
  | 'Wyrdeer'
  | 'Kleavor'
  | 'Ursaluna'
  | 'Basculegion'
  | 'Sneasler'
  | 'Overqwil'
  | 'Enamorus'
  | 'Sprigatito'
  | 'Floragato'
  | 'Meowscarada'
  | 'Fuecoco'
  | 'Crocalor'
  | 'Skeledirge'
  | 'Quaxly'
  | 'Quaxwell'
  | 'Quaquaval'
  | 'Lechonk'
  | 'Oinkologne'
  | 'Tarountula'
  | 'Spidops'
  | 'Nymble'
  | 'Lokix'
  | 'Pawmi'
  | 'Pawmo'
  | 'Pawmot'
  | 'Tandemaus'
  | 'Maushold'
  | 'Fidough'
  | 'Dachsbun'
  | 'Smoliv'
  | 'Dolliv'
  | 'Arboliva'
  | 'Squawkabilly'
  | 'Nacli'
  | 'Naclstack'
  | 'Garganacl'
  | 'Charcadet'
  | 'Armarouge'
  | 'Ceruledge'
  | 'Tadbulb'
  | 'Bellibolt'
  | 'Wattrel'
  | 'Kilowattrel'
  | 'Maschiff'
  | 'Mabosstiff'
  | 'Shroodle'
  | 'Grafaiai'
  | 'Bramblin'
  | 'Brambleghast'
  | 'Toedscool'
  | 'Toedscruel'
  | 'Klawf'
  | 'Capsakid'
  | 'Scovillain'
  | 'Rellor'
  | 'Rabsca'
  | 'Flittle'
  | 'Espathra'
  | 'Tinkatink'
  | 'Tinkatuff'
  | 'Tinkaton'
  | 'Wiglett'
  | 'Wugtrio'
  | 'Bombirdier'
  | 'Finizen'
  | 'Palafin'
  | 'Varoom'
  | 'Revavroom'
  | 'Cyclizar'
  | 'Orthworm'
  | 'Glimmet'
  | 'Glimmora'
  | 'Greavard'
  | 'Houndstone'
  | 'Flamigo'
  | 'Cetoddle'
  | 'Cetitan'
  | 'Veluza'
  | 'Dondozo'
  | 'Tatsugiri'
  | 'Annihilape'
  | 'Clodsire'
  | 'Farigiraf'
  | 'Dudunsparce'
  | 'Kingambit'
  | 'GreatTusk'
  | 'ScreamTail'
  | 'BruteBonnet'
  | 'FlutterMane'
  | 'SlitherWing'
  | 'SandyShocks'
  | 'IronTreads'
  | 'IronBundle'
  | 'IronHands'
  | 'IronJugulis'
  | 'IronMoth'
  | 'IronThorns'
  | 'Frigibax'
  | 'Arctibax'
  | 'Baxcalibur'
  | 'Gimmighoul'
  | 'Gholdengo'
  | 'WoChien'
  | 'ChienPao'
  | 'TingLu'
  | 'ChiYu'
  | 'RoaringMoon'
  | 'IronValiant'
  | 'Koraidon'
  | 'Miraidon'
  | 'WalkingWake'
  | 'IronLeaves'
  | 'Dipplin'
  | 'Poltchageist'
  | 'Sinistcha'
  | 'Okidogi'
  | 'Munkidori'
  | 'Fezandipiti'
  | 'Ogerpon'
  | 'Archaludon'
  | 'Hydrapple'
  | 'GougingFire'
  | 'RagingBolt'
  | 'IronBoulder'
  | 'IronCrown'
  | 'Terapagos'
  | 'Pecharunt'
export type NatureIndex = number
export type NatureStrategy = 'KeepOriginalNature' | 'KeepMintNature'
export type NicknameCapitalization = 'GameDefault' | 'Modern'
export type OriginGame =
  | 'Invalid0'
  | 'Sapphire'
  | 'Ruby'
  | 'Emerald'
  | 'FireRed'
  | 'LeafGreen'
  | 'Invalid6'
  | 'HeartGold'
  | 'SoulSilver'
  | 'Invalid9'
  | 'Diamond'
  | 'Pearl'
  | 'Platinum'
  | 'Invalid13'
  | 'Invalid14'
  | 'ColosseumXd'
  | 'BattleRevolution'
  | 'Invalid17'
  | 'Invalid18'
  | 'Invalid19'
  | 'White'
  | 'Black'
  | 'White2'
  | 'Black2'
  | 'X'
  | 'Y'
  | 'AlphaSapphire'
  | 'OmegaRuby'
  | 'Invalid28'
  | 'Invalid29'
  | 'Sun'
  | 'Moon'
  | 'UltraSun'
  | 'UltraMoon'
  | 'Go'
  | 'Red'
  | 'BlueGreen'
  | 'BlueJpn'
  | 'Yellow'
  | 'Gold'
  | 'Silver'
  | 'Crystal'
  | 'LetsGoPikachu'
  | 'LetsGoEevee'
  | 'Sword'
  | 'Shield'
  | 'Home'
  | 'LegendsArceus'
  | 'BrilliantDiamond'
  | 'ShiningPearl'
  | 'Scarlet'
  | 'Violet'
  | 'LegendsZa'
export type PaginatedPage<T> = {
  results: T[]
  nextPageExists: boolean
  currentCursor: PaginationCursor
  nextCursor: PaginationCursor
  totalCount: number
}
export type PaginationCursor = { pageSize: number; pageIndex: number }
export type PathData = { raw: string; name: string; dir: string; ext: string; separator: string }
export type PkmType =
  | 'Normal'
  | 'Fighting'
  | 'Flying'
  | 'Poison'
  | 'Ground'
  | 'Rock'
  | 'Bug'
  | 'Ghost'
  | 'Steel'
  | 'Fire'
  | 'Water'
  | 'Grass'
  | 'Electric'
  | 'Psychic'
  | 'Ice'
  | 'Dragon'
  | 'Dark'
  | 'Fairy'
export type PluginIdentifier = 'radical_red' | 'unbound' | 'luminescent_platinum' | 'compass'
export type PluginMetadataWithIcon = {
  id: string
  name: string
  version: string
  api_version: number
  icon_image: ImageResponse | null
}
export type Pokedex = { byDexNumber: Partial<{ [key in number]: PokedexEntry }> }
export type PokedexEntry = { formes: Partial<{ [key in number]: PokedexStatus }> }
export type PokedexStatus = 'Seen' | 'Caught' | 'ShinyCaught'
export type PokedexUpdate = { nationalDex: number; formIndex: number; status: PokedexStatus }
export type PossibleSaves = { citra: PathData[]; desmume: PathData[]; open_emu: PathData[] }
export type SaveRef = {
  filePath: PathData
  game: number
  trainerName: string
  trainerID: string
  lastOpened: number | null
  lastModified: number | null
  valid: boolean
  pluginIdentifier: PluginIdentifier | null
}
export type StoredBankDataWasm = { banks: BankWasm[]; current_bank?: number }
export type TransactionState = { open_transaction: boolean; temp_files: string[] }
export type UpdateFeatures = { version: string; feature_messages: string[] }

/** tauri-specta globals **/

import { invoke as TAURI_INVOKE } from '@tauri-apps/api/core'
import * as TAURI_API_EVENT from '@tauri-apps/api/event'
import { type WebviewWindow as __WebviewWindow__ } from '@tauri-apps/api/webviewWindow'

type __EventObj__<T> = {
  listen: (cb: TAURI_API_EVENT.EventCallback<T>) => ReturnType<typeof TAURI_API_EVENT.listen<T>>
  once: (cb: TAURI_API_EVENT.EventCallback<T>) => ReturnType<typeof TAURI_API_EVENT.once<T>>
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>
}

export type Result<T, E> = { status: 'ok'; data: T } | { status: 'error'; error: E }

function __makeEvents__<T extends Record<string, any>>(mappings: Record<keyof T, string>) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>
      }
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T]

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case 'listen':
                return (arg: any) => TAURI_API_EVENT.listen(name, arg)
              case 'once':
                return (arg: any) => TAURI_API_EVENT.once(name, arg)
              case 'emit':
                return (arg: any) => TAURI_API_EVENT.emit(name, arg)
            }
          },
        })
      },
    }
  )
}
