export type RadicalRedItem = { id: number; name: string }

export const RADICAL_RED_ITEMS: RadicalRedItem[] = [
  { id: 1, name: "Master Ball" },
  { id: 2, name: "Ultra Ball" },
  { id: 3, name: "Great Ball" },
  { id: 4, name: "Poke Ball" },
  { id: 5, name: "Safari Ball" },
  { id: 6, name: "Net Ball" },
  { id: 7, name: "Dive Ball" },
  { id: 8, name: "Nest Ball" },
  { id: 9, name: "Repeat Ball" },
  { id: 10, name: "Timer Ball" },
  { id: 11, name: "Luxury Ball" },
  { id: 12, name: "Premier Ball" },
  { id: 13, name: "Potion" },
  { id: 14, name: "Antidote" },
  { id: 15, name: "Burn Heal" },
  { id: 16, name: "Ice Heal" },
  { id: 17, name: "Awakening" },
  { id: 18, name: "Paralyz Heal" },
  { id: 19, name: "Full Restore" },
  { id: 20, name: "Max Potion" },
  { id: 21, name: "Hyper Potion" },
  { id: 22, name: "Super Potion" },
  { id: 23, name: "Full Heal" },
  { id: 24, name: "Revive" },
  { id: 25, name: "Max Revive" },
  { id: 26, name: "Fresh Water" },
  { id: 27, name: "Soda Pop" },
  { id: 28, name: "Lemonade" },
  { id: 29, name: "Moomoo Milk" },
  { id: 30, name: "EnergyPowder" },
  { id: 31, name: "Energy Root" },
  { id: 32, name: "Heal Powder" },
  { id: 33, name: "Revival Herb" },
  { id: 34, name: "Ether" },
  { id: 35, name: "Max Ether" },
  { id: 36, name: "Elixir" },
  { id: 37, name: "Max Elixir" },
  { id: 38, name: "Lava Cookie" },
  { id: 39, name: "Blue Flute" },
  { id: 40, name: "Yellow Flute" },
  { id: 41, name: "Red Flute" },
  { id: 42, name: "Black Flute" },
  { id: 43, name: "White Flute" },
  { id: 44, name: "Berry Juice" },
  { id: 45, name: "Sacred Ash" },
  { id: 46, name: "Shoal Salt" },
  { id: 47, name: "Shoal Shell" },
  { id: 48, name: "Red Shard" },
  { id: 49, name: "Blue Shard" },
  { id: 50, name: "Yellow Shard" },
  { id: 51, name: "Green Shard" },
  { id: 52, name: "RageCandyBar" },
  { id: 53, name: "Old Gateau" },
  { id: 54, name: "Casteliacone" },
  { id: 55, name: "Dream Patch" },
  { id: 56, name: "Shalour Sable" },
  { id: 57, name: "Health Wing" },
  { id: 58, name: "Muscle Wing" },
  { id: 59, name: "Resist Wing" },
  { id: 60, name: "Genius Wing" },
  { id: 61, name: "Clever Wing" },
  { id: 62, name: "Swift Wing" },
  { id: 63, name: "HP Up" },
  { id: 64, name: "Protein" },
  { id: 65, name: "Iron" },
  { id: 66, name: "Carbos" },
  { id: 67, name: "Calcium" },
  { id: 68, name: "Rare Candy" },
  { id: 69, name: "PP Up" },
  { id: 70, name: "Zinc" },
  { id: 71, name: "PP Max" },
  { id: 72, name: "Ability Pill" },
  { id: 73, name: "Guard Spec." },
  { id: 74, name: "Dire Hit" },
  { id: 75, name: "X Attack" },
  { id: 76, name: "X Defend" },
  { id: 77, name: "X Speed" },
  { id: 78, name: "X Accuracy" },
  { id: 79, name: "X Sp. Atk" },
  { id: 80, name: "Poke Doll" },
  { id: 81, name: "Fluffy Tail" },
  { id: 82, name: "Big Malasada" },
  { id: 83, name: "Super Repel" },
  { id: 84, name: "Max Repel" },
  { id: 85, name: "Escape Rope" },
  { id: 86, name: "Repel" },
  { id: 87, name: "Link Cable" },
  { id: 88, name: "Protector" },
  { id: 89, name: "Electirizer" },
  { id: 90, name: "Magmarizer" },
  { id: 91, name: "Dubious Disc" },
  { id: 92, name: "Reaper Cloth" },
  { id: 93, name: "Sun Stone" },
  { id: 94, name: "Moon Stone" },
  { id: 95, name: "Fire Stone" },
  { id: 96, name: "ThunderStone" },
  { id: 97, name: "Water Stone" },
  { id: 98, name: "Leaf Stone" },
  { id: 99, name: "Shiny Stone" },
  { id: 100, name: "Dusk Stone" },
  { id: 101, name: "Dawn Stone" },
  { id: 102, name: "Ice Stone t" },
  { id: 103, name: "TinyMushroom" },
  { id: 104, name: "Big Mushroom" },
  { id: 105, name: "BalmMushroom" },
  { id: 106, name: "Pearl" },
  { id: 107, name: "Big Pearl" },
  { id: 108, name: "Stardust" },
  { id: 109, name: "Star Piece" },
  { id: 110, name: "Nugget" },
  { id: 111, name: "Heart Scale" },
  { id: 112, name: "Rare Bone" },
  { id: 113, name: "Pearl String" },
  { id: 114, name: "Comet Shard" },
  { id: 115, name: "Big Nugget" },
  { id: 116, name: "Honey weet" },
  { id: 117, name: "Pretty Wing" },
  { id: 118, name: "Oval Stone" },
  { id: 119, name: "Razor Claw" },
  { id: 120, name: "Razor Fang" },
  { id: 121, name: "Orange Mail" },
  { id: 122, name: "Harbor Mail" },
  { id: 123, name: "Glitter Mail" },
  { id: 124, name: "Mech Mail" },
  { id: 125, name: "Wood Mail" },
  { id: 126, name: "Wave Mail" },
  { id: 127, name: "Bead Mail" },
  { id: 128, name: "Shadow Mail" },
  { id: 129, name: "Tropic Mail" },
  { id: 130, name: "Dream Mail" },
  { id: 131, name: "Fab Mail" },
  { id: 132, name: "Retro Mail" },
  { id: 133, name: "Cheri Berry" },
  { id: 134, name: "Chesto Berry" },
  { id: 135, name: "Pecha Berry" },
  { id: 136, name: "Rawst Berry" },
  { id: 137, name: "Aspear Berry" },
  { id: 138, name: "Leppa Berry" },
  { id: 139, name: "Oran Berry" },
  { id: 140, name: "Persim Berry" },
  { id: 141, name: "Lum Berry" },
  { id: 142, name: "Sitrus Berry" },
  { id: 143, name: "Figy Berry" },
  { id: 144, name: "Wiki Berry" },
  { id: 145, name: "Mago Berry" },
  { id: 146, name: "Aguav Berry" },
  { id: 147, name: "Iapapa Berry" },
  { id: 148, name: "Razz Berry" },
  { id: 149, name: "Bluk Berry" },
  { id: 150, name: "Nanab Berry" },
  { id: 151, name: "Wepear Berry" },
  { id: 152, name: "Pinap Berry" },
  { id: 153, name: "Pomeg Berry" },
  { id: 154, name: "Kelpsy Berry" },
  { id: 155, name: "Qualot Berry" },
  { id: 156, name: "Hondew Berry" },
  { id: 157, name: "Grepa Berry" },
  { id: 158, name: "Tamato Berry" },
  { id: 159, name: "Cornn Berry" },
  { id: 160, name: "Magost Berry" },
  { id: 161, name: "Rabuta Berry" },
  { id: 162, name: "Nomel Berry" },
  { id: 163, name: "Spelon Berry" },
  { id: 164, name: "Pamtre Berry" },
  { id: 165, name: "Watmel Berry" },
  { id: 166, name: "Durin Berry" },
  { id: 167, name: "Belue Berry" },
  { id: 168, name: "Liechi Berry" },
  { id: 169, name: "Ganlon Berry" },
  { id: 170, name: "Salac Berry" },
  { id: 171, name: "Petaya Berry" },
  { id: 172, name: "Apicot Berry" },
  { id: 173, name: "Lansat Berry" },
  { id: 174, name: "Starf Berry" },
  { id: 175, name: "Enigma Berry" },
  { id: 176, name: "Prism Scale" },
  { id: 177, name: "Sachet" },
  { id: 178, name: "Whip Dream" },
  { id: 179, name: "BrightPowder" },
  { id: 180, name: "White Herb" },
  { id: 181, name: "Macho Brace" },
  { id: 182, name: "Exp. Share" },
  { id: 183, name: "Quick Claw" },
  { id: 184, name: "Soothe Bell" },
  { id: 185, name: "Mental Herb" },
  { id: 186, name: "Choice Band" },
  { id: 187, name: "King's Rock" },
  { id: 188, name: "Silver Powder" },
  { id: 189, name: "Amulet Coin" },
  { id: 190, name: "Cleanse Tag" },
  { id: 191, name: "Soul Dew" },
  { id: 192, name: "Deep Sea Tooth" },
  { id: 193, name: "Deep Sea Scale" },
  { id: 194, name: "Smoke Ball" },
  { id: 195, name: "Everstone" },
  { id: 196, name: "Focus Band" },
  { id: 197, name: "Lucky Egg" },
  { id: 198, name: "Scope Lens" },
  { id: 199, name: "Metal Coat" },
  { id: 200, name: "Leftovers" },
  { id: 201, name: "Dragon Scale" },
  { id: 202, name: "Light Ball" },
  { id: 203, name: "Soft Sand" },
  { id: 204, name: "Hard Stone" },
  { id: 205, name: "Miracle Seed" },
  { id: 206, name: "Black Glasses" },
  { id: 207, name: "Black Belt" },
  { id: 208, name: "Magnet" },
  { id: 209, name: "Mystic Water" },
  { id: 210, name: "Sharp Beak" },
  { id: 211, name: "Poison Barb" },
  { id: 212, name: "Never-Melt Ice" },
  { id: 213, name: "Spell Tag" },
  { id: 214, name: "Twisted Spoon" },
  { id: 215, name: "Charcoal" },
  { id: 216, name: "Dragon Fang" },
  { id: 217, name: "Silk Scarf" },
  { id: 218, name: "Upgrade carf" },
  { id: 219, name: "Shell Bell" },
  { id: 220, name: "Sea Incense" },
  { id: 221, name: "Lax Incense" },
  { id: 222, name: "Lucky Punch" },
  { id: 223, name: "Metal Powder" },
  { id: 224, name: "Thick Club" },
  { id: 225, name: "Leek Stick" },
  { id: 226, name: "Straw. Sweet" },
  { id: 227, name: "Berry Sweet" },
  { id: 228, name: "Love Sweet" },
  { id: 229, name: "Clover Sweet" },
  { id: 230, name: "Flower Sweet" },
  { id: 231, name: "Ribbon Sweet" },
  { id: 232, name: "Star Sweet" },
  { id: 233, name: "Sweet Apple" },
  { id: 234, name: "Tart Apple" },
  { id: 235, name: "Cracked Pot" },
  { id: 236, name: "Chipped Pot" },
  { id: 237, name: "Galar Cuff" },
  { id: 238, name: "Galar Crown" },
  { id: 239, name: "Cherish Ball" },
  { id: 240, name: "Dusk Ball" },
  { id: 241, name: "Heal Ball" },
  { id: 242, name: "Quick Ball" },
  { id: 243, name: "Fast Ball" },
  { id: 244, name: "Level Ball" },
  { id: 245, name: "Lure Ball" },
  { id: 246, name: "Heavy Ball" },
  { id: 247, name: "Love Ball" },
  { id: 248, name: "Friend Ball" },
  { id: 249, name: "Moon Ball" },
  { id: 250, name: "Sport Ball" },
  { id: 251, name: "Beast Ball" },
  { id: 252, name: "Dream Ball" },
  { id: 253, name: "Park Ball" },
  { id: 254, name: "Red Scarf" },
  { id: 255, name: "Blue Scarf" },
  { id: 256, name: "Pink Scarf" },
  { id: 257, name: "Green Scarf" },
  { id: 258, name: "Yellow Scarf" },
  { id: 259, name: "Mach Bike" },
  { id: 260, name: "Coin Case" },
  { id: 261, name: "Itemfinder" },
  { id: 262, name: "Old Rod" },
  { id: 263, name: "Good Rod" },
  { id: 264, name: "Super Rod" },
  { id: 265, name: "S.S. Ticket" },
  { id: 266, name: "Contest Pass" },
  { id: 267, name: "Z-Power Ring" },
  { id: 268, name: "Wailmer Pail" },
  { id: 269, name: "Devon Goods" },
  { id: 270, name: "Soot Sack" },
  { id: 271, name: "Basement Key" },
  { id: 272, name: "Acro Bike" },
  { id: 273, name: "Pokeblock CASE" },
  { id: 274, name: "Letter" },
  { id: 275, name: "Eon Ticket" },
  { id: 276, name: "Red Orb" },
  { id: 277, name: "Blue Orb" },
  { id: 278, name: "Scanner" },
  { id: 279, name: "Go-Goggles" },
  { id: 280, name: "Meteorite" },
  { id: 281, name: "RM. 1 Key" },
  { id: 282, name: "RM. 2 Key" },
  { id: 283, name: "RM. 4 Key" },
  { id: 284, name: "RM. 6 Key" },
  { id: 285, name: "Storage Key" },
  { id: 286, name: "Root Fossil" },
  { id: 287, name: "Claw Fossil" },
  { id: 288, name: "Devon Scope" },
  { id: 289, name: "TM01" },
  { id: 290, name: "TM02" },
  { id: 291, name: "TM03" },
  { id: 292, name: "TM04" },
  { id: 293, name: "TM05" },
  { id: 294, name: "TM06" },
  { id: 295, name: "TM07" },
  { id: 296, name: "TM08" },
  { id: 297, name: "TM09" },
  { id: 298, name: "TM10" },
  { id: 299, name: "TM11" },
  { id: 300, name: "TM12" },
  { id: 301, name: "TM13" },
  { id: 302, name: "TM14" },
  { id: 303, name: "TM15" },
  { id: 304, name: "TM16" },
  { id: 305, name: "TM17" },
  { id: 306, name: "TM18" },
  { id: 307, name: "TM19" },
  { id: 308, name: "TM20" },
  { id: 309, name: "TM21" },
  { id: 310, name: "TM22" },
  { id: 311, name: "TM23" },
  { id: 312, name: "TM24" },
  { id: 313, name: "TM25" },
  { id: 314, name: "TM26" },
  { id: 315, name: "TM27" },
  { id: 316, name: "TM28" },
  { id: 317, name: "TM29" },
  { id: 318, name: "TM30" },
  { id: 319, name: "TM31" },
  { id: 320, name: "TM32" },
  { id: 321, name: "TM33" },
  { id: 322, name: "TM34" },
  { id: 323, name: "TM35" },
  { id: 324, name: "TM36" },
  { id: 325, name: "TM37" },
  { id: 326, name: "TM38" },
  { id: 327, name: "TM39" },
  { id: 328, name: "TM40" },
  { id: 329, name: "TM41" },
  { id: 330, name: "TM42" },
  { id: 331, name: "TM43" },
  { id: 332, name: "TM44" },
  { id: 333, name: "TM45" },
  { id: 334, name: "TM46" },
  { id: 335, name: "TM47" },
  { id: 336, name: "TM48" },
  { id: 337, name: "TM49" },
  { id: 338, name: "TM50" },
  { id: 339, name: "HM01" },
  { id: 340, name: "HM02" },
  { id: 341, name: "HM03" },
  { id: 342, name: "HM04" },
  { id: 343, name: "HM05" },
  { id: 344, name: "HM06" },
  { id: 345, name: "HM07" },
  { id: 346, name: "HM08" },
  { id: 347, name: "Dynamax Band" },
  { id: 348, name: "Gold Teeth" },
  { id: 349, name: "Oak's Parcel" },
  { id: 350, name: "Poke Flute" },
  { id: 351, name: "Secret Key" },
  { id: 352, name: "Bike Voucher" },
  { id: 353, name: "Mega Ring" },
  { id: 354, name: "Old Amber" },
  { id: 355, name: "Card Key" },
  { id: 356, name: "Lift Key" },
  { id: 357, name: "Helix Fossil" },
  { id: 358, name: "Dome Fossil" },
  { id: 359, name: "Silph Scope" },
  { id: 360, name: "Bicycle" },
  { id: 361, name: "Town Map" },
  { id: 362, name: "Stat Scanner" },
  { id: 363, name: "Poke Rider" },
  { id: 364, name: "TM Case" },
  { id: 365, name: "Berry Pouch" },
  { id: 366, name: "Teachy TV" },
  { id: 367, name: "Tri-Pass" },
  { id: 368, name: "Rainbow Pass" },
  { id: 369, name: "Tea" },
  { id: 370, name: "Mystic Ticke" },
  { id: 371, name: "Aurora Ticke" },
  { id: 372, name: "Locater Dev" },
  { id: 373, name: "Ruby" },
  { id: 374, name: "Sapphire" },
  { id: 375, name: "-DONT USE-" },
  { id: 376, name: "TM51" },
  { id: 377, name: "TM52" },
  { id: 378, name: "TM53" },
  { id: 379, name: "TM54" },
  { id: 380, name: "TM55" },
  { id: 381, name: "TM56" },
  { id: 382, name: "TM57" },
  { id: 383, name: "TM58" },
  { id: 384, name: "TM59" },
  { id: 385, name: "TM60" },
  { id: 386, name: "TM61" },
  { id: 387, name: "TM62" },
  { id: 388, name: "TM63" },
  { id: 389, name: "TM64" },
  { id: 390, name: "TM65" },
  { id: 391, name: "TM66" },
  { id: 392, name: "TM67" },
  { id: 393, name: "TM68" },
  { id: 394, name: "TM69" },
  { id: 395, name: "TM70" },
  { id: 396, name: "TM71" },
  { id: 397, name: "TM72" },
  { id: 398, name: "TM73" },
  { id: 399, name: "TM74" },
  { id: 400, name: "TM75" },
  { id: 401, name: "TM76" },
  { id: 402, name: "TM77" },
  { id: 403, name: "TM78" },
  { id: 404, name: "TM79" },
  { id: 405, name: "TM80" },
  { id: 406, name: "TM81" },
  { id: 407, name: "TM82" },
  { id: 408, name: "TM83" },
  { id: 409, name: "TM84" },
  { id: 410, name: "TM85" },
  { id: 411, name: "TM86" },
  { id: 412, name: "TM87" },
  { id: 413, name: "TM88" },
  { id: 414, name: "TM89" },
  { id: 415, name: "TM90" },
  { id: 416, name: "TM91" },
  { id: 417, name: "TM92" },
  { id: 418, name: "TM93" },
  { id: 419, name: "TM94" },
  { id: 420, name: "TM95" },
  { id: 421, name: "TM96" },
  { id: 422, name: "TM97" },
  { id: 423, name: "TM98" },
  { id: 424, name: "TM99" },
  { id: 425, name: "TM100" },
  { id: 426, name: "TM101" },
  { id: 427, name: "TM102" },
  { id: 428, name: "TM103" },
  { id: 429, name: "TM104" },
  { id: 430, name: "TM105" },
  { id: 431, name: "TM106" },
  { id: 432, name: "TM107" },
  { id: 433, name: "TM108" },
  { id: 434, name: "TM109" },
  { id: 435, name: "TM110" },
  { id: 436, name: "TM111" },
  { id: 437, name: "TM112" },
  { id: 438, name: "TM113" },
  { id: 439, name: "TM114" },
  { id: 440, name: "TM115" },
  { id: 441, name: "TM116" },
  { id: 442, name: "TM117" },
  { id: 443, name: "TM118" },
  { id: 444, name: "TM119" },
  { id: 445, name: "TM120" },
  { id: 446, name: "Occa Berry" },
  { id: 447, name: "Passho Berry" },
  { id: 448, name: "Wacan Berry" },
  { id: 449, name: "Rindo Berry" },
  { id: 450, name: "Yache Berry" },
  { id: 451, name: "Chople Berry" },
  { id: 452, name: "Kebia Berry" },
  { id: 453, name: "Shuca Berry" },
  { id: 454, name: "Coba Berry" },
  { id: 455, name: "Payapa Berry" },
  { id: 456, name: "Tanga Berry" },
  { id: 457, name: "Charti Berry" },
  { id: 458, name: "Kasib Berry" },
  { id: 459, name: "Haban Berry" },
  { id: 460, name: "Colbur Berry" },
  { id: 461, name: "Babiri Berry" },
  { id: 462, name: "Chilan Berry" },
  { id: 463, name: "Micle Berry" },
  { id: 464, name: "Custap Berry" },
  { id: 465, name: "Jacoba Berry" },
  { id: 466, name: "Rowap Berry" },
  { id: 467, name: "Roseli Berry" },
  { id: 468, name: "Kee Berry" },
  { id: 469, name: "Marang Berry" },
  { id: 470, name: "Oval Charm" },
  { id: 471, name: "Shiny Charm" },
  { id: 472, name: "Rainbow Wing" },
  { id: 473, name: "Silver Wing" },
  { id: 474, name: "Magma Stone" },
  { id: 475, name: "Light Stone" },
  { id: 476, name: "Dark Stone" },
  { id: 477, name: "Sun Flute" },
  { id: 478, name: "Moon Flute" },
  { id: 479, name: "Gracidea" },
  { id: 480, name: "DNA Splicers" },
  { id: 481, name: "Reveal Glass" },
  { id: 482, name: "PrisonBottle" },
  { id: 483, name: "N-Solarizer" },
  { id: 484, name: "Necrozmizer" },
  { id: 485, name: "Rusty Sword" },
  { id: 486, name: "Rusty Shield" },
  { id: 487, name: "Adamant Orb" },
  { id: 488, name: "Lustrous Orb" },
  { id: 489, name: "Griseous Orb" },
  { id: 490, name: "Fist Plate" },
  { id: 491, name: "Sky Plate" },
  { id: 492, name: "Toxic Plate" },
  { id: 493, name: "Earth Plate" },
  { id: 494, name: "Stone Plate" },
  { id: 495, name: "Insect Plate" },
  { id: 496, name: "Spooky Plate" },
  { id: 497, name: "Iron Plate" },
  { id: 498, name: "Flame Plate" },
  { id: 499, name: "Splash Plate" },
  { id: 500, name: "Meadow Plate" },
  { id: 501, name: "Zap Plate" },
  { id: 502, name: "Mind Plate" },
  { id: 503, name: "Icicle Plate" },
  { id: 504, name: "Draco Plate" },
  { id: 505, name: "Dread Plate" },
  { id: 506, name: "Pixie Plate" },
  { id: 507, name: "Fighting Memory" },
  { id: 508, name: "Flying Memory" },
  { id: 509, name: "Poison Memory" },
  { id: 510, name: "Ground Memory" },
  { id: 511, name: "Rock Memory" },
  { id: 512, name: "Bug Memory" },
  { id: 513, name: "Ghost Memory" },
  { id: 514, name: "Steel Memory" },
  { id: 515, name: "Fire Memory" },
  { id: 516, name: "Water Memory" },
  { id: 517, name: "Grass Memory" },
  { id: 518, name: "Electr Memory" },
  { id: 519, name: "Psychic Memory" },
  { id: 520, name: "Ice Memory" },
  { id: 521, name: "Dragon Memory" },
  { id: 522, name: "Dark Memory" },
  { id: 523, name: "Fairy Memory" },
  { id: 524, name: "Burn Drive" },
  { id: 525, name: "Douse Drive" },
  { id: 526, name: "Shock Drive" },
  { id: 527, name: "Chill Drive" },
  { id: 528, name: "Red Nectar" },
  { id: 529, name: "YellowNectar" },
  { id: 530, name: "Pink Nectar" },
  { id: 531, name: "PurpleNectar" },
  { id: 532, name: "Necrozium Z" },
  { id: 533, name: "Venusaurite" },
  { id: 534, name: "Charizardite X" },
  { id: 535, name: "Charizardite Y" },
  { id: 536, name: "Blastoisnite" },
  { id: 537, name: "Beedrillite" },
  { id: 538, name: "Pidgeotite" },
  { id: 539, name: "Alakazite" },
  { id: 540, name: "Slowbronite" },
  { id: 541, name: "Gengarite" },
  { id: 542, name: "Kangaskanite" },
  { id: 543, name: "Pinsirite" },
  { id: 544, name: "Gyaradosite" },
  { id: 545, name: "Aerodactlite" },
  { id: 546, name: "Mewtwonite X" },
  { id: 547, name: "Mewtwonite Y" },
  { id: 548, name: "Ampharosite" },
  { id: 549, name: "Steelixite" },
  { id: 550, name: "Scizorite" },
  { id: 551, name: "Heracronite" },
  { id: 552, name: "Houndoomnite" },
  { id: 553, name: "Tyranitarite" },
  { id: 554, name: "Sceptilite" },
  { id: 555, name: "Blazikenite" },
  { id: 556, name: "Swampertite" },
  { id: 557, name: "Gardevoirite" },
  { id: 558, name: "Sablenite" },
  { id: 559, name: "Mawilite" },
  { id: 560, name: "Aggronite" },
  { id: 561, name: "Medichamite" },
  { id: 562, name: "Manectite" },
  { id: 563, name: "Sharpedonite" },
  { id: 564, name: "Cameruptite" },
  { id: 565, name: "Altarianite" },
  { id: 566, name: "Banettite" },
  { id: 567, name: "Absolite" },
  { id: 568, name: "Glalitite" },
  { id: 569, name: "Salamencite" },
  { id: 570, name: "Metagrossite" },
  { id: 571, name: "Latiasite" },
  { id: 572, name: "Latiosite" },
  { id: 573, name: "Lopunnite" },
  { id: 574, name: "Garchompite" },
  { id: 575, name: "Lucarionite" },
  { id: 576, name: "Abomasite" },
  { id: 577, name: "Galladite" },
  { id: 578, name: "Audinite" },
  { id: 579, name: "Diancite" },
  { id: 580, name: "Normalium Z" },
  { id: 581, name: "Fightinium Z" },
  { id: 582, name: "Flyinium Z" },
  { id: 583, name: "Poisonium Z" },
  { id: 584, name: "Groundium Z" },
  { id: 585, name: "Rockium Z" },
  { id: 586, name: "Buginium Z" },
  { id: 587, name: "Ghostium Z" },
  { id: 588, name: "Steelium Z" },
  { id: 589, name: "Firium Z" },
  { id: 590, name: "Waterium Z" },
  { id: 591, name: "Grassium Z" },
  { id: 592, name: "Electrium Z" },
  { id: 593, name: "Psychium Z" },
  { id: 594, name: "Icium Z" },
  { id: 595, name: "Dragonium Z" },
  { id: 596, name: "Darkinium Z" },
  { id: 597, name: "Fairium Z" },
  { id: 598, name: "Alorichium Z" },
  { id: 599, name: "Decidium Z" },
  { id: 600, name: "Eevium Z" },
  { id: 601, name: "Incinium Z" },
  { id: 602, name: "Kommonium Z" },
  { id: 603, name: "Lunalium Z" },
  { id: 604, name: "Lycanium Z" },
  { id: 605, name: "Marshadium Z" },
  { id: 606, name: "Mewnium Z" },
  { id: 607, name: "Mimikium Z Z" },
  { id: 608, name: "Pikanium Z" },
  { id: 609, name: "Pikshunium Z" },
  { id: 610, name: "Primarium Z" },
  { id: 611, name: "Snorlium Z" },
  { id: 612, name: "Solganium Z" },
  { id: 613, name: "Tapunium Z" },
  { id: 614, name: "Boost Energy" },
  { id: 615, name: "Loaded Dice" },
  { id: 616, name: "Clear Amulet" },
  { id: 617, name: "Ability Shield" },
  { id: 618, name: "Mirror Herb" },
  { id: 619, name: "Upgrade" },
  { id: 620, name: "Electirizer" },
  { id: 621, name: "Cornerstone Mask" },
  { id: 622, name: "Hearthflame Mask" },
  { id: 623, name: "Wellspring Mask" },
  { id: 624, name: "Teal Mask" },
  { id: 625, name: "Burnt Seed" },
  { id: 626, name: "Magmarizer" },
  { id: 627, name: "Relic Crown" },
  { id: 628, name: "Skull Fossil" },
  { id: 629, name: "Armor Fossil" },
  { id: 630, name: "Cover Fossil" },
  { id: 631, name: "Plume Fossil" },
  { id: 632, name: "Jaw Fossil" },
  { id: 633, name: "Sail Fossil" },
  { id: 634, name: "Bird Fossil" },
  { id: 635, name: "Fish Fossil" },
  { id: 636, name: "Drake Fossil" },
  { id: 637, name: "Dino Fossil" },
  { id: 638, name: "Odd Keystone" },
  { id: 639, name: "Bottle Cap" },
  { id: 640, name: "Gold Bottle Cap" },
  { id: 641, name: "Wish Piece" },
  { id: 642, name: "Power Bracer" },
  { id: 643, name: "Power Belt" },
  { id: 644, name: "Power Lens" },
  { id: 645, name: "Power Band" },
  { id: 646, name: "Power Anklet" },
  { id: 647, name: "Power Weight" },
  { id: 648, name: "Luck Incense" },
  { id: 649, name: "Full Incense" },
  { id: 650, name: "Odd Incense" },
  { id: 651, name: "Pure Incense" },
  { id: 652, name: "Rock Incense" },
  { id: 653, name: "Rose Incense" },
  { id: 654, name: "Wave Incense" },
  { id: 655, name: "Normal Gem" },
  { id: 656, name: "Fighting Gem" },
  { id: 657, name: "Flying Gem" },
  { id: 658, name: "Poison Gem" },
  { id: 659, name: "Ground Gem" },
  { id: 660, name: "Rock Gem" },
  { id: 661, name: "Bug Gem" },
  { id: 662, name: "Ghost Gem" },
  { id: 663, name: "Steel Gem" },
  { id: 664, name: "Fire Gem" },
  { id: 665, name: "Water Gem" },
  { id: 666, name: "Grass Gem" },
  { id: 667, name: "Electric Gem" },
  { id: 668, name: "Psychic Gem" },
  { id: 669, name: "Ice Gem" },
  { id: 670, name: "Dragon Gem" },
  { id: 671, name: "Dark Gem" },
  { id: 672, name: "Fairy Gem" },
  { id: 673, name: "Wide Lens" },
  { id: 674, name: "Muscle Band" },
  { id: 675, name: "Wise Glasses" },
  { id: 676, name: "Expert Belt" },
  { id: 677, name: "Light Clay" },
  { id: 678, name: "Life Orb" },
  { id: 679, name: "Power Herb" },
  { id: 680, name: "Toxic Orb" },
  { id: 681, name: "Flame Orb" },
  { id: 682, name: "Quick Powder" },
  { id: 683, name: "Focus Sash" },
  { id: 684, name: "Zoom Lens" },
  { id: 685, name: "Metronome" },
  { id: 686, name: "Iron Ball" },
  { id: 687, name: "Lagging Tail" },
  { id: 688, name: "Destiny Knot" },
  { id: 689, name: "Black Sludge" },
  { id: 690, name: "Icy Rock" },
  { id: 691, name: "Smooth Rock" },
  { id: 692, name: "Heat Rock" },
  { id: 693, name: "Damp Rock" },
  { id: 694, name: "Grip Claw" },
  { id: 695, name: "Choice Scarf" },
  { id: 696, name: "Choice Specs" },
  { id: 697, name: "Sticky Barb" },
  { id: 698, name: "Shed Shell" },
  { id: 699, name: "Big Root" },
  { id: 700, name: "Eviolite" },
  { id: 701, name: "Float Stone" },
  { id: 702, name: "Rocky Helmet" },
  { id: 703, name: "Air Balloon" },
  { id: 704, name: "Red Card" },
  { id: 705, name: "Ring Target" },
  { id: 706, name: "Binding Band" },
  { id: 707, name: "Absorb Bulb" },
  { id: 708, name: "Cell Battery" },
  { id: 709, name: "Eject Button" },
  { id: 710, name: "Weakness Policy" },
  { id: 711, name: "Assault Vest" },
  { id: 712, name: "Luminous Moss" },
  { id: 713, name: "Snowball" },
  { id: 714, name: "Safe Goggles" },
  { id: 715, name: "Adrenal Orb" },
  { id: 716, name: "Terrain Extender" },
  { id: 717, name: "Protect Pads" },
  { id: 718, name: "Electric Seed" },
  { id: 719, name: "Grassy Seed" },
  { id: 720, name: "Misty Seed" },
  { id: 721, name: "Psychic Seed" },
  { id: 722, name: "Eject Pack" },
  { id: 723, name: "Room Service" },
  { id: 724, name: "Blunder Policy" },
  { id: 725, name: "Heavy-Duty Boots" },
  { id: 726, name: "Utility Umbrella" },
  { id: 727, name: "Throat Spray" },
  { id: 728, name: "Machampite" },
  { id: 729, name: "Laprasite" },
  { id: 730, name: "Butterfrite" },
  { id: 731, name: "Garbodorite" },
  { id: 732, name: "Snorlaxite" },
  { id: 733, name: "Kinglerite" },
  { id: 734, name: "Toxtricitite" },
  { id: 735, name: "Coalossite" },
  { id: 736, name: "Duraludite" },
  { id: 737, name: "Drednawite" },
  { id: 738, name: "Copperajite" },
  { id: 739, name: "Applite" },
  { id: 740, name: "Orbeetlite" },
  { id: 741, name: "Grimmsnite" },
  { id: 742, name: "Medicine" },
  { id: 743, name: "Centiskite" },
  { id: 744, name: "Sandacondite" },
  { id: 745, name: "Alcremite" },
  { id: 746, name: "Eter.Max Orb" },
  { id: 747, name: "Punch Glove" },
  { id: 748, name: "Covert Cloak" },
  { id: 749, name: "Free Space22" },
]

export const RADICAL_RED_ITEM_MAP = new Map<number, string>(
  RADICAL_RED_ITEMS.map((item) => [item.id, item.name])
)

