export const Gen9Locations: { [key: number]: string[] } = {
  0: [
    '——————',
    '',
    'Mystery Zone',
    '',
    'Faraway place',
    '',
    'South Province (Area One)',
    '',
    'Mesagoza',
    '',
    'Pokémon League',
    '',
    'South Province (Area Two)',
    '',
    'South Province (Area Four)',
    '',
    'South Province (Area Six)',
    '',
    'South Province (Area Five)',
    '',
    'South Province (Area Three)',
    '',
    'West Province (Area One)',
    '',
    'Asado Desert',
    '',
    'West Province (Area Two)',
    '',
    'West Province (Area Three)',
    '',
    'Tagtree Thicket',
    '',
    'East Province (Area Three)',
    '',
    'East Province (Area One)',
    '',
    'East Province (Area Two)',
    '',
    'Glaseado Mountain',
    '',
    'Casseroya Lake',
    '',
    'Glaseado Mountain',
    '',
    'North Province (Area Three)',
    '',
    'North Province (Area One)',
    '',
    'North Province (Area Two)',
    '',
    'Great Crater of Paldea',
    '',
    'Zero Gate',
    '',
    'Zero Gate',
    '',
    'South Paldean Sea',
    '',
    'West Paldean Sea',
    '',
    'East Paldean Sea',
    '',
    'North Paldean Sea',
    '',
    'Inlet Grotto',
    '',
    'South Province (Area Six)',
    'Alfornada Cavern',
    'Glaseado Mountain',
    'Dalizapa Passage',
    'Poco Path',
    '',
    'Mesagoza',
    '',
    'Mesagoza',
    '',
    'Cascarrafa',
    '',
    'Levincia',
    '',
    'Cabo Poco',
    '',
    'Los Platos',
    '',
    'Cortondo',
    '',
    'Artazon',
    '',
    'Porto Marinada',
    '',
    'Medali',
    '',
    'Zapapico',
    '',
    'Montenevera',
    '',
    'Alfornada',
    '',
    'North Province (Area Two)',
    "Caph Squad's Base",
    'West Province (Area One)',
    "Segin Squad's Base",
    'North Province (Area Three)',
    "Ruchbah Squad's Base",
    'East Province (Area One)',
    "Schedar Squad's Base",
    'Tagtree Thicket',
    "Navi Squad's Base",
    'Casseroya Lake',
    'Socarrat Trail',
    'Area Zero',
    'Research Station No. 1',
    'Area Zero',
    'Research Station No. 2',
    'Area Zero',
    'Research Station No. 3',
    'Area Zero',
    'Research Station No. 4',
    'Zero Lab',
    '',
    'Zero Lab',
    '',
    'Zero Lab',
    '',
    'Area Zero',
    '',
    'Area Zero',
    '',
    'Area Zero',
    '',
    'Naranja Academy',
    'Uva Academy',
    'Kitakami Road',
    '',
    'Mossui Town',
    '',
    'Apple Hills',
    '',
    'Loyalty Plaza',
    '',
    "Reveler's Road",
    '',
    'Kitakami Hall',
    '',
    'Oni Mountain',
    '',
    'Dreaded Den',
    'Oni Mountain',
    "Oni's Maw",
    'Oni Mountain',
    'Oni Mountain',
    '',
    'Crystal Pool',
    'Oni Mountain Summit',
    'Crystal Pool',
    'Oni Mountain Summit',
    'Wistful Fields',
    '',
    'Mossfell Confluence',
    '',
    'Fellhorn Gorge',
    '',
    'Paradise Barrens',
    '',
    'Kitakami Wilds',
    '',
    'Timeless Woods',
    'Kitakami Wilds',
    'Infernal Pass',
    'Oni Mountain',
    'Chilling Waterhead',
    '',
    'Blueberry Academy',
    '',
    'Savanna Biome',
    '',
    'Coastal Biome',
    '',
    'Canyon Biome',
    '',
    'Polar Biome',
    '',
    'Central Plaza',
    '',
    'Savanna Plaza',
    '',
    'Coastal Plaza',
    '',
    'Canyon Plaza',
    '',
    'Polar Plaza',
    '',
    'Chargestone Cavern',
    '',
    'Torchlit Labyrinth',
    '',
    'Area Zero Underdepths',
    '',
    'Area Zero Underdepths',
    '',
    'Terarium',
  ],
  30000: [
    '',
    'a Link Trade',
    'a Link Trade',
    'the Kanto region',
    'the Johto region',
    'the Hoenn region',
    'the Sinnoh region',
    'a distant land',
    '——————',
    'the Unova region',
    'the Kalos region',
    'Pokémon Link',
    'Pokémon GO',
    'the Kanto region',
    'the Hoenn region',
    'the Alola region',
    'Poké Pelago',
    'the Johto region',
    'Pokémon HOME',
    'the Kanto region',
    'the Galar region',
    'the Hisui region',
    'the Sinnoh region',
    'a picnic',
    'a crystal cavern',
  ],
  40000: [
    '',
    'a lovely place',
    'a faraway place',
    'a Pokémon movie',
    'a 2023 Pokémon movie',
    'a 2024 Pokémon movie',
    'a 2025 Pokémon movie',
    'a 2026 Pokémon movie',
    'a 2027 Pokémon movie',
    'a 2028 Pokémon movie',
    'the Pokémon animated show',
    'a Pokémon Center',
    'Pokémon Center Tohoku',
    'a WCS',
    'WCS 2023',
    'WCS 2024',
    'WCS 2025',
    'WCS 2026',
    'WCS 2027',
    'WCS 2028',
    'Worlds',
    '2023 Worlds',
    '2024 Worlds',
    '2025 Worlds',
    '2026 Worlds',
    '2027 Worlds',
    '2028 Worlds',
    'a VGE',
    'VGE 2023',
    'VGE 2024',
    'VGE 2025',
    'VGE 2026',
    'VGE 2027',
    'VGE 2028',
    'a Pokémon event',
    'a Battle Competition',
    'a game event',
    'the Pokémon Daisuki Club',
    'a Pokémon TV program',
    'a concert',
    'an online present',
    'the PGL',
    'a 2023 Pokémon event',
    'a 2024 Pokémon event',
    'a 2025 Pokémon event',
    'a 2026 Pokémon event',
    'a 2027 Pokémon event',
    'a 2028 Pokémon event',
    'a Pokémon event',
    'a 2023 Pokémon event',
    'a 2024 Pokémon event',
    'a 2025 Pokémon event',
    'a 2026 Pokémon event',
    'a 2027 Pokémon event',
    'a 2028 Pokémon event',
    'PokéPark',
    'PokéPark 2023',
    'PokéPark 2024',
    'PokéPark 2025',
    'PokéPark 2026',
    'PokéPark 2027',
    'PokéPark 2028',
    'an event site',
    'GAME FREAK',
    'a stadium',
    'a VGC event',
    'the VGC 2023',
    'the VGC 2024',
    'the VGC 2025',
    'the VGC 2026',
    'the VGC 2027',
    'the VGC 2028',
    'a Virtual Console game',
    'Pokémon GO',
    'Pokémon Bank',
    'a Pokémon shop',
    'a demo version',
    'the Poké Ball Plus',
    'Pokémon HOME',
    '[~ 78]',
    '[~ 79]',
    '[~ 80]',
    '[~ 81]',
    '[~ 82]',
    '[~ 83]',
    '[~ 84]',
    '[~ 85]',
    '[~ 86]',
    '[~ 87]',
    '[~ 88]',
    '[~ 89]',
    '[~ 90]',
    '[~ 91]',
    '[~ 92]',
    '[~ 93]',
    '[~ 94]',
    '[~ 95]',
    '[~ 96]',
    '[~ 97]',
    '[~ 98]',
    '[~ 99]',
    '[~ 100]',
    '[~ 101]',
    '[~ 102]',
    '[~ 103]',
    '[~ 104]',
    '[~ 105]',
    '[~ 106]',
    '[~ 107]',
    '[~ 108]',
    '[~ 109]',
    '[~ 110]',
    '[~ 111]',
    '[~ 112]',
    '[~ 113]',
    '[~ 114]',
    '[~ 115]',
    '[~ 116]',
    '[~ 117]',
    '[~ 118]',
    '[~ 119]',
    '[~ 120]',
    '[~ 121]',
    '[~ 122]',
    '[~ 123]',
    '[~ 124]',
    '[~ 125]',
    '[~ 126]',
    '[~ 127]',
    '[~ 128]',
    '[~ 129]',
    '[~ 130]',
    '[~ 131]',
    '[~ 132]',
    '[~ 133]',
    '[~ 134]',
    '[~ 135]',
    '[~ 136]',
    '[~ 137]',
    '[~ 138]',
    '[~ 139]',
    '[~ 140]',
    '[~ 141]',
    '[~ 142]',
    '[~ 143]',
    '[~ 144]',
  ],
  60000: [
    '',
    'someone far away',
    'a Nursery worker',
    'a treasure hunter',
    'an old hot-springs visitor',
    'Jacq',
  ],
}
