import { GameLocations } from '../../types/types'

const G6Locations: GameLocations = {
  0: [
    '——————',
    '',
    'Mystery Zone',
    '',
    'Faraway Place',
    '',
    'Vaniville Town',
    '',
    'Route 1',
    'Vaniville Pathway',
    'Aquacorde Town',
    '',
    'Route 2',
    'Avance Trail',
    'Santalune Forest',
    '',
    'Route 3',
    'Ouvert Way',
    'Santalune City',
    '',
    'Route 4',
    'Parterre Way',
    'Lumiose City',
    '',
    'Prism Tower',
    '',
    'Lysandre Labs',
    '',
    'Route 5',
    'Versant Road',
    'Camphrier Town',
    '',
    'Shabboneau Castle',
    '',
    'Route 6',
    'Palais Lane',
    'Parfum Palace',
    '',
    'Route 7',
    'Rivière Walk',
    'Cyllage City',
    '',
    'Route 8',
    'Muraille Coast',
    'Ambrette Town',
    '',
    'Route 9',
    'Spikes Passage',
    'Battle Chateau',
    '',
    'Route 10',
    'Menhir Trail',
    'Geosenge Town',
    '',
    'Route 11',
    'Miroir Way',
    'Reflection Cave',
    '',
    'Shalour City',
    '',
    'Tower of Mastery',
    '',
    'Route 12',
    'Fourrage Road',
    'Coumarine City',
    '',
    'Route 13',
    'Lumiose Badlands',
    'Route 14',
    'Laverre Nature Trail',
    'Laverre City',
    '',
    'Poké Ball Factory',
    '',
    'Route 15',
    'Brun Way',
    'Dendemille Town',
    '',
    'Route 16',
    'Mélancolie Path',
    '[~ 80]',
    '[~ 81]',
    'Frost Cavern',
    '',
    'Route 17',
    'Mamoswine Road',
    'Anistar City',
    '',
    'Route 18',
    'Vallée Étroite Way',
    'Couriway Town',
    '',
    'Route 19',
    'Grande Vallée Way',
    'Snowbelle City',
    '',
    'Route 20',
    'Winding Woods',
    'Pokémon Village',
    '',
    'Route 21',
    'Dernière Way',
    'Route 22',
    'Détourner Way',
    'Victory Road',
    '',
    'Pokémon League',
    '',
    'Kiloude City',
    '',
    'Battle Maison',
    '',
    'Azure Bay',
    '',
    'Dendemille Gate',
    '',
    'Couriway Gate',
    '',
    'Ambrette Gate',
    '',
    'Lumiose Gate',
    '',
    'Shalour Gate',
    '',
    'Coumarine Gate',
    '',
    'Laverre Gate',
    '',
    'Anistar Gate',
    '',
    'Snowbelle Gate',
    '',
    'Glittering Cave',
    '',
    'Connecting Cave',
    'Zubat Roost',
    'Kalos Power Plant',
    '',
    'Team Flare Secret HQ',
    '',
    'Terminus Cave',
    '',
    'Lost Hotel',
    '',
    'Chamber of Emptiness',
    '',
    'Sea Spirit’s Den',
    '',
    'Friend Safari',
    '',
    'Blazing Chamber',
    '',
    'Flood Chamber',
    '',
    'Ironworks Chamber',
    '',
    'Dragonmark Chamber',
    '',
    'Radiant Chamber',
    '',
    'Pokémon League Gate',
    '',
    'Lumiose Station',
    '',
    'Kiloude Station',
    '',
    'Ambrette Aquarium',
    '',
    'Unknown Dungeon',
    '',
    'Littleroot Town',
    '',
    'Oldale Town',
    '',
    'Dewford Town',
    '',
    'Lavaridge Town',
    '',
    'Fallarbor Town',
    '',
    'Verdanturf Town',
    '',
    'Pacifidlog Town',
    '',
    'Petalburg City',
    '',
    'Slateport City',
    '',
    'Mauville City',
    '',
    'Rustboro City',
    '',
    'Fortree City',
    '',
    'Lilycove City',
    '',
    'Mossdeep City',
    '',
    'Sootopolis City',
    '',
    'Ever Grande City',
    '',
    'Pokémon League',
    '',
    'Route 101',
    '',
    'Route 102',
    '',
    'Route 103',
    '',
    'Route 104',
    '',
    'Route 105',
    '',
    'Route 106',
    '',
    'Route 107',
    '',
    'Route 108',
    '',
    'Route 109',
    '',
    'Route 110',
    '',
    'Route 111',
    '',
    'Route 112',
    '',
    'Route 113',
    '',
    'Route 114',
    '',
    'Route 115',
    '',
    'Route 116',
    '',
    'Route 117',
    '',
    'Route 118',
    '',
    'Route 119',
    '',
    'Route 120',
    '',
    'Route 121',
    '',
    'Route 122',
    '',
    'Route 123',
    '',
    'Route 124',
    '',
    'Route 125',
    '',
    'Route 126',
    '',
    'Route 127',
    '',
    'Route 128',
    '',
    'Route 129',
    '',
    'Route 130',
    '',
    'Route 131',
    '',
    'Route 132',
    '',
    'Route 133',
    '',
    'Route 134',
    '',
    'Meteor Falls',
    '',
    'Rusturf Tunnel',
    '',
    '???',
    '',
    'Desert Ruins',
    '',
    'Granite Cave',
    '',
    'Petalburg Woods',
    '',
    'Mt. Chimney',
    '',
    'Jagged Pass',
    '',
    'Fiery Path',
    '',
    'Mt. Pyre',
    '',
    'Team Aqua Hideout',
    '',
    'Seafloor Cavern',
    '',
    'Cave of Origin',
    '',
    'Victory Road',
    '',
    'Shoal Cave',
    '',
    'New Mauville',
    '',
    'Sea Mauville',
    '',
    'Island Cave',
    '',
    'Ancient Tomb',
    '',
    'Sealed Chamber',
    '',
    'Scorched Slab',
    '',
    'Team Magma Hideout',
    '',
    'Sky Pillar',
    '',
    'Battle Resort',
    '',
    'Southern Island',
    '',
    'S.S. Tidal',
    '',
    'Safari Zone',
    '',
    'Mirage Forest',
    '',
    'Mirage Cave',
    '',
    'Mirage Island',
    '',
    'Mirage Mountain',
    '',
    'Trackless Forest',
    '',
    'Pathless Plain',
    '',
    'Nameless Cavern',
    '',
    'Fabled Cave',
    '',
    'Gnarled Den',
    '',
    'Crescent Isle',
    '',
    'Secret Islet',
    '',
    'Soaring in the sky',
    '',
    'Secret Shore',
    '',
    'Secret Meadow',
    '',
    'Secret Base',
  ],
  30000: [
    '',
    'a Link Trade',
    'a Link Trade',
    'the Kanto region',
    'the Johto region',
    'the Hoenn region',
    'the Sinnoh region',
    'a distant land',
    '----------',
    'the Unova region',
    'the Kalos region',
    'Pokémon Link',
  ],
  40000: [
    '',
    'a lovely place',
    'a faraway place',
    'a Pokémon movie',
    'Pokémon Movie 13',
    'Pokémon Movie 14',
    'Pokémon Movie 15',
    'Pokémon Movie 16',
    'Pokémon Movie 17',
    'Pokémon Movie 18',
    'a Pokémon Center',
    'the Pokémon cartoon',
    'PC Tokyo',
    'PC Osaka',
    'PC Fukuoka',
    'PC Nagoya',
    'PC Sapporo',
    'PC Yokohama',
    'PC Tohoku',
    'PC Tokyo Bay',
    'a Pokémon Store',
    'a WCS',
    'WCS 2013',
    'WCS 2014',
    'WCS 2015',
    'WCS 2016',
    'WCS 2017',
    'WCS 2018',
    'Worlds',
    'Worlds 2013',
    'Worlds 2014',
    'Worlds 2015',
    'Worlds 2016',
    'Worlds 2017',
    'Worlds 2018',
    'a VGE',
    'VGE 2013',
    'VGE 2014',
    'VGE 2015',
    'VGE 2016',
    'VGE 2017',
    'VGE 2018',
    'a Pokémon event',
    'a Battle Competition',
    'a game event',
    'the Pokémon Fan Club',
    'a Pokémon TV program',
    'a concert',
    'an online Present',
    'the PGL',
    'Pokémon Event 13',
    'Pokémon Event 14',
    'Pokémon Event 15',
    'Pokémon Event 16',
    'Pokémon Event 17',
    'Pokémon Event 18',
    'Pokémon Festa',
    'Pokémon Festa 13',
    'Pokémon Festa 14',
    'Pokémon Festa 15',
    'Pokémon Festa 16',
    'Pokémon Festa 17',
    'Pokémon Festa 18',
    'POKÉPARK',
    'POKÉPARK',
    'POKÉPARK',
    'POKÉPARK',
    'POKÉPARK',
    'POKÉPARK',
    'POKÉPARK',
    'an event site',
    'GAME FREAK',
    'a stadium',
    'a VGC',
    'the VGC 2013',
    'the VGC 2014',
    'the VGC 2015',
    'the VGC 2016',
    'the VGC 2017',
    'the VGC 2018',
  ],
  60000: [
    '',
    'a stranger',
    'Day Care helpers',
    'a treasure hunter',
    'an old hot-springs visitor',
  ],
}
export default G6Locations
