import { GameLocations } from '../../types/types';

const SMUSUMLocations: GameLocations = {
  0: [
    '——————',
    '',
    'Mystery Zone',
    '',
    'Faraway Place',
    '',
    'Route 1',
    'Hau’oli Outskirts',
    'Route 1',
    '',
    'Route 3',
    '',
    'Route 2',
    '',
    'Kala’e Bay',
    '',
    'Melemele Sea',
    '',
    'Hau’oli City',
    'Beachfront',
    'Hau’oli City',
    'Shopping District',
    'Hau’oli City',
    'Marina',
    'Iki Town',
    '',
    'Mahalo Trail',
    '',
    'Mahalo Trail',
    'Plank Bridge',
    'Ruins of Conflict',
    '',
    'Ruins of Conflict',
    '',
    'Ten Carat Hill',
    '',
    'Ten Carat Hill',
    'Farthest Hollow',
    'Hau’oli Cemetery',
    '',
    'Melemele Meadow',
    '',
    'Seaward Cave',
    '',
    'Berry Fields',
    '',
    'Verdant Cavern',
    'Trial Site',
    'Verdant Cavern',
    'Totem’s Den',
    'Route 4',
    '',
    'Route 5',
    '',
    'Route 6',
    '',
    'Route 7',
    '',
    'Route 8',
    '',
    'Route 9',
    '',
    'Hano Grand Resort',
    '',
    'Hano Beach',
    '',
    'Akala Meadow',
    '',
    'Paniola Town',
    '',
    'Heahea City',
    '',
    'Konikoni City',
    '',
    'Royal Avenue',
    '',
    'Memorial Hill',
    '',
    'Paniola Ranch',
    '',
    '',
    '',
    'Wela Volcano Park',
    '',
    'Wela Volcano Park',
    'Totem’s Den',
    'Brooklet Hill',
    '',
    'Brooklet Hill',
    'Totem’s Den',
    'Lush Jungle',
    '',
    'Ruins of Life',
    '',
    'Akala Outskirts',
    '',
    '',
    '',
    '',
    '',
    'Diglett’s Tunnel',
    '',
    'Hano Grand Resort',
    '',
    'Battle Royal Dome',
    '',
    'Route 10',
    '',
    'Route 11',
    '',
    'Ula’ula Beach',
    '',
    'Route 13',
    '',
    'Tapu Village',
    '',
    'Route 15',
    '',
    'Route 16',
    '',
    'Route 17',
    '',
    'Route 12',
    '',
    'Haina Desert',
    '',
    'Route 14',
    '',
    'Ula’ula Meadow',
    '',
    'Po Town',
    '',
    'Malie City',
    '',
    'Malie Garden',
    '',
    'Mount Hokulani',
    '',
    'Blush Mountain',
    '',
    'Ruins of Abundance',
    '',
    'Lake of the Sunne',
    '',
    'Lake of the Moone',
    '',
    'Mount Lanakila',
    '',
    'Shady House',
    '',
    'Thrifty Megamart',
    'Abandoned Site',
    'Hokulani Observatory',
    '',
    'Pokémon League',
    '',
    'Poni Meadow',
    '',
    'Poni Wilds',
    '',
    'Ancient Poni Path',
    '',
    'Poni Breaker Coast',
    '',
    'Poni Grove',
    '',
    'Poni Plains',
    '',
    'Poni Coast',
    '',
    'Poni Gauntlet',
    '',
    'Seafolk Village',
    '',
    'Vast Poni Canyon',
    '',
    'Altar of the Sunne',
    '',
    'Altar of the Moone',
    '',
    'Ruins of Hope',
    '',
    'Resolution Cave',
    '',
    'Exeggutor Island',
    '',
    'Battle Tree',
    '',
    'Aether Paradise',
    '',
    'Ultra Deep Sea',
    '',
    'Malie City',
    'Outer Cape',
    'Melemele',
    'Akala',
    'Ula’ula',
    'Poni',
    'Big Wave Beach',
    '',
    'Sandy Cave',
    '',
    'Heahea Beach',
    '',
    'Poni Beach',
    '',
    'Ultra Megalopolis',
    '',
    'Megalo Tower',
    '',
    'Ultra Plant',
    '',
    'Ultra Crater',
    '',
    'Ultra Desert',
    '',
    'Ultra Forest',
    '',
    'Ultra Jungle',
    '',
    'Ultra Ruin',
    '',
    'Ultra Space Wilds',
    '',
    'Team Rocket’s Castle',
    '',
    'Plains Grotto',
    '',
    'Pikachu Valley',
    '',
    'Route 1',
    'Trainers’ School',
    'Dividing Peak Tunnel',
  ],
  30000: [
    '',
    'a Link Trade',
    'a Link Trade',
    'the Kanto region',
    'the Johto region',
    'the Hoenn region',
    'the Sinnoh region',
    'a distant land',
    '——————',
    'the Unova region',
    'the Kalos region',
    'Pokémon Link',
    'Pokémon GO',
    'the Kanto region',
    'the Hoenn region',
    'the Alola region',
    'Poké Pelago',
    'the Johto region',
  ],
  40000: [
    '',
    'a lovely place',
    'a faraway place',
    'a Pokémon movie',
    '2016 Pokémon Movie',
    '2017 Pokémon Movie',
    '2018 Pokémon Movie',
    '2019 Pokémon Movie',
    '2020 Pokémon Movie',
    '2021 Pokémon Movie',
    'a Pokémon Center',
    'the Pokémon animated show',
    'Pokémon Ctr. MEGA TOKYO',
    'Pokémon Center Osaka',
    'Pokémon Center Fukuoka',
    'Pokémon Center Nagoya',
    'Pokémon Center Sapporo',
    'Pokémon Center Yokohama',
    'Pokémon Center Tohoku',
    'Pokémon Center TOKYO-BAY',
    'Pokémon Center Hiroshima',
    'Pokémon Center Kyoto',
    'Pokémon Ctr. SKYTREE TOWN',
    'a Pokémon Store',
    'a WCS',
    'WCS 2016',
    'WCS 2017',
    'WCS 2018',
    'WCS 2019',
    'WCS 2020',
    'WCS 2021',
    'Worlds',
    '2016 Worlds',
    '2017 Worlds',
    '2018 Worlds',
    '2019 Worlds',
    '2020 Worlds',
    '2021 Worlds',
    'a VGE',
    'VGE 2016',
    'VGE 2017',
    'VGE 2018',
    'VGE 2019',
    'VGE 2020',
    'VGE 2021',
    'a Pokémon event',
    'a Battle Competition',
    'a game event',
    'the Pokémon Daisuki Club',
    'a Pokémon TV program',
    'a concert',
    'an online present',
    'the PGL',
    'a 2016 Pokémon event',
    'a 2017 Pokémon event',
    'a 2018 Pokémon event',
    'a 2019 Pokémon event',
    'a 2020 Pokémon event',
    'a 2021 Pokémon event',
    'a Pokémon event',
    'a 2016 Pokémon event',
    'a 2017 Pokémon event',
    'a 2018 Pokémon event',
    'a 2019 Pokémon event',
    'a 2020 Pokémon event',
    'a 2021 Pokémon event',
    'PokéPark',
    'PokéPark 2016',
    'PokéPark 2017',
    'PokéPark 2018',
    'PokéPark 2019',
    'PokéPark 2020',
    'PokéPark 2021',
    'an event site',
    'GAME FREAK',
    'a stadium',
    'VGC',
    'the VGC 2016',
    'the VGC 2017',
    'the VGC 2018',
    'the VGC 2019',
    'the VGC 2020',
    'the VGC 2021',
    'a Virtual Console game',
    'Pokémon GO',
    'Pokémon Bank',
    'a Pokémon shop',
    'a demo version',
    'the Pokémon Trainer Club',
  ],
  60000: [
    '',
    'a stranger',
    'Nursery helpers',
    'a treasure hunter',
    'an old hot-springs visitor',
  ],
};

export default SMUSUMLocations;
