#[cfg(feature = "wasm")]
use js_sys::Set;
use serde::Serialize;
use std::fmt::Display;

#[cfg(feature = "wasm")]
use wasm_bindgen::convert::*;
#[cfg(feature = "wasm")]
use wasm_bindgen::describe::*;
#[cfg(feature = "wasm")]
use wasm_bindgen::prelude::*;

#[cfg(feature = "randomize")]
use pkm_rs_types::randomize::Randomize;

use crate::ribbons::ribbon_set::Ribbon;
use crate::ribbons::ribbon_set::RibbonSet;

// #[cfg_attr(feature = "randomize", derive(Randomize))]
// #[derive(Default, Debug, Clone, Copy)]
// pub struct ModernRibbonSet_OLD<const N: usize, const MAX: usize>(FlagSet<N>);

pub type ModernRibbonSet<const N: usize, const MAX: usize = { ModernRibbon::Partner as usize }> =
    RibbonSet<N, ModernRibbon, MAX>;

impl<const N: usize, const MAX: usize> WasmDescribe for ModernRibbonSet<N, MAX> {
    fn describe() {
        js_sys::Set::describe()
    }
}

#[cfg(feature = "wasm")]
impl<const N: usize, const MAX: usize> IntoWasmAbi for ModernRibbonSet<N, MAX> {
    type Abi = <Set as IntoWasmAbi>::Abi;

    fn into_abi(self) -> Self::Abi {
        let set = Set::new(&JsValue::UNDEFINED);
        for ribbon in self.get_ribbons() {
            set.add(&JsValue::from(ribbon as u32));
        }
        set.into_abi()
    }
}

#[cfg_attr(feature = "wasm", wasm_bindgen)]
#[cfg_attr(feature = "randomize", derive(Randomize))]
#[derive(Debug, Serialize, PartialEq, Eq, Clone, Copy, PartialOrd, Ord)]
pub enum ModernRibbon {
    KalosChampion,
    Gen3Champion,
    SinnohChampion,
    BestFriends,
    Training,
    SkillfulBattler,
    ExpertBattler,
    Effort,
    Alert,
    Shock,
    Downcast,
    Careless,
    Relax,
    Snooze,
    Smile,
    Gorgeous,
    Royal,
    GorgeousRoyal,
    Artist,
    Footprint,
    Record,
    Legend,
    Country,
    National,
    Earth,
    World,
    Classic,
    Premier,
    Event,
    Birthday,
    Special,
    Souvenir,
    Wishing,
    BattleChampion,
    RegionalChampion,
    NationalChampion,
    WorldChampion,
    ContestMemory,
    BattleMemory,
    HoennChampion,
    ContestStar,
    CoolnessMaster,
    BeautyMaster,
    CutenessMaster,
    ClevernessMaster,
    ToughnessMaster,
    AlolaChampion,
    BattleRoyalChampion,
    BattleTreeGreat,
    BattleTreeMaster,
    GalarChampion,
    TowerMaster,
    MasterRank,
    LunchtimeMark,
    SleepyTimeMark,
    DuskMark,
    DawnMark,
    CloudyMark,
    RainyMark,
    StormyMark,
    SnowyMark,
    BlizzardMark,
    DryMark,
    SandstormMark,
    MistyMark,
    DestinyMark,
    FishingMark,
    CurryMark,
    UncommonMark,
    RareMark,
    RowdyMark,
    AbsentMindedMark,
    JitteryMark,
    ExcitedMark,
    CharismaticMark,
    CalmnessMark,
    IntenseMark,
    ZonedOutMark,
    JoyfulMark,
    AngryMark,
    SmileyMark,
    TearyMark,
    UpbeatMark,
    PeevedMark,
    IntellectualMark,
    FerociousMark,
    CraftyMark,
    ScowlingMark,
    KindlyMark,
    FlusteredMark,
    PumpedUpMark,
    ZeroEnergyMark,
    PridefulMark,
    UnsureMark,
    HumbleMark,
    ThornyMark,
    VigorMark,
    SlumpMark,
    Hisui,
    TwinklingStar,
    PaldeaChampion,
    JumboMark,
    MiniMark,
    ItemfinderMark,
    PartnerMark,
    GourmandMark,
    OnceInALifetime,
    AlphaMark,
    MightiestMark,
    TitanMark,
    Partner,
}

impl ModernRibbon {
    pub const MAX: usize = ModernRibbon::Partner as usize;
    pub const fn get_name(&self) -> &'static str {
        match self {
            ModernRibbon::KalosChampion => "Kalos Champion Ribbon",
            ModernRibbon::Gen3Champion => "Champion Ribbon",
            ModernRibbon::SinnohChampion => "Sinnoh Champion Ribbon",
            ModernRibbon::BestFriends => "Best Friends Ribbon",
            ModernRibbon::Training => "Training Ribbon",
            ModernRibbon::SkillfulBattler => "Skillful Battler Ribbon",
            ModernRibbon::ExpertBattler => "Expert Battler Ribbon",
            ModernRibbon::Effort => "Effort Ribbon",
            ModernRibbon::Alert => "Alert Ribbon",
            ModernRibbon::Shock => "Shock Ribbon",
            ModernRibbon::Downcast => "Downcast Ribbon",
            ModernRibbon::Careless => "Careless Ribbon",
            ModernRibbon::Relax => "Relax Ribbon",
            ModernRibbon::Snooze => "Snooze Ribbon",
            ModernRibbon::Smile => "Smile Ribbon",
            ModernRibbon::Gorgeous => "Gorgeous Ribbon",
            ModernRibbon::Royal => "Royal Ribbon",
            ModernRibbon::GorgeousRoyal => "Gorgeous Royal Ribbon",
            ModernRibbon::Artist => "Artist Ribbon",
            ModernRibbon::Footprint => "Footprint Ribbon",
            ModernRibbon::Record => "Record Ribbon",
            ModernRibbon::Legend => "Legend Ribbon",
            ModernRibbon::Country => "Country Ribbon",
            ModernRibbon::National => "National Ribbon",
            ModernRibbon::Earth => "Earth Ribbon",
            ModernRibbon::World => "World Ribbon",
            ModernRibbon::Classic => "Classic Ribbon",
            ModernRibbon::Premier => "Premier Ribbon",
            ModernRibbon::Event => "Event Ribbon",
            ModernRibbon::Birthday => "Birthday Ribbon",
            ModernRibbon::Special => "Special Ribbon",
            ModernRibbon::Souvenir => "Souvenir Ribbon",
            ModernRibbon::Wishing => "Wishing Ribbon",
            ModernRibbon::BattleChampion => "Battle Champion Ribbon",
            ModernRibbon::RegionalChampion => "Regional Champion Ribbon",
            ModernRibbon::NationalChampion => "National Champion Ribbon",
            ModernRibbon::WorldChampion => "World Champion Ribbon",
            ModernRibbon::ContestMemory => "Contest Memory Ribbon",
            ModernRibbon::BattleMemory => "Battle Memory Ribbon",
            ModernRibbon::HoennChampion => "Hoenn Champion Ribbon",
            ModernRibbon::ContestStar => "Contest Star Ribbon",
            ModernRibbon::CoolnessMaster => "Coolness Master Ribbon",
            ModernRibbon::BeautyMaster => "Beauty Master Ribbon",
            ModernRibbon::CutenessMaster => "Cuteness Master Ribbon",
            ModernRibbon::ClevernessMaster => "Cleverness Master Ribbon",
            ModernRibbon::ToughnessMaster => "Toughness Master Ribbon",
            ModernRibbon::AlolaChampion => "Alola Champion Ribbon",
            ModernRibbon::BattleRoyalChampion => "Battle Royal Champion Ribbon",
            ModernRibbon::BattleTreeGreat => "Battle Tree Great Ribbon",
            ModernRibbon::BattleTreeMaster => "Battle Tree Master Ribbon",
            ModernRibbon::GalarChampion => "Galar Champion Ribbon",
            ModernRibbon::TowerMaster => "Tower Master Ribbon",
            ModernRibbon::MasterRank => "Master Rank Ribbon",
            ModernRibbon::LunchtimeMark => "Lunchtime Mark",
            ModernRibbon::SleepyTimeMark => "Sleepy-Time Mark",
            ModernRibbon::DuskMark => "Dusk Mark",
            ModernRibbon::DawnMark => "Dawn Mark",
            ModernRibbon::CloudyMark => "Cloudy Mark",
            ModernRibbon::RainyMark => "Rainy Mark",
            ModernRibbon::StormyMark => "Stormy Mark",
            ModernRibbon::SnowyMark => "Snowy Mark",
            ModernRibbon::BlizzardMark => "Blizzard Mark",
            ModernRibbon::DryMark => "Dry Mark",
            ModernRibbon::SandstormMark => "Sandstorm Mark",
            ModernRibbon::MistyMark => "Misty Mark",
            ModernRibbon::DestinyMark => "Destiny Mark",
            ModernRibbon::FishingMark => "Fishing Mark",
            ModernRibbon::CurryMark => "Curry Mark",
            ModernRibbon::UncommonMark => "Uncommon Mark",
            ModernRibbon::RareMark => "Rare Mark",
            ModernRibbon::RowdyMark => "Rowdy Mark",
            ModernRibbon::AbsentMindedMark => "Absent-Minded Mark",
            ModernRibbon::JitteryMark => "Jittery Mark",
            ModernRibbon::ExcitedMark => "Excited Mark",
            ModernRibbon::CharismaticMark => "Charismatic Mark",
            ModernRibbon::CalmnessMark => "Calmness Mark",
            ModernRibbon::IntenseMark => "Intense Mark",
            ModernRibbon::ZonedOutMark => "Zoned-Out Mark",
            ModernRibbon::JoyfulMark => "Joyful Mark",
            ModernRibbon::AngryMark => "Angry Mark",
            ModernRibbon::SmileyMark => "Smiley Mark",
            ModernRibbon::TearyMark => "Teary Mark",
            ModernRibbon::UpbeatMark => "Upbeat Mark",
            ModernRibbon::PeevedMark => "Peeved Mark",
            ModernRibbon::IntellectualMark => "Intellectual Mark",
            ModernRibbon::FerociousMark => "Ferocious Mark",
            ModernRibbon::CraftyMark => "Crafty Mark",
            ModernRibbon::ScowlingMark => "Scowling Mark",
            ModernRibbon::KindlyMark => "Kindly Mark",
            ModernRibbon::FlusteredMark => "Flustered Mark",
            ModernRibbon::PumpedUpMark => "Pumped-Up Mark",
            ModernRibbon::ZeroEnergyMark => "Zero Energy Mark",
            ModernRibbon::PridefulMark => "Prideful Mark",
            ModernRibbon::UnsureMark => "Unsure Mark",
            ModernRibbon::HumbleMark => "Humble Mark",
            ModernRibbon::ThornyMark => "Thorny Mark",
            ModernRibbon::VigorMark => "Vigor Mark",
            ModernRibbon::SlumpMark => "Slump Mark",
            ModernRibbon::Hisui => "Hisui Ribbon",
            ModernRibbon::TwinklingStar => "Twinkling Star Ribbon",
            ModernRibbon::PaldeaChampion => "Paldea Champion Ribbon",
            ModernRibbon::JumboMark => "Jumbo Mark",
            ModernRibbon::MiniMark => "Mini Mark",
            ModernRibbon::ItemfinderMark => "Itemfinder Mark",
            ModernRibbon::PartnerMark => "Partner Mark",
            ModernRibbon::GourmandMark => "Gourmand Mark",
            ModernRibbon::OnceInALifetime => "Once-in-a-Lifetime Ribbon",
            ModernRibbon::AlphaMark => "Alpha Mark",
            ModernRibbon::MightiestMark => "Mightiest Mark",
            ModernRibbon::TitanMark => "Titan Mark",
            ModernRibbon::Partner => "Partner Ribbon",
        }
    }

    pub fn from_name(name: &str) -> Option<Self> {
        let mut full_name = name.to_owned();
        if !full_name.ends_with("Ribbon") && !full_name.ends_with("Mark") {
            full_name = format!("{name} Ribbon");
        }
        match full_name.as_str() {
            "Kalos Champion Ribbon" => Some(Self::KalosChampion),
            "Champion Ribbon" => Some(Self::Gen3Champion),
            "Sinnoh Champion Ribbon" => Some(Self::SinnohChampion),
            "Best Friends Ribbon" => Some(Self::BestFriends),
            "Training Ribbon" => Some(Self::Training),
            "Skillful Battler Ribbon" => Some(Self::SkillfulBattler),
            "Expert Battler Ribbon" => Some(Self::ExpertBattler),
            "Effort Ribbon" => Some(Self::Effort),
            "Alert Ribbon" => Some(Self::Alert),
            "Shock Ribbon" => Some(Self::Shock),
            "Downcast Ribbon" => Some(Self::Downcast),
            "Careless Ribbon" => Some(Self::Careless),
            "Relax Ribbon" => Some(Self::Relax),
            "Snooze Ribbon" => Some(Self::Snooze),
            "Smile Ribbon" => Some(Self::Smile),
            "Gorgeous Ribbon" => Some(Self::Gorgeous),
            "Royal Ribbon" => Some(Self::Royal),
            "Gorgeous Royal Ribbon" => Some(Self::GorgeousRoyal),
            "Artist Ribbon" => Some(Self::Artist),
            "Footprint Ribbon" => Some(Self::Footprint),
            "Record Ribbon" => Some(Self::Record),
            "Legend Ribbon" => Some(Self::Legend),
            "Country Ribbon" => Some(Self::Country),
            "National Ribbon" => Some(Self::National),
            "Earth Ribbon" => Some(Self::Earth),
            "World Ribbon" => Some(Self::World),
            "Classic Ribbon" => Some(Self::Classic),
            "Premier Ribbon" => Some(Self::Premier),
            "Event Ribbon" => Some(Self::Event),
            "Birthday Ribbon" => Some(Self::Birthday),
            "Special Ribbon" => Some(Self::Special),
            "Souvenir Ribbon" => Some(Self::Souvenir),
            "Wishing Ribbon" => Some(Self::Wishing),
            "Battle Champion Ribbon" => Some(Self::BattleChampion),
            "Regional Champion Ribbon" => Some(Self::RegionalChampion),
            "National Champion Ribbon" => Some(Self::NationalChampion),
            "World Champion Ribbon" => Some(Self::WorldChampion),
            "Contest Memory Ribbon" => Some(Self::ContestMemory),
            "Battle Memory Ribbon" => Some(Self::BattleMemory),
            "Hoenn Champion Ribbon" => Some(Self::HoennChampion),
            "Contest Star Ribbon" => Some(Self::ContestStar),
            "Coolness Master Ribbon" => Some(Self::CoolnessMaster),
            "Beauty Master Ribbon" => Some(Self::BeautyMaster),
            "Cuteness Master Ribbon" => Some(Self::CutenessMaster),
            "Cleverness Master Ribbon" => Some(Self::ClevernessMaster),
            "Toughness Master Ribbon" => Some(Self::ToughnessMaster),
            "Alola Champion Ribbon" => Some(Self::AlolaChampion),
            "Battle Royal Champion Ribbon" => Some(Self::BattleRoyalChampion),
            "Battle Tree Great Ribbon" => Some(Self::BattleTreeGreat),
            "Battle Tree Master Ribbon" => Some(Self::BattleTreeMaster),
            "Galar Champion Ribbon" => Some(Self::GalarChampion),
            "Tower Master Ribbon" => Some(Self::TowerMaster),
            "Master Rank Ribbon" => Some(Self::MasterRank),
            "Lunchtime Mark" => Some(Self::LunchtimeMark),
            "Sleepy-Time Mark" => Some(Self::SleepyTimeMark),
            "Dusk Mark" => Some(Self::DuskMark),
            "Dawn Mark" => Some(Self::DawnMark),
            "Cloudy Mark" => Some(Self::CloudyMark),
            "Rainy Mark" => Some(Self::RainyMark),
            "Stormy Mark" => Some(Self::StormyMark),
            "Snowy Mark" => Some(Self::SnowyMark),
            "Blizzard Mark" => Some(Self::BlizzardMark),
            "Dry Mark" => Some(Self::DryMark),
            "Sandstorm Mark" => Some(Self::SandstormMark),
            "Misty Mark" => Some(Self::MistyMark),
            "Destiny Mark" => Some(Self::DestinyMark),
            "Fishing Mark" => Some(Self::FishingMark),
            "Curry Mark" => Some(Self::CurryMark),
            "Uncommon Mark" => Some(Self::UncommonMark),
            "Rare Mark" => Some(Self::RareMark),
            "Rowdy Mark" => Some(Self::RowdyMark),
            "Absent-Minded Mark" => Some(Self::AbsentMindedMark),
            "Jittery Mark" => Some(Self::JitteryMark),
            "Excited Mark" => Some(Self::ExcitedMark),
            "Charismatic Mark" => Some(Self::CharismaticMark),
            "Calmness Mark" => Some(Self::CalmnessMark),
            "Intense Mark" => Some(Self::IntenseMark),
            "Zoned-Out Mark" => Some(Self::ZonedOutMark),
            "Joyful Mark" => Some(Self::JoyfulMark),
            "Angry Mark" => Some(Self::AngryMark),
            "Smiley Mark" => Some(Self::SmileyMark),
            "Teary Mark" => Some(Self::TearyMark),
            "Upbeat Mark" => Some(Self::UpbeatMark),
            "Peeved Mark" => Some(Self::PeevedMark),
            "Intellectual Mark" => Some(Self::IntellectualMark),
            "Ferocious Mark" => Some(Self::FerociousMark),
            "Crafty Mark" => Some(Self::CraftyMark),
            "Scowling Mark" => Some(Self::ScowlingMark),
            "Kindly Mark" => Some(Self::KindlyMark),
            "Flustered Mark" => Some(Self::FlusteredMark),
            "Pumped-Up Mark" => Some(Self::PumpedUpMark),
            "Zero Energy Mark" => Some(Self::ZeroEnergyMark),
            "Prideful Mark" => Some(Self::PridefulMark),
            "Unsure Mark" => Some(Self::UnsureMark),
            "Humble Mark" => Some(Self::HumbleMark),
            "Thorny Mark" => Some(Self::ThornyMark),
            "Vigor Mark" => Some(Self::VigorMark),
            "Slump Mark" => Some(Self::SlumpMark),
            "Hisui Ribbon" => Some(Self::Hisui),
            "Twinkling Star Ribbon" => Some(Self::TwinklingStar),
            "Paldea Champion Ribbon" => Some(Self::PaldeaChampion),
            "Jumbo Mark" => Some(Self::JumboMark),
            "Mini Mark" => Some(Self::MiniMark),
            "Itemfinder Mark" => Some(Self::ItemfinderMark),
            "Partner Mark" => Some(Self::PartnerMark),
            "Gourmand Mark" => Some(Self::GourmandMark),
            "Once-in-a-Lifetime Ribbon" => Some(Self::OnceInALifetime),
            "Alpha Mark" => Some(Self::AlphaMark),
            "Mightiest Mark" => Some(Self::MightiestMark),
            "Titan Mark" => Some(Self::TitanMark),
            "Partner Ribbon" => Some(Self::Partner),
            _ => None,
        }
    }

    pub const fn get_index(&self) -> usize {
        match self {
            ModernRibbon::KalosChampion => 0,
            ModernRibbon::Gen3Champion => 1,
            ModernRibbon::SinnohChampion => 2,
            ModernRibbon::BestFriends => 3,
            ModernRibbon::Training => 4,
            ModernRibbon::SkillfulBattler => 5,
            ModernRibbon::ExpertBattler => 6,
            ModernRibbon::Effort => 7,
            ModernRibbon::Alert => 8,
            ModernRibbon::Shock => 9,
            ModernRibbon::Downcast => 10,
            ModernRibbon::Careless => 11,
            ModernRibbon::Relax => 12,
            ModernRibbon::Snooze => 13,
            ModernRibbon::Smile => 14,
            ModernRibbon::Gorgeous => 15,
            ModernRibbon::Royal => 16,
            ModernRibbon::GorgeousRoyal => 17,
            ModernRibbon::Artist => 18,
            ModernRibbon::Footprint => 19,
            ModernRibbon::Record => 20,
            ModernRibbon::Legend => 21,
            ModernRibbon::Country => 22,
            ModernRibbon::National => 23,
            ModernRibbon::Earth => 24,
            ModernRibbon::World => 25,
            ModernRibbon::Classic => 26,
            ModernRibbon::Premier => 27,
            ModernRibbon::Event => 28,
            ModernRibbon::Birthday => 29,
            ModernRibbon::Special => 30,
            ModernRibbon::Souvenir => 31,
            ModernRibbon::Wishing => 32,
            ModernRibbon::BattleChampion => 33,
            ModernRibbon::RegionalChampion => 34,
            ModernRibbon::NationalChampion => 35,
            ModernRibbon::WorldChampion => 36,
            ModernRibbon::ContestMemory => 37,
            ModernRibbon::BattleMemory => 38,
            ModernRibbon::HoennChampion => 39,
            ModernRibbon::ContestStar => 40,
            ModernRibbon::CoolnessMaster => 41,
            ModernRibbon::BeautyMaster => 42,
            ModernRibbon::CutenessMaster => 43,
            ModernRibbon::ClevernessMaster => 44,
            ModernRibbon::ToughnessMaster => 45,
            ModernRibbon::AlolaChampion => 46,
            ModernRibbon::BattleRoyalChampion => 47,
            ModernRibbon::BattleTreeGreat => 48,
            ModernRibbon::BattleTreeMaster => 49,
            ModernRibbon::GalarChampion => 50,
            ModernRibbon::TowerMaster => 51,
            ModernRibbon::MasterRank => 52,
            ModernRibbon::LunchtimeMark => 53,
            ModernRibbon::SleepyTimeMark => 54,
            ModernRibbon::DuskMark => 55,
            ModernRibbon::DawnMark => 56,
            ModernRibbon::CloudyMark => 57,
            ModernRibbon::RainyMark => 58,
            ModernRibbon::StormyMark => 59,
            ModernRibbon::SnowyMark => 60,
            ModernRibbon::BlizzardMark => 61,
            ModernRibbon::DryMark => 62,
            ModernRibbon::SandstormMark => 63,
            ModernRibbon::MistyMark => 64,
            ModernRibbon::DestinyMark => 65,
            ModernRibbon::FishingMark => 66,
            ModernRibbon::CurryMark => 67,
            ModernRibbon::UncommonMark => 68,
            ModernRibbon::RareMark => 69,
            ModernRibbon::RowdyMark => 70,
            ModernRibbon::AbsentMindedMark => 71,
            ModernRibbon::JitteryMark => 72,
            ModernRibbon::ExcitedMark => 73,
            ModernRibbon::CharismaticMark => 74,
            ModernRibbon::CalmnessMark => 75,
            ModernRibbon::IntenseMark => 76,
            ModernRibbon::ZonedOutMark => 77,
            ModernRibbon::JoyfulMark => 78,
            ModernRibbon::AngryMark => 79,
            ModernRibbon::SmileyMark => 80,
            ModernRibbon::TearyMark => 81,
            ModernRibbon::UpbeatMark => 82,
            ModernRibbon::PeevedMark => 83,
            ModernRibbon::IntellectualMark => 84,
            ModernRibbon::FerociousMark => 85,
            ModernRibbon::CraftyMark => 86,
            ModernRibbon::ScowlingMark => 87,
            ModernRibbon::KindlyMark => 88,
            ModernRibbon::FlusteredMark => 89,
            ModernRibbon::PumpedUpMark => 90,
            ModernRibbon::ZeroEnergyMark => 91,
            ModernRibbon::PridefulMark => 92,
            ModernRibbon::UnsureMark => 93,
            ModernRibbon::HumbleMark => 94,
            ModernRibbon::ThornyMark => 95,
            ModernRibbon::VigorMark => 96,
            ModernRibbon::SlumpMark => 97,
            ModernRibbon::Hisui => 98,
            ModernRibbon::TwinklingStar => 99,
            ModernRibbon::PaldeaChampion => 100,
            ModernRibbon::JumboMark => 101,
            ModernRibbon::MiniMark => 102,
            ModernRibbon::ItemfinderMark => 103,
            ModernRibbon::PartnerMark => 104,
            ModernRibbon::GourmandMark => 105,
            ModernRibbon::OnceInALifetime => 106,
            ModernRibbon::AlphaMark => 107,
            ModernRibbon::MightiestMark => 108,
            ModernRibbon::TitanMark => 109,
            ModernRibbon::Partner => 110,
        }
    }

    pub fn from_affixed_byte(affixed_byte: u8) -> Option<ModernRibbon> {
        match affixed_byte {
            0xff => None,
            value => ModernRibbon::from_index(value),
        }
    }

    pub const fn to_affixed_byte(affixed: Option<ModernRibbon>) -> u8 {
        match affixed {
            None => 0xff,
            Some(ribbon) => ribbon.get_index() as u8,
        }
    }

    pub fn from_index(value: impl Into<usize>) -> Option<Self> {
        match value.into() {
            0 => Some(Self::KalosChampion),
            1 => Some(Self::Gen3Champion),
            2 => Some(Self::SinnohChampion),
            3 => Some(Self::BestFriends),
            4 => Some(Self::Training),
            5 => Some(Self::SkillfulBattler),
            6 => Some(Self::ExpertBattler),
            7 => Some(Self::Effort),
            8 => Some(Self::Alert),
            9 => Some(Self::Shock),
            10 => Some(Self::Downcast),
            11 => Some(Self::Careless),
            12 => Some(Self::Relax),
            13 => Some(Self::Snooze),
            14 => Some(Self::Smile),
            15 => Some(Self::Gorgeous),
            16 => Some(Self::Royal),
            17 => Some(Self::GorgeousRoyal),
            18 => Some(Self::Artist),
            19 => Some(Self::Footprint),
            20 => Some(Self::Record),
            21 => Some(Self::Legend),
            22 => Some(Self::Country),
            23 => Some(Self::National),
            24 => Some(Self::Earth),
            25 => Some(Self::World),
            26 => Some(Self::Classic),
            27 => Some(Self::Premier),
            28 => Some(Self::Event),
            29 => Some(Self::Birthday),
            30 => Some(Self::Special),
            31 => Some(Self::Souvenir),
            32 => Some(Self::Wishing),
            33 => Some(Self::BattleChampion),
            34 => Some(Self::RegionalChampion),
            35 => Some(Self::NationalChampion),
            36 => Some(Self::WorldChampion),
            37 => Some(Self::ContestMemory),
            38 => Some(Self::BattleMemory),
            39 => Some(Self::HoennChampion),
            40 => Some(Self::ContestStar),
            41 => Some(Self::CoolnessMaster),
            42 => Some(Self::BeautyMaster),
            43 => Some(Self::CutenessMaster),
            44 => Some(Self::ClevernessMaster),
            45 => Some(Self::ToughnessMaster),
            46 => Some(Self::AlolaChampion),
            47 => Some(Self::BattleRoyalChampion),
            48 => Some(Self::BattleTreeGreat),
            49 => Some(Self::BattleTreeMaster),
            50 => Some(Self::GalarChampion),
            51 => Some(Self::TowerMaster),
            52 => Some(Self::MasterRank),
            53 => Some(Self::LunchtimeMark),
            54 => Some(Self::SleepyTimeMark),
            55 => Some(Self::DuskMark),
            56 => Some(Self::DawnMark),
            57 => Some(Self::CloudyMark),
            58 => Some(Self::RainyMark),
            59 => Some(Self::StormyMark),
            60 => Some(Self::SnowyMark),
            61 => Some(Self::BlizzardMark),
            62 => Some(Self::DryMark),
            63 => Some(Self::SandstormMark),
            64 => Some(Self::MistyMark),
            65 => Some(Self::DestinyMark),
            66 => Some(Self::FishingMark),
            67 => Some(Self::CurryMark),
            68 => Some(Self::UncommonMark),
            69 => Some(Self::RareMark),
            70 => Some(Self::RowdyMark),
            71 => Some(Self::AbsentMindedMark),
            72 => Some(Self::JitteryMark),
            73 => Some(Self::ExcitedMark),
            74 => Some(Self::CharismaticMark),
            75 => Some(Self::CalmnessMark),
            76 => Some(Self::IntenseMark),
            77 => Some(Self::ZonedOutMark),
            78 => Some(Self::JoyfulMark),
            79 => Some(Self::AngryMark),
            80 => Some(Self::SmileyMark),
            81 => Some(Self::TearyMark),
            82 => Some(Self::UpbeatMark),
            83 => Some(Self::PeevedMark),
            84 => Some(Self::IntellectualMark),
            85 => Some(Self::FerociousMark),
            86 => Some(Self::CraftyMark),
            87 => Some(Self::ScowlingMark),
            88 => Some(Self::KindlyMark),
            89 => Some(Self::FlusteredMark),
            90 => Some(Self::PumpedUpMark),
            91 => Some(Self::ZeroEnergyMark),
            92 => Some(Self::PridefulMark),
            93 => Some(Self::UnsureMark),
            94 => Some(Self::HumbleMark),
            95 => Some(Self::ThornyMark),
            96 => Some(Self::VigorMark),
            97 => Some(Self::SlumpMark),
            98 => Some(Self::Hisui),
            99 => Some(Self::TwinklingStar),
            100 => Some(Self::PaldeaChampion),
            101 => Some(Self::JumboMark),
            102 => Some(Self::MiniMark),
            103 => Some(Self::ItemfinderMark),
            104 => Some(Self::PartnerMark),
            105 => Some(Self::GourmandMark),
            106 => Some(Self::OnceInALifetime),
            107 => Some(Self::AlphaMark),
            108 => Some(Self::MightiestMark),
            109 => Some(Self::TitanMark),
            110 => Some(Self::Partner),
            _ => None,
        }
    }
}

impl From<usize> for ModernRibbon {
    fn from(value: usize) -> Self {
        Self::from_index(value).expect("Invalid ribbon index")
    }
}

impl From<ModernRibbon> for usize {
    fn from(ribbon: ModernRibbon) -> Self {
        ribbon.get_index()
    }
}

impl Display for ModernRibbon {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.get_name())
    }
}

impl Ribbon for ModernRibbon {
    const MAX: usize = ModernRibbon::Partner as usize;
}
