export const GameLogos: { [key: string]: string } = {
  AlphaSapphire: require(`./logos/Alpha_Sapphire.png`),
  Black2: require(`./logos/Black_2.png`),
  Black: require(`./logos/Black.png`),
  BlueGreen: require(`./logos/Blue_Green.png`),
  BlueJP: require(`./logos/Blue_JP.png`),
  BrilliantDiamond: require(`./logos/Brilliant_Diamond.png`),
  Colosseum: require(`./logos/Colosseum.png`),
  ColosseumXD: require(`./logos/ColosseumXD.png`),
  Crystal: require(`./logos/Crystal.png`),
  Diamond: require(`./logos/Diamond.png`),
  Emerald: require(`./logos/Emerald.png`),
  FireRed: require(`./logos/FireRed.png`),
  GB: require(`./logos/GB.png`),
  GO: require(`./logos/GO.png`),
  Gold: require(`./logos/Gold.png`),
  HeartGold: require(`./logos/HeartGold.png`),
  LeafGreen: require(`./logos/LeafGreen.png`),
  LegendsArceus: require(`./logos/Legends_Arceus.png`),
  LetsGoEevee: require(`./logos/Let's_Go_Eevee.png`),
  LetsGoPikachu: require(`./logos/Let's_Go_Pikachu.png`),
  Moon: require(`./logos/Moon.png`),
  OmegaRuby: require(`./logos/Omega_Ruby.png`),
  Pearl: require(`./logos/Pearl.png`),
  Platinum: require(`./logos/Platinum.png`),
  Red: require(`./logos/Red.png`),
  Ruby: require(`./logos/Ruby.png`),
  Sapphire: require(`./logos/Sapphire.png`),
  Scarlet: require(`./logos/Scarlet.png`),
  Shield: require(`./logos/Shield.png`),
  ShiningPearl: require(`./logos/Shining_Pearl.png`),
  Silver: require(`./logos/Silver.png`),
  SoulSilver: require(`./logos/SoulSilver.png`),
  Sun: require(`./logos/Sun.png`),
  Sword: require(`./logos/Sword.png`),
  UltraMoon: require(`./logos/Ultra_Moon.png`),
  UltraSun: require(`./logos/Ultra_Sun.png`),
  Violet: require(`./logos/Violet.png`),
  White2: require(`./logos/White_2.png`),
  White: require(`./logos/White.png`),
  X: require(`./logos/X.png`),
  XD: require(`./logos/XD.png`),
  Y: require(`./logos/Y.png`),
  Yellow: require(`./logos/Yellow.png`),
};

export const OriginMarks: { [key: string]: string } = {
  Alola: require(`./origin_marks/Alola.png`),
  BDSP: require(`./origin_marks/BDSP.png`),
  G6: require(`./origin_marks/G6.png`),
  Galar: require(`./origin_marks/Galar.png`),
  GB: require(`./origin_marks/GB.png`),
  GO: require(`./origin_marks/GO.png`),
  LA: require(`./origin_marks/LA.png`),
  LGPE: require(`./origin_marks/LGPE.png`),
  Tera: require(`./origin_marks/Tera.png`),
};
