/* eslint-disable global-require */
export const GameLogos: { [key: string]: string } = {
  AlphaSapphire: require(`./logos/Alpha_Sapphire.png`),
  Black2: require(`./logos/Black_2.png`),
  Black: require(`./logos/Black.png`),
  BlueGreen: require(`./logos/Blue_Green.png`),
  BlueJP: require(`./logos/Blue_JP.png`),
  BrilliantDiamond: require(`./logos/Brilliant_Diamond.png`),
  Colosseum: require(`./logos/Colosseum.png`),
  ColosseumXD: require(`./logos/ColosseumXD.png`),
  Crystal: require(`./logos/Crystal.png`),
  Diamond: require(`./logos/Diamond.png`),
  Emerald: require(`./logos/Emerald.png`),
  FireRed: require(`./logos/FireRed.png`),
  GB: require(`./logos/GB.png`),
  GO: require(`./logos/GO.png`),
  Gold: require(`./logos/Gold.png`),
  HeartGold: require(`./logos/HeartGold.png`),
  LeafGreen: require(`./logos/LeafGreen.png`),
  LegendsArceus: require(`./logos/Legends_Arceus.png`),
  LetsGoEevee: require(`./logos/Let's_Go_Eevee.png`),
  LetsGoPikachu: require(`./logos/Let's_Go_Pikachu.png`),
  Moon: require(`./logos/Moon.png`),
  OmegaRuby: require(`./logos/Omega_Ruby.png`),
  Pearl: require(`./logos/Pearl.png`),
  Platinum: require(`./logos/Platinum.png`),
  Red: require(`./logos/Red.png`),
  Ruby: require(`./logos/Ruby.png`),
  Sapphire: require(`./logos/Sapphire.png`),
  Scarlet: require(`./logos/Scarlet.png`),
  Shield: require(`./logos/Shield.png`),
  ShiningPearl: require(`./logos/Shining_Pearl.png`),
  Silver: require(`./logos/Silver.png`),
  SoulSilver: require(`./logos/SoulSilver.png`),
  Sun: require(`./logos/Sun.png`),
  Sword: require(`./logos/Sword.png`),
  UltraMoon: require(`./logos/Ultra_Moon.png`),
  UltraSun: require(`./logos/Ultra_Sun.png`),
  Violet: require(`./logos/Violet.png`),
  White2: require(`./logos/White_2.png`),
  White: require(`./logos/White.png`),
  X: require(`./logos/X.png`),
  XD: require(`./logos/XD.png`),
  Y: require(`./logos/Y.png`),
  Yellow: require(`./logos/Yellow.png`),
};

export const OriginMarks: { [key: string]: string } = {
  Alola: require(`./origin_marks/Alola.png`),
  BDSP: require(`./origin_marks/BDSP.png`),
  G6: require(`./origin_marks/G6.png`),
  Galar: require(`./origin_marks/Galar.png`),
  GB: require(`./origin_marks/GB.png`),
  GO: require(`./origin_marks/GO.png`),
  LA: require(`./origin_marks/LA.png`),
  LGPE: require(`./origin_marks/LGPE.png`),
  Tera: require(`./origin_marks/Tera.png`),
};

export const BallsMap: { [key: string]: string } = {
  Master: require(`./items/index/0001.png`),
  Ultra: require(`./items/index/0002.png`),
  Great: require(`./items/index/0003.png`),
  Poke: require(`./items/index/0004.png`),
  Safari: require(`./items/index/0005.png`),
  Net: require(`./items/index/0006.png`),
  Dive: require(`./items/index/0007.png`),
  Nest: require(`./items/index/0008.png`),
  Repeat: require(`./items/index/0009.png`),
  Timer: require(`./items/index/0010.png`),
  Luxury: require(`./items/index/0011.png`),
  Premier: require(`./items/index/0012.png`),
  Dusk: require(`./items/index/0013.png`),
  Heal: require(`./items/index/0014.png`),
  Quick: require(`./items/index/0015.png`),
  Cherish: require(`./items/index/0016.png`),
  Fast: require(`./items/index/0492.png`),
  Level: require(`./items/index/0493.png`),
  Lure: require(`./items/index/0494.png`),
  Heavy: require(`./items/index/0495.png`),
  Love: require(`./items/index/0496.png`),
  Friend: require(`./items/index/0497.png`),
  Moon: require(`./items/index/0498.png`),
  Sport: require(`./items/index/0499.png`),
  Dream: require(`./items/index/0576.png`),
  Beast: require(`./items/index/0851.png`),
  PokeLA: require(`./items/index/1710.png`),
  GreatLA: require(`./items/index/1711.png`),
  UltraLA: require(`./items/index/1712.png`),
  Feather: require(`./items/index/1713.png`),
  Wing: require(`./items/index/1746.png`),
  Jet: require(`./items/index/1747.png`),
  HeavyLA: require(`./items/index/1748.png`),
  Leaden: require(`./items/index/1749.png`),
  Gigaton: require(`./items/index/1750.png`),
  Origin: require(`./items/index/1771.png`),
};

export const BallsList = [
  '',
  BallsMap.Master,
  BallsMap.Ultra,
  BallsMap.Great,
  BallsMap.Poke,
  BallsMap.Safari,
  BallsMap.Net,
  BallsMap.Dive,
  BallsMap.Nest,
  BallsMap.Repeat,
  BallsMap.Timer,
  BallsMap.Luxury,
  BallsMap.Premier,
  BallsMap.Dusk,
  BallsMap.Heal,
  BallsMap.Quick,
  BallsMap.Cherish,
  BallsMap.Fast,
  BallsMap.Level,
  BallsMap.Lure,
  BallsMap.Heavy,
  BallsMap.Love,
  BallsMap.Friend,
  BallsMap.Moon,
  BallsMap.Sport,
  BallsMap.Dream,
  BallsMap.Beast,
  BallsMap.PokeLA,
  BallsMap.GreatLA,
  BallsMap.UltraLA,
  BallsMap.Feather,
  BallsMap.Wing,
  BallsMap.Jet,
  BallsMap.HeavyLA,
  BallsMap.Leaden,
  BallsMap.Gigaton,
  BallsMap.Origin,
];

export const RibbonsMap: { [key: string]: string } = {
  'Absent Minded Mark': require(`./ribbons/absent-minded-mark.png`),
  'Kalos Champion': require(`./ribbons/kalos-champion.png`),
  Champion: require(`./ribbons/champion.png`),
  'Sinnoh Champion': require(`./ribbons/sinnoh-champion.png`),
  'Best Friends': require(`./ribbons/best-friends.png`),
  Training: require(`./ribbons/training.png`),
  'Skillful Battler': require(`./ribbons/skillful-battler.png`),
  'Expert Battler': require(`./ribbons/expert-battler.png`),
  Effort: require(`./ribbons/effort.png`),
  Alert: require(`./ribbons/alert.png`),
  Shock: require(`./ribbons/shock.png`),
  Downcast: require(`./ribbons/downcast.png`),
  Careless: require(`./ribbons/careless.png`),
  Relax: require(`./ribbons/relax.png`),
  Snooze: require(`./ribbons/snooze.png`),
  Smile: require(`./ribbons/smile.png`),
  Gorgeous: require(`./ribbons/gorgeous.png`),
  Royal: require(`./ribbons/royal.png`),
  'Gorgeous Royal': require(`./ribbons/gorgeous-royal.png`),
  Artist: require(`./ribbons/artist.png`),
  Footprint: require(`./ribbons/footprint.png`),
  Record: require(`./ribbons/record.png`),
  Legend: require(`./ribbons/legend.png`),
  Country: require(`./ribbons/country.png`),
  National: require(`./ribbons/national.png`),
  Earth: require(`./ribbons/earth.png`),
  World: require(`./ribbons/world.png`),
  Classic: require(`./ribbons/classic.png`),
  Premier: require(`./ribbons/premier.png`),
  Event: require(`./ribbons/event.png`),
  Birthday: require(`./ribbons/birthday.png`),
  Special: require(`./ribbons/special.png`),
  Souvenir: require(`./ribbons/souvenir.png`),
  Wishing: require(`./ribbons/wishing.png`),
  'Battle Champion': require(`./ribbons/battle-champion.png`),
  'Regional Champion': require(`./ribbons/regional-champion.png`),
  'National Champion': require(`./ribbons/national-champion.png`),
  'World Champion': require(`./ribbons/world-champion.png`),
  'Contest Memory': require(`./ribbons/contest-memory.png`),
  'Battle Memory': require(`./ribbons/battle-memory.png`),
  'Contest Memory Gold': require(`./ribbons/contest-memory-gold.png`),
  'Battle Memory Gold': require(`./ribbons/battle-memory-gold.png`),
  'Hoenn Champion': require(`./ribbons/hoenn-champion.png`),
  'Contest Star': require(`./ribbons/contest-star.png`),
  'Coolness Master': require(`./ribbons/coolness-master.png`),
  'Beauty Master': require(`./ribbons/beauty-master.png`),
  'Cuteness Master': require(`./ribbons/cuteness-master.png`),
  'Cleverness Master': require(`./ribbons/cleverness-master.png`),
  'Toughness Master': require(`./ribbons/toughness-master.png`),
  'Alola Champion': require(`./ribbons/alola-champion.png`),
  'Battle Royal Master': require('./ribbons/battle-royal-master.png'),
  'Battle Tree Great': require('./ribbons/battle-tree-great.png'),
  'Battle Tree Master': require('./ribbons/battle-tree-master.png'),
  'Galar Champion': require('./ribbons/galar-champion.png'),
  'Tower Master': require('./ribbons/tower-master.png'),
  'Master Rank': require('./ribbons/master-rank.png'),
  'Lunchtime Mark': require('./ribbons/lunchtime-mark.png'),
  'Sleepy-Time Mark': require('./ribbons/sleepy-time-mark.png'),
  'Dusk Mark': require('./ribbons/dusk-mark.png'),
  'Dawn Mark': require('./ribbons/dawn-mark.png'),
  'Cloudy Mark': require('./ribbons/cloudy-mark.png'),
  'Rainy Mark': require('./ribbons/rainy-mark.png'),
  'Stormy Mark': require('./ribbons/stormy-mark.png'),
  'Snowy Mark': require('./ribbons/snowy-mark.png'),
  'Blizzard Mark': require('./ribbons/blizzard-mark.png'),
  'Dry Mark': require('./ribbons/dry-mark.png'),
  'Sandstorm Mark': require('./ribbons/sandstorm-mark.png'),
  'Misty Mark': require('./ribbons/misty-mark.png'),
  'Destiny Mark': require('./ribbons/destiny-mark.png'),
  'Fishing Mark': require('./ribbons/fishing-mark.png'),
  'Curry Mark': require('./ribbons/curry-mark.png'),
  'Uncommon Mark': require('./ribbons/uncommon-mark.png'),
  'Rare Mark': require('./ribbons/rare-mark.png'),
  'Rowdy Mark': require('./ribbons/rowdy-mark.png'),
  'Absent-Minded Mark': require('./ribbons/absent-minded-mark.png'),
  'Jittery Mark': require('./ribbons/jittery-mark.png'),
  'Excited Mark': require('./ribbons/excited-mark.png'),
  'Charismatic Mark': require('./ribbons/charismatic-mark.png'),
  'Calmness Mark': require('./ribbons/calmness-mark.png'),
  'Intense Mark': require('./ribbons/intense-mark.png'),
  'Zoned-Out Mark': require('./ribbons/zoned-out-mark.png'),
  'Joyful Mark': require('./ribbons/joyful-mark.png'),
  'Angry Mark': require('./ribbons/angry-mark.png'),
  'Smiley Mark': require('./ribbons/smiley-mark.png'),
  'Teary Mark': require('./ribbons/teary-mark.png'),
  'Upbeat Mark': require('./ribbons/upbeat-mark.png'),
  'Peeved Mark': require('./ribbons/peeved-mark.png'),
  'Intellectual Mark': require('./ribbons/intellectual-mark.png'),
  'Ferocious Mark': require('./ribbons/ferocious-mark.png'),
  'Crafty Mark': require('./ribbons/crafty-mark.png'),
  'Scowling Mark': require('./ribbons/scowling-mark.png'),
  'Kindly Mark': require('./ribbons/kindly-mark.png'),
  'Flustered Mark': require('./ribbons/flustered-mark.png'),
  'Pumped-Up Mark': require('./ribbons/pumped-up-mark.png'),
  'Zero Energy Mark': require('./ribbons/zero-energy-mark.png'),
  'Prideful Mark': require('./ribbons/prideful-mark.png'),
  'Unsure Mark': require('./ribbons/unsure-mark.png'),
  'Humble Mark': require('./ribbons/humble-mark.png'),
  'Thorny Mark': require('./ribbons/thorny-mark.png'),
  'Vigor Mark': require('./ribbons/vigor-mark.png'),
  'Slump Mark': require('./ribbons/slump-mark.png'),
  Hisui: require('./ribbons/hisui.png'),
  'Twinkling Star': require('./ribbons/twinkling-star.png'),
  'Paldea Champion': require('./ribbons/paldea-champion.png'),
  'Jumbo Mark': require('./ribbons/jumbo-mark.png'),
  'Mini Mark': require('./ribbons/mini-mark.png'),
  'Itemfinder Mark': require('./ribbons/itemfinder-mark.png'),
  'Partner Mark': require('./ribbons/partner-mark.png'),
  'Gourmand Mark': require('./ribbons/gourmand-mark.png'),
  'Once-in-a-Lifetime': require('./ribbons/once-in-a-lifetime.png'),
  'Alpha Mark': require('./ribbons/alpha-mark.png'),
  'Mightiest Mark': require('./ribbons/mightiest-mark.png'),
  'Titan Mark': require('./ribbons/titan-mark.png'),
  'Cool (Hoenn)': require('./ribbons/cool-hoenn.png'),
  'Cool Super (Hoenn)': require('./ribbons/cool-super-hoenn.png'),
  'Cool Hyper (Hoenn)': require('./ribbons/cool-hyper-hoenn.png'),
  'Cool Master (Hoenn)': require('./ribbons/cool-master-hoenn.png'),
  'Beauty (Hoenn)': require('./ribbons/beauty-hoenn.png'),
  'Beauty Super (Hoenn)': require('./ribbons/beauty-super-hoenn.png'),
  'Beauty Hyper (Hoenn)': require('./ribbons/beauty-hyper-hoenn.png'),
  'Beauty Master (Hoenn)': require('./ribbons/beauty-master-hoenn.png'),
  'Cute (Hoenn)': require('./ribbons/cute-hoenn.png'),
  'Cute Super (Hoenn)': require('./ribbons/cute-super-hoenn.png'),
  'Cute Hyper (Hoenn)': require('./ribbons/cute-hyper-hoenn.png'),
  'Cute Master (Hoenn)': require('./ribbons/cute-master-hoenn.png'),
  'Smart (Hoenn)': require('./ribbons/smart-hoenn.png'),
  'Smart Super (Hoenn)': require('./ribbons/smart-super-hoenn.png'),
  'Smart Hyper (Hoenn)': require('./ribbons/smart-hyper-hoenn.png'),
  'Smart Master (Hoenn)': require('./ribbons/smart-master-hoenn.png'),
  'Tough (Hoenn)': require('./ribbons/tough-hoenn.png'),
  'Tough Super (Hoenn)': require('./ribbons/tough-super-hoenn.png'),
  'Tough Hyper (Hoenn)': require('./ribbons/tough-hyper-hoenn.png'),
  'Tough Master (Hoenn)': require('./ribbons/tough-master-hoenn.png'),
  'Cool (Sinnoh)': require('./ribbons/cool-sinnoh.png'),
  'Cool Great (Sinnoh)': require('./ribbons/cool-great-sinnoh.png'),
  'Cool Ultra (Sinnoh)': require('./ribbons/cool-ultra-sinnoh.png'),
  'Cool Master (Sinnoh)': require('./ribbons/cool-master-sinnoh.png'),
  'Beauty (Sinnoh)': require('./ribbons/beauty-sinnoh.png'),
  'Beauty Great (Sinnoh)': require('./ribbons/beauty-great-sinnoh.png'),
  'Beauty Ultra (Sinnoh)': require('./ribbons/beauty-ultra-sinnoh.png'),
  'Beauty Master (Sinnoh)': require('./ribbons/beauty-master-sinnoh.png'),
  'Cute (Sinnoh)': require('./ribbons/cute-sinnoh.png'),
  'Cute Great (Sinnoh)': require('./ribbons/cute-great-sinnoh.png'),
  'Cute Ultra (Sinnoh)': require('./ribbons/cute-ultra-sinnoh.png'),
  'Cute Master (Sinnoh)': require('./ribbons/cute-master-sinnoh.png'),
  'Smart (Sinnoh)': require('./ribbons/smart-sinnoh.png'),
  'Smart Great (Sinnoh)': require('./ribbons/smart-great-sinnoh.png'),
  'Smart Ultra (Sinnoh)': require('./ribbons/smart-ultra-sinnoh.png'),
  'Smart Master (Sinnoh)': require('./ribbons/smart-master-sinnoh.png'),
  'Tough (Sinnoh)': require('./ribbons/tough-sinnoh.png'),
  'Tough Great (Sinnoh)': require('./ribbons/tough-great-sinnoh.png'),
  'Tough Ultra (Sinnoh)': require('./ribbons/tough-ultra-sinnoh.png'),
  'Tough Master (Sinnoh)': require('./ribbons/tough-master-sinnoh.png'),
  Winning: require('./ribbons/winning.png'),
  Victory: require('./ribbons/victory.png'),
  Ability: require('./ribbons/ability.png'),
  'Great Ability': require('./ribbons/great-ability.png'),
  'Double Ability': require('./ribbons/double-ability.png'),
  'Multi Ability': require('./ribbons/multi-ability.png'),
  'Pair Ability': require('./ribbons/pair-ability.png'),
  'World Ability': require('./ribbons/world-ability.png'),
};
