// This file was generated by make generate

import {
  AbilityIndex,
  Ball,
  Gender,
  Language,
  MetadataLookup,
  NatureIndex,
  SpeciesLookup,
  Stats16Le,
  TeraTypeWasm,
} from '@pkm-rs-resources/pkg'
import * as lodash from 'lodash'
import Prando from 'prando'
import {
  AllPKMFields,
  generatePersonalityValuePreservingAttributes,
  markingsSixShapesWithColorFromOther,
} from '../../../packages/pokemon-files/src'
import * as types from '../../../packages/pokemon-files/src/util/types'
import { Gen34ContestRibbons, Gen34TowerRibbons } from '../../../packages/pokemon-resources/src'
import * as PkmRs from '../../../pkm_rs/pkg'
import { NationalDex } from '../../consts/NationalDex'
import {
  contestStatsToWasm,
  convertPokeDate,
  convertPokeDateOptional,
  geolocationsFromWasm,
  geolocationsToWasm,
  markingsSixShapesColorsFromWasm,
  markingsSixShapesColorsToWasm,
  statsPreSplitToWasm,
  statsToWasmStats16Le,
  statsToWasmStats8,
  trainerMemoryToWasm,
} from './convert'
import { adjustMovePPBetweenFormats, generateIVs, getAbilityFromNumber, ivsFromDVs } from './util'

export class OhpkmV2 {
  static getName() {
    return 'PK7Wasm'
  }
  format: 'PK7Wasm' = 'PK7Wasm'
  static getBoxSize() {
    return 232
  }
  inner: PkmRs.OhpkmV2

  constructor(arg: ArrayBuffer | AllPKMFields | PkmRs.OhpkmV2) {
    if (arg instanceof ArrayBuffer) {
      let buffer = arg

      this.inner = PkmRs.OhpkmV2.fromBytes(new Uint8Array(buffer))
    } else if (arg instanceof PkmRs.OhpkmV2) {
      this.inner = arg
    } else {
      const other = arg

      this.inner = new PkmRs.OhpkmV2(other.dexNum, other.formeNum)
      let prng: Prando

      if ('personalityValue' in other) {
        prng = new Prando(
          other.trainerName
            .concat((other.personalityValue ?? 0).toString())
            .concat((other.secretID ?? 0).toString())
            .concat(other.trainerID.toString())
        )
      } else if (other.dvs) {
        const { hp, atk, def, spc, spe } = other.dvs

        prng = new Prando(
          other.trainerName
            .concat(`${hp}~${atk}~${def}~${spc}~${spe}`)
            .concat(other.trainerID.toString())
        )
      } else {
        prng = new Prando(other.trainerName.concat(other.trainerID.toString()))
      }

      this.encryptionConstant = other.encryptionConstant ?? 0
      this.heldItemIndex = other.heldItemIndex
      this.trainerName = other.trainerName
      this.trainerGender = other.trainerGender
      this.trainerID = other.trainerID
      this.secretID = other.secretID ?? 0
      this.exp = other.exp

      this.moves = other.moves as [number, number, number, number]
      this.movePP = adjustMovePPBetweenFormats(this, other)
      this.movePPUps = other.movePPUps as [number, number, number, number]
      this.nickname = other.nickname
      this.language = other.language
      this.gameOfOrigin = other.gameOfOrigin
      this.pluginOrigin = other.pluginOrigin

      this.isEgg = other.isEgg ?? false
      this.pokerusByte = other.pokerusByte ?? 0
      this.trainerFriendship = other.trainerFriendship ?? 40

      this.personalityValue =
        other.personalityValue !== undefined
          ? other.personalityValue
          : generatePersonalityValuePreservingAttributes(other)
      this.isFatefulEncounter = other.isFatefulEncounter ?? false

      if (other.format === 'PK1' || other.format === 'PK2') {
        this.abilityNum = 4 // hidden ability for GB mons to mirror virtual console + pokemon bank
        if (other.dexNum === NationalDex.Mew || other.dexNum === NationalDex.Celebi) {
          this.isFatefulEncounter = true
        }
        this.gender =
          other.gender ??
          (other.dvs
            ? this.metadata?.genderFromAtkDv(other.dvs.atk)
            : this.metadata?.genderFromPid(this.personalityValue)) ??
          Gender.Genderless
      } else {
        this.abilityNum = other.abilityNum ?? 0
        this.gender =
          other.gender ?? this.metadata?.genderFromPid(this.personalityValue) ?? Gender.Genderless
      }

      this.nature =
        other.nature !== undefined ? other.nature : NatureIndex.newFromPid(this.personalityValue)
      this.ivs = other.ivs ?? (other.dvs !== undefined ? ivsFromDVs(other.dvs) : generateIVs(prng))

      if (other.evs) {
        this.evs = other.evs
      }
      if (other.evsG12) {
        this.evs
      }

      if (other.contest) {
        this.contest = other.contest
      }

      this.ball = other.ball !== undefined ? other.ball : Ball.Poke
      this.markings = markingsSixShapesWithColorFromOther(other.markings)
      if (other.dvs) {
        this.dvs = other.dvs
      }

      if (other.format === 'PK2' && other.dexNum === NationalDex.Unown && other.dvs) {
        const letterBits = (other.formeNum ?? 0) * 10
        const newDvs = { ...other.dvs }

        newDvs.atk = (newDvs.atk & 0b1001) | (((letterBits >> 6) & 0b11) << 1)
        newDvs.def = (newDvs.def & 0b1001) | (((letterBits >> 4) & 0b11) << 1)
        newDvs.spe = (newDvs.spe & 0b1001) | (((letterBits >> 2) & 0b11) << 1)
        newDvs.spc = (newDvs.spc & 0b1001) | ((letterBits & 0b11) << 1)
        this.dvs = newDvs
      }

      this.metLocationIndex = other.metLocationIndex ?? 0
      this.metLevel = other.metLevel ?? 0

      this.metTimeOfDay = other.metTimeOfDay ?? 0
      this.metLocationIndex = other.metLocationIndex ?? 0
      this.ability =
        getAbilityFromNumber(this.dexNum, this.formeNum, this.abilityNum) ?? this.ability

      this.isShadow = other.isShadow ?? false

      this.encryptionConstant =
        other.encryptionConstant ?? other.personalityValue ?? prng.nextInt(0, 0xffffffff)

      if (other.metDate) {
        this.metDate = other.metDate
      } else {
        const now = new Date()

        this.metDate = {
          month: now.getMonth() + 1,
          day: now.getDate(),
          year: now.getFullYear(),
        }
      }

      // Gen 4+
      this.isNicknamed = other.isNicknamed ?? true
      this.eggDate = other.eggDate
      this.eggLocationIndex = other.eggLocationIndex

      this.encounterType = other.encounterType

      this.shinyLeaves = other.shinyLeaves
      this.performance = other.performance

      // Gen 5+
      this.pokeStarFame = other.pokeStarFame
      this.isNsPokemon = !!other.isNsPokemon

      // Gen 6+
      this.contestMemoryCount = other.contestMemoryCount ?? 0
      this.battleMemoryCount = other.battleMemoryCount ?? 0
      this.relearnMoves = other.relearnMoves ?? [0, 0, 0, 0]
      this.handlerName = other.handlerName ?? ''
      this.handlerGender = other.handlerGender ?? false
      this.isCurrentHandler = other.isCurrentHandler ?? false
      this.handlerFriendship = other.handlerFriendship ?? 0

      if ('ribbons' in other) {
        const contestRibbons = lodash.intersection(other.ribbons, Gen34ContestRibbons)

        this.contestMemoryCount = Math.max(contestRibbons.length, this.contestMemoryCount)
        const battleRibbons = lodash.intersection(other.ribbons, Gen34TowerRibbons)

        this.battleMemoryCount = Math.max(battleRibbons.length, this.battleMemoryCount)
        // this.ribbons = other.ribbons ?? []
      }

      if (other.handlerMemory) {
        this.handlerMemory = other.handlerMemory
      }
      if (other.trainerMemory) {
        this.trainerMemory = other.trainerMemory
      }

      // if (this.contestMemoryCount) {
      //   this.ribbons.push('Contest Memory')
      // }
      // if (this.battleMemoryCount) {
      //   this.ribbons.push('Battle Memory')
      // }

      this.handlerAffection = other.handlerAffection ?? 0
      this.superTrainingFlags = other.superTrainingFlags ?? 0
      this.superTrainingDistFlags = other.superTrainingDistFlags ?? 0
      this.secretSuperTrainingUnlocked = other.secretSuperTrainingUnlocked ?? false
      this.secretSuperTrainingComplete = other.secretSuperTrainingComplete ?? false
      this.country = other.country ?? 0
      this.region = other.region ?? 0
      this.consoleRegion = other.consoleRegion ?? 0
      this.formArgument = other.formArgument ?? 0

      if (other.geolocations) {
        this.geolocations = other.geolocations
      }
      this.trainerAffection = other.trainerAffection ?? 0

      this.trainingBagHits = other.trainingBagHits ?? 0
      this.trainingBag = other.trainingBag

      this.fullness = other.fullness ?? 0
      this.enjoyment = other.enjoyment ?? 0

      if (other.hyperTraining) {
        this.hyperTraining = other.hyperTraining
      }

      this.resortEventStatus = other.resortEventStatus ?? 0

      if (other.avs) {
        this.avs = statsToWasmStats16Le(other.avs)
      }
    }
  }

  get encryptionConstant() {
    return this.inner.main_data.encryption_constant
  }
  set encryptionConstant(value: number) {
    this.inner.main_data.encryption_constant = value
  }

  get dexNum() {
    return this.inner.main_data.species_and_forme.nationalDex
  }

  get heldItemIndex() {
    return this.inner.main_data.held_item_index
  }
  set heldItemIndex(value: number) {
    this.inner.main_data.held_item_index = value
  }

  get trainerID() {
    return this.inner.main_data.trainer_id
  }
  set trainerID(value: number) {
    this.inner.main_data.trainer_id = value
  }

  get secretID() {
    return this.inner.main_data.secret_id
  }
  set secretID(value: number) {
    this.inner.main_data.secret_id = value
  }

  get exp() {
    return this.inner.main_data.exp
  }
  set exp(value: number) {
    this.inner.main_data.exp = value
  }

  get ability() {
    return this.inner.main_data.ability_index
  }
  set ability(value: AbilityIndex) {
    this.inner.main_data.ability_index = value
  }

  get abilityNum() {
    return this.inner.main_data.ability_num
  }
  set abilityNum(value: number) {
    this.inner.main_data.ability_num = value
  }

  get markings() {
    return markingsSixShapesColorsFromWasm(this.inner.main_data.markings)
  }
  set markings(value: types.MarkingsSixShapesWithColor) {
    this.inner.main_data.markings = markingsSixShapesColorsToWasm(value)
  }

  get personalityValue() {
    return this.inner.main_data.personality_value
  }
  set personalityValue(value: number) {
    this.inner.main_data.personality_value = value
  }

  get nature() {
    return this.inner.main_data.nature
  }
  set nature(value: NatureIndex) {
    this.inner.main_data.nature = value
  }

  get isFatefulEncounter() {
    return this.inner.main_data.is_fateful_encounter
  }
  set isFatefulEncounter(value: boolean) {
    this.inner.main_data.is_fateful_encounter = value
  }

  get gender() {
    return this.inner.main_data.gender
  }
  set gender(value: number) {
    this.inner.main_data.gender = value
  }

  get formeNum() {
    return this.inner.main_data.species_and_forme.formeIndex
  }

  get evs() {
    return this.inner.main_data.evs
  }
  set evs(value: types.Stats) {
    this.inner.main_data.evs = statsToWasmStats8(value)
  }

  get evsG12() {
    return this.inner.gameboy_data.evs_g12
  }
  set evsG12(value: types.StatsPreSplit) {
    this.inner.gameboy_data.evs_g12 = statsPreSplitToWasm(value)
  }

  get dvs() {
    return this.inner.gameboy_data.dvs
  }
  set dvs(value: types.StatsPreSplit) {
    this.inner.gameboy_data.dvs = statsPreSplitToWasm(value)
  }

  get contest() {
    return this.inner.main_data.contest
  }
  set contest(value: types.ContestStats) {
    this.inner.main_data.contest = contestStatsToWasm(value)
  }

  get resortEventStatus() {
    return this.inner.gen67_data.resort_event_status
  }
  set resortEventStatus(value: number) {
    this.inner.gen67_data.resort_event_status = value
  }

  get avs() {
    return this.inner.gen67_data.avs
  }
  set avs(value: Stats16Le) {
    this.inner.gen67_data.avs = value
  }

  get pokerusByte() {
    return this.inner.main_data.pokerus_byte
  }
  set pokerusByte(value: number) {
    this.inner.main_data.pokerus_byte = value
  }

  get superTrainingFlags() {
    return this.inner.gen67_data.super_training_flags
  }
  set superTrainingFlags(value: number) {
    this.inner.gen67_data.super_training_flags = value
  }

  get contestMemoryCount() {
    return this.inner.main_data.contest_memory_count
  }
  set contestMemoryCount(value: number) {
    this.inner.main_data.contest_memory_count = value
  }

  get battleMemoryCount() {
    return this.inner.main_data.battle_memory_count
  }
  set battleMemoryCount(value: number) {
    this.inner.main_data.battle_memory_count = value
  }

  get superTrainingDistFlags() {
    return this.inner.gen67_data.super_training_dist_flags
  }
  set superTrainingDistFlags(value: number) {
    this.inner.gen67_data.super_training_dist_flags = value
  }

  get formArgument() {
    return this.inner.main_data.form_argument
  }
  set formArgument(value: number) {
    this.inner.main_data.form_argument = value
  }

  get nickname() {
    return this.inner.nickname
  }

  set nickname(value: string) {
    this.inner.nickname = value
  }

  get moves() {
    return Array.from(this.inner.move_indices)
  }
  set moves(value: number[]) {
    this.inner.move_indices = new Uint16Array(value)
  }

  get movePP() {
    return Array.from(this.inner.move_pp)
  }
  set movePP(value: number[]) {
    this.inner.move_pp = new Uint8Array(value)
  }

  get movePPUps() {
    return Array.from(this.inner.move_pp_ups)
  }
  set movePPUps(value: number[]) {
    this.inner.move_pp_ups = new Uint8Array(value)
  }

  get relearnMoves() {
    return Array.from(this.inner.relearn_move_indices)
  }
  set relearnMoves(value: number[]) {
    this.inner.relearn_move_indices = new Uint16Array(value)
  }

  get secretSuperTrainingUnlocked() {
    return this.inner.gen67_data.secret_super_training_unlocked
  }
  set secretSuperTrainingUnlocked(value: boolean) {
    this.inner.gen67_data.secret_super_training_unlocked = value
  }

  get secretSuperTrainingComplete() {
    return this.inner.gen67_data.secret_super_training_complete
  }
  set secretSuperTrainingComplete(value: boolean) {
    this.inner.gen67_data.secret_super_training_complete = value
  }

  get trainingBag() {
    return this.inner.gen67_data.training_bag ?? undefined
  }
  set trainingBag(value: number | undefined) {
    this.inner.gen67_data.training_bag = value ?? 0
  }

  get trainingBagHits() {
    return this.inner.gen67_data.training_bag_hits ?? undefined
  }
  set trainingBagHits(value: number | undefined) {
    this.inner.gen67_data.training_bag_hits = value ?? 0
  }

  get ivs() {
    return this.inner.main_data.ivs
  }
  set ivs(value: types.Stats) {
    this.inner.main_data.ivs = statsToWasmStats8(value)
  }

  get isEgg() {
    return this.inner.main_data.is_egg
  }
  set isEgg(value: boolean) {
    this.inner.main_data.is_egg = value
  }

  get isNicknamed() {
    return this.inner.main_data.is_nicknamed
  }
  set isNicknamed(value: boolean) {
    this.inner.main_data.is_nicknamed = value
  }

  get isShadow() {
    return this.inner.main_data.is_shadow
  }
  set isShadow(value: boolean) {
    this.inner.main_data.is_shadow = value
  }

  get handlerName() {
    return this.inner.handler_name
  }
  set handlerName(value: string) {
    this.inner.handler_name = value
  }

  get handlerGender() {
    return this.inner.main_data.handler_gender
  }
  set handlerGender(value: boolean) {
    this.inner.main_data.handler_gender = value
  }

  get isCurrentHandler() {
    return this.inner.main_data.is_current_handler
  }
  set isCurrentHandler(value: boolean) {
    this.inner.main_data.is_current_handler = value
  }

  get geolocations() {
    return geolocationsFromWasm(this.inner.gen67_data.geolocations)
  }
  set geolocations(value: types.Geolocation[]) {
    this.inner.gen67_data.geolocations = geolocationsToWasm(value)
  }

  get handlerFriendship() {
    return this.inner.main_data.handler_friendship
  }
  set handlerFriendship(value: number) {
    this.inner.main_data.handler_friendship = value
  }

  get handlerAffection() {
    return this.inner.main_data.handler_affection
  }
  set handlerAffection(value: number) {
    this.inner.main_data.handler_affection = value
  }

  get fullness() {
    return this.inner.main_data.fullness
  }
  set fullness(value: number) {
    this.inner.main_data.fullness = value
  }

  get enjoyment() {
    return this.inner.main_data.enjoyment
  }
  set enjoyment(value: number) {
    this.inner.main_data.enjoyment = value
  }

  get trainerName() {
    return this.inner.trainer_name
  }
  set trainerName(value: string) {
    this.inner.trainer_name = value
  }

  get trainerFriendship() {
    return this.inner.main_data.trainer_friendship
  }
  set trainerFriendship(value: number) {
    this.inner.main_data.trainer_friendship = value
  }

  get trainerAffection() {
    return this.inner.main_data.trainer_affection
  }
  set trainerAffection(value: number) {
    this.inner.main_data.trainer_affection = value
  }

  get eggDate() {
    return convertPokeDateOptional(this.inner.egg_date)
  }

  set eggDate(value: types.PKMDate | undefined) {
    if (value) {
      this.inner.egg_date = new PkmRs.PokeDate(value.year, value.month, value.day)
    } else {
      this.inner.egg_date = undefined
    }
  }

  get metDate() {
    return convertPokeDate(this.inner.main_data.met_date)
  }
  set metDate(value: types.PKMDate) {
    this.inner.main_data.met_date = new PkmRs.PokeDate(value.year, value.month, value.day)
  }

  get metTimeOfDay() {
    return this.inner.gameboy_data.met_time_of_day
  }
  set metTimeOfDay(value: number) {
    this.inner.gameboy_data.met_time_of_day = value
  }

  get eggLocationIndex() {
    return this.inner.main_data.egg_location_index ?? undefined
  }
  set eggLocationIndex(value: number | undefined) {
    this.inner.main_data.egg_location_index = value ?? 0
  }

  get metLocationIndex() {
    return this.inner.main_data.met_location_index
  }
  set metLocationIndex(value: number) {
    this.inner.main_data.met_location_index = value
  }

  get ball() {
    return this.inner.main_data.ball
  }
  set ball(value: number) {
    this.inner.main_data.ball = value
  }

  get metLevel() {
    return this.inner.main_data.met_level
  }
  set metLevel(value: number) {
    this.inner.main_data.met_level = value
  }

  get hyperTraining() {
    return this.inner.main_data.hyper_training
  }
  set hyperTraining(value: types.HyperTrainStats) {
    this.inner.main_data.hyper_training = new PkmRs.HyperTraining(
      value.hp,
      value.atk,
      value.def,
      value.spa,
      value.spd,
      value.spe
    )
  }

  get gameOfOrigin() {
    return this.inner.main_data.game_of_origin
  }
  set gameOfOrigin(value: number) {
    this.inner.main_data.game_of_origin = value
  }

  get country() {
    return this.inner.gen67_data.country
  }
  set country(value: number) {
    this.inner.gen67_data.country = value
  }

  get region() {
    return this.inner.gen67_data.region
  }
  set region(value: number) {
    this.inner.gen67_data.region = value
  }

  get consoleRegion() {
    return this.inner.main_data.console_region
  }
  set consoleRegion(value: number) {
    this.inner.main_data.console_region = value
  }

  get language() {
    return this.inner.main_data.language
  }
  set language(value: Language) {
    this.inner.main_data.language = value
  }

  // get ribbons() {
  //   return this.inner.ribbons.map((ribbonName) =>
  //     ribbonName.endsWith('Ribbon') ? ribbonName.substring(0, ribbonName.length - 7) : ribbonName
  //   )
  // }
  // set ribbons(ribbonNames: string[]) {
  //   this.inner.main_data.ribbon_indices = new Uint32Array(
  //     ribbonNames.map((name) => ModernRibbons.indexOf(name)).filter((idx) => idx !== -1)
  //   )
  // }

  get handlerMemory() {
    return this.inner.main_data.handler_memory
  }
  set handlerMemory(value: types.Memory) {
    this.inner.main_data.handler_memory = trainerMemoryToWasm(value)
  }

  get trainerMemory() {
    return this.inner.main_data.trainer_memory
  }
  set trainerMemory(value: types.Memory) {
    this.inner.main_data.trainer_memory = trainerMemoryToWasm(value)
  }

  get trainerGender() {
    return PkmRs.genderToBool(this.inner.main_data.trainer_gender)
  }
  set trainerGender(value: boolean) {
    this.inner.main_data.trainer_gender = PkmRs.genderFromBool(value)
  }

  // Gen 4+
  get encounterType() {
    return this.inner.gen45_data.encounter_type ?? undefined
  }
  set encounterType(value: number | undefined) {
    this.inner.gen45_data.encounter_type = value ?? 0
  }

  get shinyLeaves() {
    return this.inner.gen45_data.shiny_leaves ?? undefined
  }
  set shinyLeaves(value: number | undefined) {
    this.inner.gen45_data.shiny_leaves = value ?? 0
  }

  get performance() {
    return this.inner.gen45_data.performance ?? undefined
  }
  set performance(value: number | undefined) {
    this.inner.gen45_data.performance = value ?? 0
  }

  // Gen 5+
  get pokeStarFame() {
    return this.inner.gen45_data.poke_star_fame ?? undefined
  }
  set pokeStarFame(value: number | undefined) {
    this.inner.gen45_data.poke_star_fame = value ?? 0
  }

  get isNsPokemon() {
    return this.inner.gen45_data.is_ns_pokemon
  }
  set isNsPokemon(value: boolean) {
    this.inner.gen45_data.is_ns_pokemon = value
  }

  get teraTypeOriginal() {
    return this.inner.tera_type_original
  }

  get teraTypeOverride() {
    return this.inner.tera_type_override
  }

  set teraTypeOverride(value: TeraTypeWasm | undefined) {
    this.inner.tera_type_override = value
  }

  get pluginOrigin() {
    return this.inner.plugin_origin
  }
  set pluginOrigin(value: string | undefined) {
    this.inner.plugin_origin = value
  }

  static fromBytes(buffer: ArrayBuffer): OhpkmV2 {
    return new OhpkmV2(buffer)
  }

  public get abilityName() {
    return this.ability.name
  }

  public get heldItemName() {
    return PkmRs.Item.fromIndex(this.heldItemIndex)?.name
  }

  public get ribbonBytes() {
    return this.inner.ribbon_bytes
  }

  public toBytes() {
    return this.inner.toBytes().buffer as ArrayBuffer
  }

  isShiny() {
    return (
      (this.trainerID ^
        this.secretID ^
        (this.personalityValue & 0xffff) ^
        ((this.personalityValue >> 16) & 0xffff)) <
      16
    )
  }

  isSquareShiny() {
    return !(
      this.trainerID ^
      this.secretID ^
      (this.personalityValue & 0xffff) ^
      ((this.personalityValue >> 16) & 0xffff)
    )
  }

  public get metadata() {
    return MetadataLookup(this.dexNum, this.formeNum)
  }

  public get speciesMetadata() {
    return SpeciesLookup(this.dexNum)
  }

  static maxValidMove() {
    return 728
  }

  static maxValidBall() {
    return 26
  }

  static allowedBalls() {
    return []
  }
}

export default OhpkmV2
