const RibbonsImageMap: { [key: string]: string } = {
  'Absent Minded Mark': 'ribbons/absent-minded-mark.png',
  'Kalos Champion': 'ribbons/kalos-champion.png',
  Champion: 'ribbons/champion.png',
  'Sinnoh Champion': 'ribbons/sinnoh-champion.png',
  'Best Friends': 'ribbons/best-friends.png',
  Training: 'ribbons/training.png',
  'Skillful Battler': 'ribbons/skillful-battler.png',
  'Expert Battler': 'ribbons/expert-battler.png',
  Effort: 'ribbons/effort.png',
  Alert: 'ribbons/alert.png',
  Shock: 'ribbons/shock.png',
  Downcast: 'ribbons/downcast.png',
  Careless: 'ribbons/careless.png',
  Relax: 'ribbons/relax.png',
  Snooze: 'ribbons/snooze.png',
  Smile: 'ribbons/smile.png',
  Gorgeous: 'ribbons/gorgeous.png',
  Royal: 'ribbons/royal.png',
  'Gorgeous Royal': 'ribbons/gorgeous-royal.png',
  Artist: 'ribbons/artist.png',
  Footprint: 'ribbons/footprint.png',
  Record: 'ribbons/record.png',
  Legend: 'ribbons/legend.png',
  Country: 'ribbons/country.png',
  National: 'ribbons/national.png',
  Earth: 'ribbons/earth.png',
  World: 'ribbons/world.png',
  Classic: 'ribbons/classic.png',
  Premier: 'ribbons/premier.png',
  Event: 'ribbons/event.png',
  Birthday: 'ribbons/birthday.png',
  Special: 'ribbons/special.png',
  Souvenir: 'ribbons/souvenir.png',
  Wishing: 'ribbons/wishing.png',
  'Battle Champion': 'ribbons/battle-champion.png',
  'Regional Champion': 'ribbons/regional-champion.png',
  'National Champion': 'ribbons/national-champion.png',
  'World Champion': 'ribbons/world-champion.png',
  'Contest Memory': 'ribbons/contest-memory.png',
  'Battle Memory': 'ribbons/battle-memory.png',
  'Contest Memory Gold': 'ribbons/contest-memory-gold.png',
  'Battle Memory Gold': 'ribbons/battle-memory-gold.png',
  'Hoenn Champion': 'ribbons/hoenn-champion.png',
  'Contest Star': 'ribbons/contest-star.png',
  'Coolness Master': 'ribbons/coolness-master.png',
  'Beauty Master': 'ribbons/beauty-master.png',
  'Cuteness Master': 'ribbons/cuteness-master.png',
  'Cleverness Master': 'ribbons/cleverness-master.png',
  'Toughness Master': 'ribbons/toughness-master.png',
  'Alola Champion': 'ribbons/alola-champion.png',
  'Battle Royal Master': 'ribbons/battle-royal-master.png',
  'Battle Tree Great': 'ribbons/battle-tree-great.png',
  'Battle Tree Master': 'ribbons/battle-tree-master.png',
  'Galar Champion': 'ribbons/galar-champion.png',
  'Tower Master': 'ribbons/tower-master.png',
  'Master Rank': 'ribbons/master-rank.png',
  'Lunchtime Mark': 'ribbons/lunchtime-mark.png',
  'Sleepy-Time Mark': 'ribbons/sleepy-time-mark.png',
  'Dusk Mark': 'ribbons/dusk-mark.png',
  'Dawn Mark': 'ribbons/dawn-mark.png',
  'Cloudy Mark': 'ribbons/cloudy-mark.png',
  'Rainy Mark': 'ribbons/rainy-mark.png',
  'Stormy Mark': 'ribbons/stormy-mark.png',
  'Snowy Mark': 'ribbons/snowy-mark.png',
  'Blizzard Mark': 'ribbons/blizzard-mark.png',
  'Dry Mark': 'ribbons/dry-mark.png',
  'Sandstorm Mark': 'ribbons/sandstorm-mark.png',
  'Misty Mark': 'ribbons/misty-mark.png',
  'Destiny Mark': 'ribbons/destiny-mark.png',
  'Fishing Mark': 'ribbons/fishing-mark.png',
  'Curry Mark': 'ribbons/curry-mark.png',
  'Uncommon Mark': 'ribbons/uncommon-mark.png',
  'Rare Mark': 'ribbons/rare-mark.png',
  'Rowdy Mark': 'ribbons/rowdy-mark.png',
  'Absent-Minded Mark': 'ribbons/absent-minded-mark.png',
  'Jittery Mark': 'ribbons/jittery-mark.png',
  'Excited Mark': 'ribbons/excited-mark.png',
  'Charismatic Mark': 'ribbons/charismatic-mark.png',
  'Calmness Mark': 'ribbons/calmness-mark.png',
  'Intense Mark': 'ribbons/intense-mark.png',
  'Zoned-Out Mark': 'ribbons/zoned-out-mark.png',
  'Joyful Mark': 'ribbons/joyful-mark.png',
  'Angry Mark': 'ribbons/angry-mark.png',
  'Smiley Mark': 'ribbons/smiley-mark.png',
  'Teary Mark': 'ribbons/teary-mark.png',
  'Upbeat Mark': 'ribbons/upbeat-mark.png',
  'Peeved Mark': 'ribbons/peeved-mark.png',
  'Intellectual Mark': 'ribbons/intellectual-mark.png',
  'Ferocious Mark': 'ribbons/ferocious-mark.png',
  'Crafty Mark': 'ribbons/crafty-mark.png',
  'Scowling Mark': 'ribbons/scowling-mark.png',
  'Kindly Mark': 'ribbons/kindly-mark.png',
  'Flustered Mark': 'ribbons/flustered-mark.png',
  'Pumped-Up Mark': 'ribbons/pumped-up-mark.png',
  'Zero Energy Mark': 'ribbons/zero-energy-mark.png',
  'Prideful Mark': 'ribbons/prideful-mark.png',
  'Unsure Mark': 'ribbons/unsure-mark.png',
  'Humble Mark': 'ribbons/humble-mark.png',
  'Thorny Mark': 'ribbons/thorny-mark.png',
  'Vigor Mark': 'ribbons/vigor-mark.png',
  'Slump Mark': 'ribbons/slump-mark.png',
  Hisui: 'ribbons/hisui.png',
  'Twinkling Star': 'ribbons/twinkling-star.png',
  'Paldea Champion': 'ribbons/paldea-champion.png',
  'Jumbo Mark': 'ribbons/jumbo-mark.png',
  'Mini Mark': 'ribbons/mini-mark.png',
  'Itemfinder Mark': 'ribbons/itemfinder-mark.png',
  'Partner Mark': 'ribbons/partner-mark.png',
  'Gourmand Mark': 'ribbons/gourmand-mark.png',
  'Once-in-a-Lifetime': 'ribbons/once-in-a-lifetime.png',
  'Alpha Mark': 'ribbons/alpha-mark.png',
  'Mightiest Mark': 'ribbons/mightiest-mark.png',
  'Titan Mark': 'ribbons/titan-mark.png',
  'Cool (Hoenn)': 'ribbons/cool-hoenn.png',
  'Cool Super (Hoenn)': 'ribbons/cool-super-hoenn.png',
  'Cool Hyper (Hoenn)': 'ribbons/cool-hyper-hoenn.png',
  'Cool Master (Hoenn)': 'ribbons/cool-master-hoenn.png',
  'Beauty (Hoenn)': 'ribbons/beauty-hoenn.png',
  'Beauty Super (Hoenn)': 'ribbons/beauty-super-hoenn.png',
  'Beauty Hyper (Hoenn)': 'ribbons/beauty-hyper-hoenn.png',
  'Beauty Master (Hoenn)': 'ribbons/beauty-master-hoenn.png',
  'Cute (Hoenn)': 'ribbons/cute-hoenn.png',
  'Cute Super (Hoenn)': 'ribbons/cute-super-hoenn.png',
  'Cute Hyper (Hoenn)': 'ribbons/cute-hyper-hoenn.png',
  'Cute Master (Hoenn)': 'ribbons/cute-master-hoenn.png',
  'Smart (Hoenn)': 'ribbons/smart-hoenn.png',
  'Smart Super (Hoenn)': 'ribbons/smart-super-hoenn.png',
  'Smart Hyper (Hoenn)': 'ribbons/smart-hyper-hoenn.png',
  'Smart Master (Hoenn)': 'ribbons/smart-master-hoenn.png',
  'Tough (Hoenn)': 'ribbons/tough-hoenn.png',
  'Tough Super (Hoenn)': 'ribbons/tough-super-hoenn.png',
  'Tough Hyper (Hoenn)': 'ribbons/tough-hyper-hoenn.png',
  'Tough Master (Hoenn)': 'ribbons/tough-master-hoenn.png',
  'Cool (Sinnoh)': 'ribbons/cool-sinnoh.png',
  'Cool Great (Sinnoh)': 'ribbons/cool-great-sinnoh.png',
  'Cool Ultra (Sinnoh)': 'ribbons/cool-ultra-sinnoh.png',
  'Cool Master (Sinnoh)': 'ribbons/cool-master-sinnoh.png',
  'Beauty (Sinnoh)': 'ribbons/beauty-sinnoh.png',
  'Beauty Great (Sinnoh)': 'ribbons/beauty-great-sinnoh.png',
  'Beauty Ultra (Sinnoh)': 'ribbons/beauty-ultra-sinnoh.png',
  'Beauty Master (Sinnoh)': 'ribbons/beauty-master-sinnoh.png',
  'Cute (Sinnoh)': 'ribbons/cute-sinnoh.png',
  'Cute Great (Sinnoh)': 'ribbons/cute-great-sinnoh.png',
  'Cute Ultra (Sinnoh)': 'ribbons/cute-ultra-sinnoh.png',
  'Cute Master (Sinnoh)': 'ribbons/cute-master-sinnoh.png',
  'Smart (Sinnoh)': 'ribbons/smart-sinnoh.png',
  'Smart Great (Sinnoh)': 'ribbons/smart-great-sinnoh.png',
  'Smart Ultra (Sinnoh)': 'ribbons/smart-ultra-sinnoh.png',
  'Smart Master (Sinnoh)': 'ribbons/smart-master-sinnoh.png',
  'Tough (Sinnoh)': 'ribbons/tough-sinnoh.png',
  'Tough Great (Sinnoh)': 'ribbons/tough-great-sinnoh.png',
  'Tough Ultra (Sinnoh)': 'ribbons/tough-ultra-sinnoh.png',
  'Tough Master (Sinnoh)': 'ribbons/tough-master-sinnoh.png',
  Winning: 'ribbons/winning.png',
  Victory: 'ribbons/victory.png',
  Ability: 'ribbons/ability.png',
  'Great Ability': 'ribbons/great-ability.png',
  'Double Ability': 'ribbons/double-ability.png',
  'Multi Ability': 'ribbons/multi-ability.png',
  'Pair Ability': 'ribbons/pair-ability.png',
  'World Ability': 'ribbons/world-ability.png',
}

export const getRibbonSpritePath = (ribbon: string): string => {
  return RibbonsImageMap[ribbon]
}
