export const Balls = [
    "",
    "Master Ball",
    "Ultra Ball",
    "Great Ball",
    "Poké Ball",
    "Safari Ball",
    "Net Ball",
    "Dive Ball",
    "Nest Ball",
    "Repeat Ball",
    "Timer Ball",
    "Luxury Ball",
    "Premier Ball",
    "Dusk Ball",
    "Heal Ball",
    "Quick Ball",
    "Cherish Ball",
    "Fast Ball",
    "Level Ball",
    "Lure Ball",
    "Heavy Ball",
    "Love Ball",
    "Friend Ball",
    "Moon Ball",
    "Sport Ball",
    "Dream Ball",
    "Beast Ball",
    "Strange Ball",
    "Poké Ball (Legends)",
    "Great Ball (Legends)",
    "Ultra Ball (Legends)",
    "Feather Ball",
    "Wing Ball",
    "Jet Ball",
    "Heavy Ball (Legends)",
    "Leaden Ball",
    "Gigaton Ball",
    "Origin Ball"
]