export const Natures = [
  "Hardy",
  "Lonely",
  "Brave",
  "Adamant",
  "Naughty",
  "Bold",
  "Docile",
  "Relaxed",
  "Impish",
  "Lax",
  "Timid",
  "Hasty",
  "Serious",
  "Jolly",
  "Naive",
  "Modest",
  "Mild",
  "Quiet",
  "Bashful",
  "Rash",
  "Calm",
  "Gentle",
  "Sassy",
  "Careful",
  "Quirky",
];

const NatureData = [
  {
    name: "Adamant",
    hp: 1,
    atk: 1.1,
    def: 1,
    spa: 0.9,
    spd: 1,
    spe: 1,
    summary: "+Atk, -SpA",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Bashful",
    hp: 1,
    atk: 1,
    def: 1,
    spa: 1,
    spd: 1,
    spe: 1,
    summary: "",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Bold",
    hp: 1,
    atk: 0.9,
    def: 1.1,
    spa: 1,
    spd: 1,
    spe: 1,
    summary: "+Def, -Atk",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Brave",
    hp: 1,
    atk: 1.1,
    def: 1,
    spa: 1,
    spd: 1,
    spe: 0.9,
    summary: "+Atk, -Spe",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Calm",
    hp: 1,
    atk: 0.9,
    def: 1,
    spa: 1,
    spd: 1.1,
    spe: 1,
    summary: "+SpD, -Atk",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Careful",
    hp: 1,
    atk: 1,
    def: 1,
    spa: 0.9,
    spd: 1.1,
    spe: 1,
    summary: "+SpD, -SpA",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Docile",
    hp: 1,
    atk: 1,
    def: 1,
    spa: 1,
    spd: 1,
    spe: 1,
    summary: "",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Gentle",
    hp: 1,
    atk: 1,
    def: 0.9,
    spa: 1,
    spd: 1.1,
    spe: 1,
    summary: "+SpD, -Def",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Hardy",
    hp: 1,
    atk: 1,
    def: 1,
    spa: 1,
    spd: 1,
    spe: 1,
    summary: "",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Hasty",
    hp: 1,
    atk: 1,
    def: 0.9,
    spa: 1,
    spd: 1,
    spe: 1.1,
    summary: "+Spe, -Def",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Impish",
    hp: 1,
    atk: 1,
    def: 1.1,
    spa: 0.9,
    spd: 1,
    spe: 1,
    summary: "+Def, -SpA",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Jolly",
    hp: 1,
    atk: 1,
    def: 1,
    spa: 0.9,
    spd: 1,
    spe: 1.1,
    summary: "+Spe, -SpA",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Lax",
    hp: 1,
    atk: 1,
    def: 1.1,
    spa: 1,
    spd: 0.9,
    spe: 1,
    summary: "+Def, -SpD",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Lonely",
    hp: 1,
    atk: 1.1,
    def: 0.9,
    spa: 1,
    spd: 1,
    spe: 1,
    summary: "+Atk, -Def",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Mild",
    hp: 1,
    atk: 1,
    def: 0.9,
    spa: 1.1,
    spd: 1,
    spe: 1,
    summary: "+SpA, -Def",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Modest",
    hp: 1,
    atk: 0.9,
    def: 1,
    spa: 1.1,
    spd: 1,
    spe: 1,
    summary: "+SpA, -Atk",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Naive",
    hp: 1,
    atk: 1,
    def: 1,
    spa: 1,
    spd: 0.9,
    spe: 1.1,
    summary: "+Spe, -SpD",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Naughty",
    hp: 1,
    atk: 1.1,
    def: 1,
    spa: 1,
    spd: 0.9,
    spe: 1,
    summary: "+Atk, -SpD",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Quiet",
    hp: 1,
    atk: 1,
    def: 1,
    spa: 1.1,
    spd: 1,
    spe: 0.9,
    summary: "+SpA, -Spe",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Quirky",
    hp: 1,
    atk: 1,
    def: 1,
    spa: 1,
    spd: 1,
    spe: 1,
    summary: "",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Rash",
    hp: 1,
    atk: 1,
    def: 1,
    spa: 1.1,
    spd: 0.9,
    spe: 1,
    summary: "+SpA, -SpD",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Relaxed",
    hp: 1,
    atk: 1,
    def: 1.1,
    spa: 1,
    spd: 1,
    spe: 0.9,
    summary: "+Def, -Spe",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Sassy",
    hp: 1,
    atk: 1,
    def: 1,
    spa: 1,
    spd: 1.1,
    spe: 0.9,
    summary: "+SpD, -Spe",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Serious",
    hp: 1,
    atk: 1,
    def: 1,
    spa: 1,
    spd: 1,
    spe: 1,
    summary: "",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
  {
    name: "Timid",
    hp: 1,
    atk: 0.9,
    def: 1,
    spa: 1,
    spd: 1,
    spe: 1.1,
    summary: "+Spe, -Atk",
    genfamily: ["RS", "DP", "BW", "XY"],
  },
];

export const getNatureSummary = (nature: number) => {
  return NatureData.find((n) => n.name === Natures[nature])?.summary;
};
