export const Gen3Ribbons = [
  "Champion",
  "Winning",
  "Victory",
  "Artist",
  "Effort",
  "Battle Champion",
  "Regional Champion",
  "National Champion",
  "Country",
  "National",
  "Earth",
  "World",
];

export const Gen34TowerRibbons = [
  "Winning",
  "Victory",
  "Ability",
  "Great Ability",
  "Double Ability",
  "Multi Ability",
  "Pair Ability",
  "World Ability",
]

export const Gen34ContestRibbons = [
  "Cool (Gen 3)",
  "Cool Super",
  "Cool Hyper",
  "Cool Master (Gen 3)",
  "Beauty (Gen 3)",
  "Beauty Super",
  "Beauty Hyper",
  "Beauty Master (Gen 3)",
  "Cute (Gen 3)",
  "Cute Super",
  "Cute Hyper",
  "Cute Master (Gen 3)",
  "Smart (Gen 3)",
  "Smart Super",
  "Smart Hyper",
  "Smart Master (Gen 3)",
  "Tough (Gen 3)",
  "Tough Super",
  "Tough Hyper",
  "Tough Master (Gen 3)",
  "Cool (Gen 4)",
  "Cool Great",
  "Cool Ultra",
  "Cool Master (Gen 4)",
  "Beauty (Gen 4)",
  "Beauty Great",
  "Beauty Ultra",
  "Beauty Master (Gen 4)",
  "Cute (Gen 4)",
  "Cute Great",
  "Cute Ultra",
  "Cute Master (Gen 4)",
  "Smart (Gen 4)",
  "Smart Great",
  "Smart Ultra",
  "Smart Master (Gen 4)",
  "Tough (Gen 4)",
  "Tough Great",
  "Tough Ultra",
  "Tough Master (Gen 4)",
]

export const Gen4RibbonsPart1 = [
  "Sinnoh Champion",
  "Ability",
  "Great Ability",
  "Double Ability",
  "Multi Ability",
  "Pair Ability",
  "World Ability",
  "Alert",
  "Shock",
  "Downcast",
  "Careless",
  "Relax",
  "Snooze",
  "Smile",
  "Gorgeous",
  "Royal",
  "Gorgeous Royal",
  "Footprint",
  "Record",
  "Event",
  "Legend",
  "World Champion",
  "Birthday",
  "Special",
  "Souvenir",
  "Wishing",
  "Classic",
  "Premier",
];
export const Gen4RibbonsPart2 = [
  "Cool (Gen 3)",
  "Cool Super",
  "Cool Hyper",
  "Cool Master",
  "Beauty (Gen 3)",
  "Beauty Super",
  "Beauty Hyper",
  "Beauty Master",
  "Cute (Gen 3)",
  "Cute Super",
  "Cute Hyper",
  "Cute Master",
  "Smart (Gen 3)",
  "Smart Super",
  "Smart Hyper",
  "Smart Master",
  "Tough (Gen 3)",
  "Tough Super",
  "Tough Hyper",
  "Tough Master",
  "Champion",
  "Winning",
  "Victory",
  "Artist",
  "Effort",
  "Battle Champion",
  "Regional Champion",
  "National Champion",
  "Country",
  "National",
  "Earth",
  "World",
];

export const Gen4RibbonsPart3 = [
  "Cool (Gen 4)",
  "Cool Great",
  "Cool Ultra",
  "Cool Master",
  "Beauty (Gen 4)",
  "Beauty Great",
  "Beauty Ultra",
  "Beauty Master",
  "Cute (Gen 4)",
  "Cute Great",
  "Cute Ultra",
  "Cute Master",
  "Smart (Gen 4)",
  "Smart Great",
  "Smart Ultra",
  "Smart Master",
  "Tough (Gen 4)",
  "Tough Great",
  "Tough Ultra",
  "Tough Master",
];

export const Gen9Ribbons = [
  "Kalos Champion",
  "Champion",
  "Sinnoh Champion",
  "Best Friends",
  "Training",
  "Skillful Battler",
  "Expert Battler",
  "Effort",
  "Alert",
  "Shock",
  "Downcast",
  "Careless",
  "Relax",
  "Snooze",
  "Smile",
  "Gorgeous",
  "Royal",
  "Gorgeous Royal",
  "Artist",
  "Footprint",
  "Record",
  "Legend",
  "Country",
  "National",
  "Earth",
  "World",
  "Classic",
  "Premier",
  "Event",
  "Birthday",
  "Special",
  "Souvenir",
  "Wishing",
  "Battle Champion",
  "Regional Champion",
  "National Champion",
  "World Champion",
  "Contest Memory",
  "Battle Memory",
  "Hoenn Champion",
  "Contest Star",
  "Coolness Master",
  "Beauty Master",
  "Cuteness Master",
  "Cleverness Master",
  "Toughness Master",
  "Alola Champion",
  "Battle Royal Champion",
  "Battle Tree Great",
  "Battle Tree Master",
  "Galar Champion",
  "Tower Master",
  "Master Rank",
  "Lunchtime Mark",
  "Sleepy-Time Mark",
  "Dusk Mark",
  "Dawn Mark",
  "Cloudy Mark",
  "Rainy Mark",
  "Stormy Mark",
  "Snowy Mark",
  "Blizzard Mark",
  "Dry Mark",
  "Sandstorm Mark",
  "Misty Mark",
  "Destiny Mark",
  "Fishing Mark",
  "Curry Mark",
  "Uncommon Mark",
  "Rare Mark",
  "Rowdy Mark",
  "Absent-Minded Mark",
  "Jittery Mark",
  "Excited Mark",
  "Charismatic Mark",
  "Calmness Mark",
  "Intense Mark",
  "Zoned-Out Mark",
  "Joyful Mark",
  "Angry Mark",
  "Smiley Mark",
  "Teary Mark",
  "Upbeat Mark",
  "Peeved Mark",
  "Intellectual Mark",
  "Ferocious Mark",
  "Crafty Mark",
  "Scowling Mark",
  "Kindly Mark",
  "Flustered Mark",
  "Pumped-Up Mark",
  "Zero Energy Mark",
  "Prideful Mark",
  "Unsure Mark",
  "Humble Mark",
  "Thorny Mark",
  "Vigor Mark",
  "Slump Mark",
  "Hisui",
  "Twinkling Star",
  "Paldea Champion",
  "Jumbo Mark",
  "Mini Mark",
  "Itemfinder Mark",
  "Partner Mark",
  "Gourmand Mark",
  "Once-in-a-Lifetime",
  "Alpha Mark",
  "Mightiest Mark",
  "Titan Mark",
];
export const Gen9RibbonsPart1 = [
  "Kalos Champion",
  "Champion",
  "Sinnoh Champion",
  "Best Friends",
  "Training",
  "Skillful Battler",
  "Expert Battler",
  "Effort",
  "Alert",
  "Shock",
  "Downcast",
  "Careless",
  "Relax",
  "Snooze",
  "Smile",
  "Gorgeous",
  "Royal",
  "Gorgeous Royal",
  "Artist",
  "Footprint",
  "Record",
  "Legend",
  "Country",
  "National",
  "Earth",
  "World",
  "Classic",
  "Premier",
  "Event",
  "Birthday",
  "Special",
  "Souvenir",
  "Wishing",
  "Battle Champion",
  "Regional Champion",
  "National Champion",
  "World Champion",
  "Contest Memory",
  "Battle Memory",
  "Hoenn Champion",
  "Contest Star",
  "Coolness Master",
  "Beauty Master",
  "Cuteness Master",
  "Cleverness Master",
  "Toughness Master",
  "Alola Champion",
  "Battle Royal Champion",
  "Battle Tree Great",
  "Battle Tree Master",
  "Galar Champion",
  "Tower Master",
  "Master Rank",
  "Lunchtime Mark",
  "Sleepy-Time Mark",
  "Dusk Mark",
  "Dawn Mark",
  "Cloudy Mark",
  "Rainy Mark",
  "Stormy Mark",
  "Snowy Mark",
  "Blizzard Mark",
  "Dry Mark",
  "Sandstorm Mark",
];
export const Gen9RibbonsPart2 = [
  "Misty Mark",
  "Destiny Mark",
  "Fishing Mark",
  "Curry Mark",
  "Uncommon Mark",
  "Rare Mark",
  "Rowdy Mark",
  "Absent-Minded Mark",
  "Jittery Mark",
  "Excited Mark",
  "Charismatic Mark",
  "Calmness Mark",
  "Intense Mark",
  "Zoned-Out Mark",
  "Joyful Mark",
  "Angry Mark",
  "Smiley Mark",
  "Teary Mark",
  "Upbeat Mark",
  "Peeved Mark",
  "Intellectual Mark",
  "Ferocious Mark",
  "Crafty Mark",
  "Scowling Mark",
  "Kindly Mark",
  "Flustered Mark",
  "Pumped-Up Mark",
  "Zero Energy Mark",
  "Prideful Mark",
  "Unsure Mark",
  "Humble Mark",
  "Thorny Mark",
  "Vigor Mark",
  "Slump Mark",
  "Hisui",
  "Twinkling Star",
  "Paldea Champion",
  "Jumbo Mark",
  "Mini Mark",
  "Itemfinder Mark",
  "Partner Mark",
  "Gourmand Mark",
  "Once-in-a-Lifetime",
  "Alpha Mark",
  "Mightiest Mark",
  "Titan Mark",
];

export const OpenHomeRibbons = Gen34TowerRibbons.concat(Gen34ContestRibbons).concat(Gen9Ribbons)