export const Gen3StandardRibbons = [
  'Champion',
  'Winning',
  'Victory',
  'Artist',
  'Effort',
  'Battle Champion',
  'Regional Champion',
  'National Champion',
  'Country',
  'National',
  'Earth',
  'World',
]

export const Gen3ContestRibbons = [
  'Cool (Hoenn)',
  'Cool Super (Hoenn)',
  'Cool Hyper (Hoenn)',
  'Cool Master (Hoenn)',
  'Beauty (Hoenn)',
  'Beauty Super (Hoenn)',
  'Beauty Hyper (Hoenn)',
  'Beauty Master (Hoenn)',
  'Cute (Hoenn)',
  'Cute Super (Hoenn)',
  'Cute Hyper (Hoenn)',
  'Cute Master (Hoenn)',
  'Smart (Hoenn)',
  'Smart Super (Hoenn)',
  'Smart Hyper (Hoenn)',
  'Smart Master (Hoenn)',
  'Tough (Hoenn)',
  'Tough Super (Hoenn)',
  'Tough Hyper (Hoenn)',
  'Tough Master (Hoenn)',
]

export const Gen34TowerRibbons = [
  'Winning',
  'Victory',
  'Ability',
  'Great Ability',
  'Double Ability',
  'Multi Ability',
  'Pair Ability',
  'World Ability',
]

export const Gen34ContestRibbons = [
  'Cool (Hoenn)',
  'Cool Super (Hoenn)',
  'Cool Hyper (Hoenn)',
  'Cool Master (Hoenn)',
  'Beauty (Hoenn)',
  'Beauty Super (Hoenn)',
  'Beauty Hyper (Hoenn)',
  'Beauty Master (Hoenn)',
  'Cute (Hoenn)',
  'Cute Super (Hoenn)',
  'Cute Hyper (Hoenn)',
  'Cute Master (Hoenn)',
  'Smart (Hoenn)',
  'Smart Super (Hoenn)',
  'Smart Hyper (Hoenn)',
  'Smart Master (Hoenn)',
  'Tough (Hoenn)',
  'Tough Super (Hoenn)',
  'Tough Hyper (Hoenn)',
  'Tough Master (Hoenn)',
  'Cool (Sinnoh)',
  'Cool Great (Sinnoh)',
  'Cool Ultra (Sinnoh)',
  'Cool Master (Sinnoh)',
  'Beauty (Sinnoh)',
  'Beauty Great (Sinnoh)',
  'Beauty Ultra (Sinnoh)',
  'Beauty Master (Sinnoh)',
  'Cute (Sinnoh)',
  'Cute Great (Sinnoh)',
  'Cute Ultra (Sinnoh)',
  'Cute Master (Sinnoh)',
  'Smart (Sinnoh)',
  'Smart Great (Sinnoh)',
  'Smart Ultra (Sinnoh)',
  'Smart Master (Sinnoh)',
  'Tough (Sinnoh)',
  'Tough Great (Sinnoh)',
  'Tough Ultra (Sinnoh)',
  'Tough Master (Sinnoh)',
]

export const Gen4RibbonsPart1 = [
  'Sinnoh Champion',
  'Ability',
  'Great Ability',
  'Double Ability',
  'Multi Ability',
  'Pair Ability',
  'World Ability',
  'Alert',
  'Shock',
  'Downcast',
  'Careless',
  'Relax',
  'Snooze',
  'Smile',
  'Gorgeous',
  'Royal',
  'Gorgeous Royal',
  'Footprint',
  'Record',
  'Event',
  'Legend',
  'World Champion',
  'Birthday',
  'Special',
  'Souvenir',
  'Wishing',
  'Classic',
  'Premier',
]
export const Gen4RibbonsPart2 = [
  'Cool (Hoenn)',
  'Cool Super (Hoenn)',
  'Cool Hyper (Hoenn)',
  'Cool Master (Hoenn)',
  'Beauty (Hoenn)',
  'Beauty Super (Hoenn)',
  'Beauty Hyper (Hoenn)',
  'Beauty Master (Hoenn)',
  'Cute (Hoenn)',
  'Cute Super (Hoenn)',
  'Cute Hyper (Hoenn)',
  'Cute Master (Hoenn)',
  'Smart (Hoenn)',
  'Smart Super (Hoenn)',
  'Smart Hyper (Hoenn)',
  'Smart Master (Hoenn)',
  'Tough (Hoenn)',
  'Tough Super (Hoenn)',
  'Tough Hyper (Hoenn)',
  'Tough Master (Hoenn)',
  'Champion',
  'Winning',
  'Victory',
  'Artist',
  'Effort',
  'Battle Champion',
  'Regional Champion',
  'National Champion',
  'Country',
  'National',
  'Earth',
  'World',
]

export const Gen4RibbonsPart3 = [
  'Cool (Sinnoh)',
  'Cool Great (Sinnoh)',
  'Cool Ultra (Sinnoh)',
  'Cool Master (Sinnoh)',
  'Beauty (Sinnoh)',
  'Beauty Great (Sinnoh)',
  'Beauty Ultra (Sinnoh)',
  'Beauty Master (Sinnoh)',
  'Cute (Sinnoh)',
  'Cute Great (Sinnoh)',
  'Cute Ultra (Sinnoh)',
  'Cute Master (Sinnoh)',
  'Smart (Sinnoh)',
  'Smart Great (Sinnoh)',
  'Smart Ultra (Sinnoh)',
  'Smart Master (Sinnoh)',
  'Tough (Sinnoh)',
  'Tough Great (Sinnoh)',
  'Tough Ultra (Sinnoh)',
  'Tough Master (Sinnoh)',
]

export const Gen9Ribbons = [
  'Kalos Champion',
  'Champion',
  'Sinnoh Champion',
  'Best Friends',
  'Training',
  'Skillful Battler',
  'Expert Battler',
  'Effort',
  'Alert',
  'Shock',
  'Downcast',
  'Careless',
  'Relax',
  'Snooze',
  'Smile',
  'Gorgeous',
  'Royal',
  'Gorgeous Royal',
  'Artist',
  'Footprint',
  'Record',
  'Legend',
  'Country',
  'National',
  'Earth',
  'World',
  'Classic',
  'Premier',
  'Event',
  'Birthday',
  'Special',
  'Souvenir',
  'Wishing',
  'Battle Champion',
  'Regional Champion',
  'National Champion',
  'World Champion',
  'Contest Memory',
  'Battle Memory',
  'Hoenn Champion',
  'Contest Star',
  'Coolness Master',
  'Beauty Master',
  'Cuteness Master',
  'Cleverness Master',
  'Toughness Master',
  'Alola Champion',
  'Battle Royal Champion',
  'Battle Tree Great',
  'Battle Tree Master',
  'Galar Champion',
  'Tower Master',
  'Master Rank',
  'Lunchtime Mark',
  'Sleepy-Time Mark',
  'Dusk Mark',
  'Dawn Mark',
  'Cloudy Mark',
  'Rainy Mark',
  'Stormy Mark',
  'Snowy Mark',
  'Blizzard Mark',
  'Dry Mark',
  'Sandstorm Mark',
  'Misty Mark',
  'Destiny Mark',
  'Fishing Mark',
  'Curry Mark',
  'Uncommon Mark',
  'Rare Mark',
  'Rowdy Mark',
  'Absent-Minded Mark',
  'Jittery Mark',
  'Excited Mark',
  'Charismatic Mark',
  'Calmness Mark',
  'Intense Mark',
  'Zoned-Out Mark',
  'Joyful Mark',
  'Angry Mark',
  'Smiley Mark',
  'Teary Mark',
  'Upbeat Mark',
  'Peeved Mark',
  'Intellectual Mark',
  'Ferocious Mark',
  'Crafty Mark',
  'Scowling Mark',
  'Kindly Mark',
  'Flustered Mark',
  'Pumped-Up Mark',
  'Zero Energy Mark',
  'Prideful Mark',
  'Unsure Mark',
  'Humble Mark',
  'Thorny Mark',
  'Vigor Mark',
  'Slump Mark',
  'Hisui',
  'Twinkling Star',
  'Paldea Champion',
  'Jumbo Mark',
  'Mini Mark',
  'Itemfinder Mark',
  'Partner Mark',
  'Gourmand Mark',
  'Once-in-a-Lifetime',
  'Alpha Mark',
  'Mightiest Mark',
  'Titan Mark',
]
export const Gen9RibbonsPart1 = [
  'Kalos Champion',
  'Champion',
  'Sinnoh Champion',
  'Best Friends',
  'Training',
  'Skillful Battler',
  'Expert Battler',
  'Effort',
  'Alert',
  'Shock',
  'Downcast',
  'Careless',
  'Relax',
  'Snooze',
  'Smile',
  'Gorgeous',
  'Royal',
  'Gorgeous Royal',
  'Artist',
  'Footprint',
  'Record',
  'Legend',
  'Country',
  'National',
  'Earth',
  'World',
  'Classic',
  'Premier',
  'Event',
  'Birthday',
  'Special',
  'Souvenir',
  'Wishing',
  'Battle Champion',
  'Regional Champion',
  'National Champion',
  'World Champion',
  'Contest Memory',
  'Battle Memory',
  'Hoenn Champion',
  'Contest Star',
  'Coolness Master',
  'Beauty Master',
  'Cuteness Master',
  'Cleverness Master',
  'Toughness Master',
  'Alola Champion',
  'Battle Royal Master',
  'Battle Tree Great',
  'Battle Tree Master',
  'Galar Champion',
  'Tower Master',
  'Master Rank',
  'Lunchtime Mark',
  'Sleepy-Time Mark',
  'Dusk Mark',
  'Dawn Mark',
  'Cloudy Mark',
  'Rainy Mark',
  'Stormy Mark',
  'Snowy Mark',
  'Blizzard Mark',
  'Dry Mark',
  'Sandstorm Mark',
]
export const Gen9RibbonsPart2 = [
  'Misty Mark',
  'Destiny Mark',
  'Fishing Mark',
  'Curry Mark',
  'Uncommon Mark',
  'Rare Mark',
  'Rowdy Mark',
  'Absent-Minded Mark',
  'Jittery Mark',
  'Excited Mark',
  'Charismatic Mark',
  'Calmness Mark',
  'Intense Mark',
  'Zoned-Out Mark',
  'Joyful Mark',
  'Angry Mark',
  'Smiley Mark',
  'Teary Mark',
  'Upbeat Mark',
  'Peeved Mark',
  'Intellectual Mark',
  'Ferocious Mark',
  'Crafty Mark',
  'Scowling Mark',
  'Kindly Mark',
  'Flustered Mark',
  'Pumped-Up Mark',
  'Zero Energy Mark',
  'Prideful Mark',
  'Unsure Mark',
  'Humble Mark',
  'Thorny Mark',
  'Vigor Mark',
  'Slump Mark',
  'Hisui',
  'Twinkling Star',
  'Paldea Champion',
  'Jumbo Mark',
  'Mini Mark',
  'Itemfinder Mark',
  'Partner Mark',
  'Gourmand Mark',
  'Once-in-a-Lifetime',
  'Alpha Mark',
  'Mightiest Mark',
  'Titan Mark',
]

export const OpenHomeRibbons = Gen34TowerRibbons.concat(Gen34ContestRibbons).concat(Gen9Ribbons)

export const RibbonTitles = [
  'the Kalos Champion',
  'the Champion',
  'the Sinnoh Champion',
  'the Great Friend',
  'the Tried and True',
  'the Veteran',
  'the Master',
  'the Once Well-Trained',
  'the Once Vigilant',
  'the Once Cowardly',
  'the Once Shaken',
  'the Once Imperfect',
  'the Once Well-Rested',
  'the Once Sleepy',
  'the Once Cheery',
  'the Gorgeous',
  'the Royal',
  'the Gorgeous Royal',
  'the Model for Paintings',
  'the Strutter',
  'the Record Holder',
  'the Living Legend',
  'the Victor',
  'the Triumphant',
  'the 100× Victorious',
  'the World Conqueror',
  'the Pokémon Fan',
  'the Celebratory',
  'the Festive',
  'the Best Buddy',
  'the Premium',
  'the Cherished',
  'the Wish Granter',
  'the Battle Champion',
  'the Regional Champion',
  'the National Champion',
  'the World Champion',
  'the Treasured Memory',
  'the Exciting Memory',
  'the Hoenn Champion',
  'the Shining Star',
  'the Former Star',
  'the Vintage Beauty',
  'the Former Idol',
  'the Historic Genius',
  'the Formerly Buff',
  'the Alola Champion',
  'the Royal Master',
  'the Tree Victor',
  'the Tree Master',
  'the Galar Champion',
  'the Tower Master',
  'the Rank Master',
  'the Peckish',
  'the Sleepy',
  'the Dozy',
  'the Early Riser',
  'the Cloud Watcher',
  'the Sodden',
  'the Thunderstruck',
  'the Snow Frolicker',
  'the Shivering',
  'the Parched',
  'the Sandswept',
  'the Mist Drifter',
  'the Chosen One',
  'the Catch of the Day',
  'the Curry Connoisseur',
  'the Sociable',
  'the Recluse',
  'the Rowdy',
  'the Spacey',
  'the Anxious',
  'the Giddy',
  'the Radiant',
  'the Serene',
  'the Feisty',
  'the Daydreamer',
  'the Joyful',
  'the Furious',
  'the Beaming',
  'the Teary-Eyed',
  'the Chipper',
  'the Grumpy',
  'the Scholar',
  'the Rampaging',
  'the Opportunist',
  'the Stern',
  'the Kindhearted',
  'the Easily Flustered',
  'the Driven',
  'the Apathetic',
  'the Arrogant',
  'the Reluctant',
  'the Humble',
  'the Pompous',
  'the Lively',
  'the Worn-Out',
  'of the Distant Past',
  'the Twinkling Star',
  'the Paldea Champion',
  'the Great',
  'the Teeny',
  'the Treasure Hunter',
  'the Reliable Partner',
  'the Gourmet',
  'the One-in-a-Million',
  'the Former Alpha',
  'the Unrivaled',
  'the Former Titan',
]
