// This file was generated by make generate
use crate::pkm::traits::IsShiny4096;
use crate::pkm::{Error, Pkm, Result};
use crate::resources::{
    AbilityIndex, Ball, FormeMetadata, GameOfOriginIndex, ModernRibbonSet, MoveSlot, NatureIndex,
    SpeciesAndForme, SpeciesMetadata,
};
use crate::strings::SizedUtf16String;
use crate::substructures::{
    ContestStats, Gender, Geolocations, MarkingsSixShapes, PokeDate, Stats8, Stats16Le,
    TrainerMemory,
};
use crate::util;
use serde::Serialize;
#[cfg(feature = "wasm")]
use wasm_bindgen::prelude::*;

#[cfg_attr(feature = "wasm", wasm_bindgen)]
#[derive(Debug, Default, Serialize, Clone, Copy, IsShiny4096)]
pub struct Pk6 {
    pub encryption_constant: u32,
    pub sanity: u16,
    pub checksum: u16,
    pub species_and_forme: SpeciesAndForme,
    pub held_item_index: u16,
    pub trainer_id: u16,
    pub secret_id: u16,
    pub exp: u32,
    pub ability_index: AbilityIndex,
    pub ability_num: u8,
    pub training_bag_hits: u8,
    pub training_bag: u8,
    pub personality_value: u32,
    pub nature: NatureIndex,
    pub gender: Gender,
    pub evs: Stats8,
    pub contest: ContestStats,
    pub markings: MarkingsSixShapes,
    pub pokerus_byte: u8,
    pub super_training_flags: u32,
    #[cfg_attr(feature = "wasm", wasm_bindgen(skip))]
    pub ribbons: ModernRibbonSet<6>,
    pub contest_memory_count: u8,
    pub battle_memory_count: u8,
    pub super_training_dist_flags: u8,
    pub form_argument: u32,
    #[cfg_attr(feature = "wasm", wasm_bindgen(skip))]
    pub nickname: SizedUtf16String<24>,
    #[cfg_attr(feature = "wasm", wasm_bindgen(skip))]
    pub moves: [MoveSlot; 4],
    #[cfg_attr(feature = "wasm", wasm_bindgen(skip))]
    pub move_pp: [u8; 4],
    #[cfg_attr(feature = "wasm", wasm_bindgen(skip))]
    pub move_pp_ups: [u8; 4],
    #[cfg_attr(feature = "wasm", wasm_bindgen(skip))]
    pub relearn_moves: [MoveSlot; 4],
    pub secret_super_training_unlocked: bool,
    pub secret_super_training_complete: bool,
    pub ivs: Stats8,
    pub is_egg: bool,
    pub is_nicknamed: bool,
    #[cfg_attr(feature = "wasm", wasm_bindgen(skip))]
    pub handler_name: SizedUtf16String<24>,
    pub handler_gender: bool,
    pub is_current_handler: bool,
    pub geolocations: Geolocations,
    pub handler_friendship: u8,
    pub handler_affection: u8,
    pub handler_memory: TrainerMemory,
    pub trainer_memory: TrainerMemory,
    pub fullness: u8,
    pub enjoyment: u8,
    #[cfg_attr(feature = "wasm", wasm_bindgen(skip))]
    pub trainer_name: SizedUtf16String<24>,
    pub trainer_friendship: u8,
    pub trainer_affection: u8,
    pub egg_date: Option<PokeDate>,
    pub met_date: PokeDate,
    pub egg_location_index: u16,
    pub met_location_index: u16,
    pub ball: Ball,
    pub met_level: u8,
    pub encounter_type: u8,
    pub game_of_origin: GameOfOriginIndex,
    pub country: u8,
    pub region: u8,
    pub console_region: u8,
    pub language_index: u8,
    pub is_fateful_encounter: bool,
    pub trainer_gender: Gender,
    pub status_condition: u32,
    pub stat_level: u8,
    pub form_argument_remain: u8,
    pub form_argument_elapsed: u8,
    pub current_hp: u16,
    pub stats: Stats16Le,
}

impl Pk6 {
    pub fn from_bytes(bytes: &[u8]) -> Result<Self> {
        let size = bytes.len();
        if size < Pk6::BOX_SIZE {
            return Err(Error::ByteLength {
                expected: Pk6::BOX_SIZE,
                received: size,
            });
        }
        // try_into() will always succeed thanks to the length check
        let mon = Pk6 {
            encryption_constant: u32::from_le_bytes(bytes[0..4].try_into().unwrap()),
            sanity: u16::from_le_bytes(bytes[4..6].try_into().unwrap()),
            checksum: u16::from_le_bytes(bytes[6..8].try_into().unwrap()),
            species_and_forme: SpeciesAndForme::new(
                u16::from_le_bytes(bytes[8..10].try_into().unwrap()),
                util::read_uint5_from_bits(bytes[29], 3).into(),
            )?,
            held_item_index: u16::from_le_bytes(bytes[10..12].try_into().unwrap()),
            trainer_id: u16::from_le_bytes(bytes[12..14].try_into().unwrap()),
            secret_id: u16::from_le_bytes(bytes[14..16].try_into().unwrap()),
            exp: u32::from_le_bytes(bytes[16..20].try_into().unwrap()),
            ability_index: AbilityIndex::try_from(bytes[20])?,
            ability_num: bytes[21],
            training_bag_hits: bytes[22],
            training_bag: bytes[23],
            personality_value: u32::from_le_bytes(bytes[24..28].try_into().unwrap()),
            nature: NatureIndex::try_from(bytes[28])?,
            gender: Gender::from_bits_1_2(bytes[29]),
            evs: Stats8::from_bytes(bytes[30..36].try_into().unwrap()),
            contest: ContestStats::from_bytes(bytes[36..42].try_into().unwrap()),
            markings: MarkingsSixShapes::from_byte(bytes[42]),
            pokerus_byte: bytes[43],
            super_training_flags: u32::from_le_bytes(bytes[44..48].try_into().unwrap()),
            ribbons: ModernRibbonSet::from_bytes(bytes[48..54].try_into().unwrap()),
            contest_memory_count: bytes[56],
            battle_memory_count: bytes[57],
            super_training_dist_flags: bytes[58],
            form_argument: u32::from_le_bytes(bytes[60..64].try_into().unwrap()),
            nickname: SizedUtf16String::<24>::from_bytes(bytes[64..88].try_into().unwrap()),
            moves: [
                MoveSlot::from_le_bytes(bytes[90..92].try_into().unwrap()),
                MoveSlot::from_le_bytes(bytes[92..94].try_into().unwrap()),
                MoveSlot::from_le_bytes(bytes[94..96].try_into().unwrap()),
                MoveSlot::from_le_bytes(bytes[96..98].try_into().unwrap()),
            ],
            move_pp: [bytes[98], bytes[99], bytes[100], bytes[101]],
            move_pp_ups: [bytes[102], bytes[103], bytes[104], bytes[105]],
            relearn_moves: [
                MoveSlot::from_le_bytes(bytes[106..108].try_into().unwrap()),
                MoveSlot::from_le_bytes(bytes[108..110].try_into().unwrap()),
                MoveSlot::from_le_bytes(bytes[110..112].try_into().unwrap()),
                MoveSlot::from_le_bytes(bytes[112..114].try_into().unwrap()),
            ],
            secret_super_training_unlocked: util::get_flag(bytes, 114, 1),
            secret_super_training_complete: util::get_flag(bytes, 114, 2),
            ivs: Stats8::from_30_bits(bytes[116..120].try_into().unwrap()),
            is_egg: util::get_flag(bytes, 116, 30),
            is_nicknamed: util::get_flag(bytes, 116, 31),
            handler_name: SizedUtf16String::<24>::from_bytes(bytes[120..144].try_into().unwrap()),
            handler_gender: util::get_flag(bytes, 146, 0),
            is_current_handler: util::get_flag(bytes, 147, 0),
            geolocations: Geolocations::from_bytes(bytes[148..158].try_into().unwrap()),
            handler_friendship: bytes[162],
            handler_affection: bytes[163],
            handler_memory: TrainerMemory {
                intensity: bytes[164],
                memory: bytes[165],
                feeling: bytes[166],
                text_variable: u16::from_le_bytes(bytes[168..170].try_into().unwrap()),
            },
            fullness: bytes[174],
            enjoyment: bytes[175],
            trainer_name: SizedUtf16String::<24>::from_bytes(bytes[176..200].try_into().unwrap()),
            trainer_friendship: bytes[202],
            trainer_affection: bytes[203],
            trainer_memory: TrainerMemory {
                intensity: bytes[204],
                memory: bytes[205],
                text_variable: u16::from_le_bytes(bytes[206..208].try_into().unwrap()),
                feeling: bytes[208],
            },
            egg_date: PokeDate::from_bytes_optional(bytes[209..212].try_into().unwrap()),
            met_date: PokeDate::from_bytes(bytes[212..215].try_into().unwrap()),
            egg_location_index: u16::from_le_bytes(bytes[216..218].try_into().unwrap()),
            met_location_index: u16::from_le_bytes(bytes[218..220].try_into().unwrap()),
            ball: Ball::from(bytes[220]),
            met_level: bytes[221],
            encounter_type: bytes[222],
            game_of_origin: GameOfOriginIndex::from(bytes[223]),
            country: bytes[224],
            region: bytes[225],
            console_region: bytes[226],
            language_index: bytes[227],
            is_fateful_encounter: util::get_flag(bytes, 29, 0),
            trainer_gender: util::get_flag(bytes, 221, 7).into(),
            status_condition: if bytes.len() > Self::BOX_SIZE {
                u32::from_le_bytes(bytes[232..236].try_into().unwrap())
            } else {
                0
            },
            stat_level: if bytes.len() > Self::BOX_SIZE {
                bytes[237]
            } else {
                0
            },
            form_argument_remain: if bytes.len() > Self::BOX_SIZE {
                bytes[238]
            } else {
                0
            },
            form_argument_elapsed: if bytes.len() > Self::BOX_SIZE {
                bytes[239]
            } else {
                0
            },
            current_hp: if bytes.len() > Self::BOX_SIZE {
                u16::from_le_bytes(bytes[240..242].try_into().unwrap())
            } else {
                0
            },
            stats: if bytes.len() > Self::BOX_SIZE {
                Stats16Le::from_bytes(bytes[242..254].try_into().unwrap())
            } else {
                Stats16Le::default()
            },
        };
        Ok(mon)
    }
}

impl Pkm for Pk6 {
    const BOX_SIZE: usize = 232;
    const PARTY_SIZE: usize = 260;

    fn box_size() -> usize {
        Self::BOX_SIZE
    }

    fn party_size() -> usize {
        Self::PARTY_SIZE
    }

    fn from_bytes(bytes: &[u8]) -> Result<Box<Self>> {
        Self::from_bytes(bytes).map(Box::new)
    }

    fn write_box_bytes(&self, bytes: &mut [u8]) -> Result<()> {
        bytes[0..4].copy_from_slice(&self.encryption_constant.to_le_bytes());
        bytes[4..6].copy_from_slice(&self.sanity.to_le_bytes());
        bytes[6..8].copy_from_slice(&self.checksum.to_le_bytes());
        bytes[8..10].copy_from_slice(&self.species_and_forme.get_ndex().to_le_bytes());
        bytes[10..12].copy_from_slice(&self.held_item_index.to_le_bytes());
        bytes[12..14].copy_from_slice(&self.trainer_id.to_le_bytes());
        bytes[14..16].copy_from_slice(&self.secret_id.to_le_bytes());
        bytes[16..20].copy_from_slice(&self.exp.to_le_bytes());
        bytes[20] = self.ability_index.into();
        bytes[21] = self.ability_num;
        bytes[22] = self.training_bag_hits;
        bytes[23] = self.training_bag;
        bytes[24..28].copy_from_slice(&self.personality_value.to_le_bytes());
        bytes[28] = self.nature.to_byte();

        self.gender.set_bits_1_2(&mut bytes[29]);
        util::set_flag(bytes, 29, 0, self.is_fateful_encounter);
        util::write_uint5_to_bits(
            self.species_and_forme.get_forme_index() as u8,
            &mut bytes[29],
            3,
        );

        bytes[30..36].copy_from_slice(&self.evs.to_bytes());
        bytes[36..42].copy_from_slice(&self.contest.to_bytes());
        bytes[42] = self.markings.to_byte();
        bytes[43] = self.pokerus_byte;
        bytes[44..48].copy_from_slice(&self.super_training_flags.to_le_bytes());
        bytes[48..54].copy_from_slice(&self.ribbons.to_bytes());

        // 55 unused

        bytes[56] = self.contest_memory_count;
        bytes[57] = self.battle_memory_count;
        bytes[58] = self.super_training_dist_flags;
        bytes[60..64].copy_from_slice(&self.form_argument.to_le_bytes());
        bytes[64..88].copy_from_slice(&self.nickname);

        bytes[90..92].copy_from_slice(&self.moves[0].to_le_bytes());
        bytes[92..94].copy_from_slice(&self.moves[1].to_le_bytes());
        bytes[94..96].copy_from_slice(&self.moves[2].to_le_bytes());
        bytes[96..98].copy_from_slice(&self.moves[3].to_le_bytes());

        bytes[98] = self.move_pp[0];
        bytes[99] = self.move_pp[1];
        bytes[100] = self.move_pp[2];
        bytes[101] = self.move_pp[3];

        bytes[102] = self.move_pp_ups[0];
        bytes[103] = self.move_pp_ups[1];
        bytes[104] = self.move_pp_ups[2];
        bytes[105] = self.move_pp_ups[3];

        bytes[106..108].copy_from_slice(&self.relearn_moves[0].to_le_bytes());
        bytes[108..110].copy_from_slice(&self.relearn_moves[1].to_le_bytes());
        bytes[110..112].copy_from_slice(&self.relearn_moves[2].to_le_bytes());
        bytes[112..114].copy_from_slice(&self.relearn_moves[3].to_le_bytes());

        util::set_flag(bytes, 114, 1, self.secret_super_training_unlocked);
        util::set_flag(bytes, 114, 2, self.secret_super_training_complete);

        self.ivs.write_30_bits(bytes, 116);
        util::set_flag(bytes, 116, 30, self.is_egg);
        util::set_flag(bytes, 116, 31, self.is_nicknamed);

        bytes[120..132].copy_from_slice(&self.handler_name);
        util::set_flag(bytes, 146, 0, self.handler_gender);
        util::set_flag(bytes, 147, 0, self.is_current_handler);
        bytes[148..158].copy_from_slice(&self.geolocations.to_bytes());

        // 157..161 unused

        bytes[162] = self.handler_friendship;
        bytes[163] = self.handler_affection;
        bytes[164] = self.handler_memory.intensity;
        bytes[165] = self.handler_memory.memory;
        bytes[166] = self.handler_memory.feeling;
        bytes[168..170].copy_from_slice(&self.handler_memory.text_variable.to_le_bytes());

        // 170..173 unused

        bytes[174] = self.fullness;
        bytes[175] = self.enjoyment;
        bytes[176..200].copy_from_slice(&self.trainer_name);
        bytes[202] = self.trainer_friendship;
        bytes[203] = self.trainer_affection;
        bytes[204] = self.trainer_memory.intensity;
        bytes[205] = self.trainer_memory.memory;
        bytes[206..208].copy_from_slice(&self.trainer_memory.text_variable.to_le_bytes());
        bytes[208] = self.trainer_memory.feeling;

        bytes[209..212].copy_from_slice(&PokeDate::to_bytes_optional(self.egg_date));
        bytes[212..215].copy_from_slice(&self.met_date.to_bytes());
        bytes[216..218].copy_from_slice(&self.egg_location_index.to_le_bytes());
        bytes[218..220].copy_from_slice(&self.met_location_index.to_le_bytes());

        bytes[220] = self.ball as u8;
        bytes[221] = self.met_level;
        util::set_flag(bytes, 221, 7, self.trainer_gender.into());
        bytes[222] = self.encounter_type;
        bytes[223] = self.game_of_origin.to_byte();
        bytes[224] = self.country;
        bytes[225] = self.region;
        bytes[226] = self.console_region;
        bytes[227] = self.language_index;

        Ok(())
    }

    fn write_party_bytes(&self, bytes: &mut [u8]) -> Result<()> {
        self.write_box_bytes(bytes)?;
        bytes[232..236].copy_from_slice(&self.status_condition.to_le_bytes());
        bytes[237] = self.stat_level;
        bytes[238] = self.form_argument_remain;
        bytes[239] = self.form_argument_elapsed;
        bytes[240..242].copy_from_slice(&self.current_hp.to_le_bytes());
        bytes[242..254].copy_from_slice(&self.stats.to_bytes());

        Ok(())
    }

    fn to_box_bytes(&self) -> Result<Vec<u8>> {
        let mut bytes = [0; Self::BOX_SIZE];
        self.write_box_bytes(&mut bytes)?;

        Ok(Vec::from(bytes))
    }

    fn to_party_bytes(&self) -> Result<Vec<u8>> {
        let mut bytes = [0; Self::PARTY_SIZE];
        self.write_party_bytes(&mut bytes)?;

        Ok(Vec::from(bytes))
    }

    fn get_species_metadata(&self) -> &'static SpeciesMetadata {
        self.species_and_forme.get_species_metadata()
    }

    fn get_forme_metadata(&self) -> &'static FormeMetadata {
        self.species_and_forme.get_forme_metadata()
    }

    fn calculate_level(&self) -> u8 {
        self.get_species_metadata()
            .level_up_type
            .calculate_level(self.exp)
    }
}
