export const EncounterTypes = [
  'Pal Park/Hatch/Event',
  undefined,
  'Tall Grass',
  undefined,
  'Spear Pillar Encounter',
  'Cave/Hall of Origin',
  undefined,
  'Surfing/Fishing',
  undefined,
  'Building',
  'Great Marsh',
  undefined,
  'Gift Pokémon',
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  'Gift Starter/Pt Starter/Sinjoh Ruins',
]
