import type { MilestoneDefinition, RewardDefinition } from "./types"
import { getRegionDex, NATIONAL_DEX_THRESHOLDS } from "./dexTracker"

export const rewards: Record<string, RewardDefinition> = {
  reward_arceus_event: {
    id: "reward_arceus_event",
    name: "Arceus",
    description: "Event reward template",
    species_id: 493,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_celebi_event: {
    id: "reward_celebi_event",
    name: "Celebi",
    description: "Event reward template",
    species_id: 251,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_darkrai_event: {
    id: "reward_darkrai_event",
    name: "Darkrai",
    description: "Event reward template",
    species_id: 491,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_diancie_event: {
    id: "reward_diancie_event",
    name: "Diancie",
    description: "Event reward template",
    species_id: 719,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_genesect_event: {
    id: "reward_genesect_event",
    name: "Genesect",
    description: "Event reward template",
    species_id: 649,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_hoopa_event: {
    id: "reward_hoopa_event",
    name: "Hoopa",
    description: "Event reward template",
    species_id: 720,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_jirachi_event: {
    id: "reward_jirachi_event",
    name: "Jirachi",
    description: "Event reward template",
    species_id: 385,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_keldeo_event: {
    id: "reward_keldeo_event",
    name: "Keldeo",
    description: "Event reward template",
    species_id: 647,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_magearna_event: {
    id: "reward_magearna_event",
    name: "Magearna",
    description: "Event reward template",
    species_id: 801,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_manaphy_event: {
    id: "reward_manaphy_event",
    name: "Manaphy",
    description: "Event reward template",
    species_id: 490,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_marshadow_event: {
    id: "reward_marshadow_event",
    name: "Marshadow",
    description: "Event reward template",
    species_id: 802,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_meloetta_event: {
    id: "reward_meloetta_event",
    name: "Meloetta",
    description: "Event reward template",
    species_id: 648,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_mew_event: {
    id: "reward_mew_event",
    name: "Mew",
    description: "Event reward template",
    species_id: 151,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_pecharunt_event: {
    id: "reward_pecharunt_event",
    name: "Pecharunt",
    description: "Event reward template",
    species_id: 1025,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_phione_event: {
    id: "reward_phione_event",
    name: "Phione",
    description: "Event reward template",
    species_id: 489,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_shaymin_event: {
    id: "reward_shaymin_event",
    name: "Shaymin",
    description: "Event reward template",
    species_id: 492,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_victini_event: {
    id: "reward_victini_event",
    name: "Victini",
    description: "Event reward template",
    species_id: 494,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_volcanion_event: {
    id: "reward_volcanion_event",
    name: "Volcanion",
    description: "Event reward template",
    species_id: 721,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_zarude_event: {
    id: "reward_zarude_event",
    name: "Zarude",
    description: "Event reward template",
    species_id: 893,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_zeraora_event: {
    id: "reward_zeraora_event",
    name: "Zeraora",
    description: "Event reward template",
    species_id: 807,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_bulbasaur_event: {
    id: "reward_bulbasaur_event",
    name: "Bulbasaur",
    description: "Event reward template",
    species_id: 1,
    is_shiny: true,
    source_tag: "progression_event_reward",
  },
  reward_charmander_event: {
    id: "reward_charmander_event",
    name: "Charmander",
    description: "Event reward template",
    species_id: 4,
    is_shiny: true,
    source_tag: "progression_event_reward",
  },
  reward_eevee_event: {
    id: "reward_eevee_event",
    name: "Eevee",
    description: "Event reward template",
    species_id: 133,
    is_shiny: true,
    source_tag: "progression_event_reward",
  },
  reward_entei_event: {
    id: "reward_entei_event",
    name: "Entei",
    description: "Event reward template",
    species_id: 244,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_gastly_event: {
    id: "reward_gastly_event",
    name: "Gastly",
    description: "Event reward template",
    species_id: 92,
    is_shiny: true,
    source_tag: "progression_event_reward",
  },
  reward_beldum_event: {
    id: "reward_beldum_event",
    name: "Beldum",
    description: "Event reward template",
    species_id: 374,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_gholdengo_event: {
    id: "reward_gholdengo_event",
    name: "Gholdengo",
    description: "Event reward template",
    species_id: 1000,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_giratina_event: {
    id: "reward_giratina_event",
    name: "Giratina",
    description: "Event reward template",
    species_id: 487,
    is_shiny: true,
    source_tag: "progression_event_reward",
  },
  reward_koraidon_event: {
    id: "reward_koraidon_event",
    name: "Koraidon",
    description: "Event reward template",
    species_id: 1007,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_lunala_event: {
    id: "reward_lunala_event",
    name: "Lunala",
    description: "Event reward template",
    species_id: 792,
    is_shiny: true,
    source_tag: "progression_event_reward",
  },
  reward_machamp_event: {
    id: "reward_machamp_event",
    name: "Machamp",
    description: "Event reward template",
    species_id: 68,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_mewtwo_event: {
    id: "reward_mewtwo_event",
    name: "Mewtwo",
    description: "Event reward template",
    species_id: 150,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_necrozma_event: {
    id: "reward_necrozma_event",
    name: "Necrozma",
    description: "Event reward template",
    species_id: 800,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_porygon_event: {
    id: "reward_porygon_event",
    name: "Porygon",
    description: "Event reward template",
    species_id: 137,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_reshiram_event: {
    id: "reward_reshiram_event",
    name: "Reshiram",
    description: "Event reward template",
    species_id: 643,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_zamazenta_event: {
    id: "reward_zamazenta_event",
    name: "Zamazenta",
    description: "Event reward template",
    species_id: 889,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_zacian_event: {
    id: "reward_zacian_event",
    name: "Zacian",
    description: "Event reward template",
    species_id: 888,
    is_shiny: true,
    source_tag: "progression_event_reward",
  },
  reward_onix_event: {
    id: "reward_onix_event",
    name: "Onix",
    description: "Event reward template",
    species_id: 95,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  
}

// Permanent milestone distribution
export const milestones: MilestoneDefinition[] = [
  // Type mastery milestones (progressive)
  {
    id: "milestone_type_psychic_progressive",
    name: "Psychic Type Mastery",
    description: "Progressive milestones for collecting Psychic-type Pokemon",
    kind: "type_count_progressive",
    target_type: "Psychic",
    levels: [
      { target_count: 50, reward_id: "reward_mew_event" },
      { target_count: 100, reward_id: "reward_meloetta_event" },
    ],
    reward_id: "reward_mew_event",
  },
  {
    id: "milestone_type_grass_progressive",
    name: "Grass Type Mastery",
    description: "Progressive milestones for collecting Grass-type Pokemon",
    kind: "type_count_progressive",
    target_type: "Grass",
    levels: [
      { target_count: 75, reward_id: "reward_celebi_event" },
      { target_count: 150, reward_id: "reward_shaymin_event" },
    ],
    reward_id: "reward_celebi_event",
  },
  {
    id: "milestone_type_steel_progressive",
    name: "Steel Type Mastery",
    description: "Progressive milestones for collecting Steel-type Pokemon",
    kind: "type_count_progressive",
    target_type: "Steel",
    levels: [
      { target_count: 50, reward_id: "reward_jirachi_event" },
      { target_count: 100, reward_id: "reward_magearna_event" },
    ],
    reward_id: "reward_jirachi_event",
  },
  {
    id: "milestone_type_water_progressive",
    name: "Water Type Mastery",
    description: "Progressive milestones for collecting Water-type Pokemon",
    kind: "type_count_progressive",
    target_type: "Water",
    levels: [
      { target_count: 75, reward_id: "reward_keldeo_event" },
      { target_count: 150, reward_id: "reward_phione_event" },
      { target_count: 250, reward_id: "reward_manaphy_event" },
    ],
    reward_id: "reward_keldeo_event",
  },
  {
    id: "milestone_type_dark_progressive",
    name: "Dark Type Mastery",
    description: "Progressive milestones for collecting Dark-type Pokemon",
    kind: "type_count_progressive",
    target_type: "Dark",
    levels: [{ target_count: 75, reward_id: "reward_darkrai_event" }],
    reward_id: "reward_darkrai_event",
  },
  {
    id: "milestone_type_bug_progressive",
    name: "Bug Type Mastery",
    description: "Progressive milestones for collecting Bug-type Pokemon",
    kind: "type_count_progressive",
    target_type: "Bug",
    levels: [{ target_count: 150, reward_id: "reward_genesect_event" }],
    reward_id: "reward_genesect_event",
  },
  {
    id: "milestone_type_fire_progressive",
    name: "Fire Type Mastery",
    description: "Progressive milestones for collecting Fire-type Pokemon",
    kind: "type_count_progressive",
    target_type: "Fire",
    levels: [
      { target_count: 75, reward_id: "reward_victini_event" },
      { target_count: 150, reward_id: "reward_volcanion_event" },
    ],
    reward_id: "reward_victini_event",
  },
  {
    id: "milestone_type_rock_progressive",
    name: "Rock Type Mastery",
    description: "Progressive milestones for collecting Rock-type Pokemon",
    kind: "type_count_progressive",
    target_type: "Rock",
    levels: [{ target_count: 75, reward_id: "reward_diancie_event" }],
    reward_id: "reward_diancie_event",
  },
  {
    id: "milestone_type_ghost_progressive",
    name: "Ghost Type Mastery",
    description: "Progressive milestones for collecting Ghost-type Pokemon",
    kind: "type_count_progressive",
    target_type: "Ghost",
    levels: [
      { target_count: 75, reward_id: "reward_hoopa_event" },
      { target_count: 125, reward_id: "reward_pecharunt_event" },
    ],
    reward_id: "reward_hoopa_event",
  },
  {
    id: "milestone_type_electric_progressive",
    name: "Electric Type Mastery",
    description: "Progressive milestones for collecting Electric-type Pokemon",
    kind: "type_count_progressive",
    target_type: "Electric",
    levels: [{ target_count: 100, reward_id: "reward_zeraora_event" }],
    reward_id: "reward_zeraora_event",
  },

  // Regional Dex 100% milestones
  {
    id: "milestone_regional_kanto_100",
    name: "Kanto Pokedex 100%",
    description: `Complete the Kanto regional pokedex (${getRegionDex("kanto").totalSpecies} species)`,
    kind: "regional_dex_100",
    region_id: "kanto",
    reward_id: "reward_porygon_event",
  },
  {
    id: "milestone_regional_johto_100",
    name: "Johto Pokedex 100%",
    description: `Complete the Johto regional pokedex (${getRegionDex("johto").totalSpecies} species)`,
    kind: "regional_dex_100",
    region_id: "johto",
    reward_id: "reward_entei_event",
  },
  {
    id: "milestone_regional_hoenn_100",
    name: "Hoenn Pokedex 100%",
    description: `Complete the Hoenn regional pokedex (${getRegionDex("hoenn").totalSpecies} species)`,
    kind: "regional_dex_100",
    region_id: "hoenn",
    reward_id: "reward_beldum_event",
  },
  {
    id: "milestone_regional_sinnoh_100",
    name: "Sinnoh Pokedex 100%",
    description: `Complete the Sinnoh regional pokedex (${getRegionDex("sinnoh").totalSpecies} species)`,
    kind: "regional_dex_100",
    region_id: "sinnoh",
    reward_id: "reward_koraidon_event",
  },
  {
    id: "milestone_regional_unova_100",
    name: "Unova Pokedex 100%",
    description: `Complete the Unova regional pokedex (${getRegionDex("unova").totalSpecies} species)`,
    kind: "regional_dex_100",
    region_id: "unova",
    reward_id: "reward_reshiram_event",
  },
  {
    id: "milestone_regional_kalos_100",
    name: "Kalos Pokedex 100%",
    description: `Complete the Kalos regional pokedex (${getRegionDex("kalos").totalSpecies} species)`,
    kind: "regional_dex_100",
    region_id: "kalos",
    reward_id: "reward_marshadow_event",
  },
  {
    id: "milestone_regional_alola_100",
    name: "Alola Pokedex 100%",
    description: `Complete the Alola regional pokedex (${getRegionDex("alola").totalSpecies} species)`,
    kind: "regional_dex_100",
    region_id: "alola",
    reward_id: "reward_necrozma_event",
  },
  {
    id: "milestone_regional_galar_100",
    name: "Galar Pokedex 100%",
    description: `Complete the Galar regional pokedex (${getRegionDex("galar").totalSpecies} species)`,
    kind: "regional_dex_100",
    region_id: "galar",
    reward_id: "reward_zarude_event",
  },
  {
    id: "milestone_regional_paldea_100",
    name: "Paldea Pokedex 100%",
    description: `Complete the Paldea regional pokedex (${getRegionDex("paldea").totalSpecies} species)`,
    kind: "regional_dex_100",
    region_id: "paldea",
    reward_id: "reward_gholdengo_event",
  },

  // National Dex progression milestones
  {
    id: "milestone_national_dex_25",
    name: "National Dex 25%",
    description: `Collect ${NATIONAL_DEX_THRESHOLDS.phase_1} unique species`,
    kind: "national_dex_threshold",
    national_threshold: NATIONAL_DEX_THRESHOLDS.phase_1,
    reward_id: "reward_machamp_event",
  },
  {
    id: "milestone_national_dex_50",
    name: "National Dex 50%",
    description: `Collect ${NATIONAL_DEX_THRESHOLDS.phase_2} unique species`,
    kind: "national_dex_threshold",
    national_threshold: NATIONAL_DEX_THRESHOLDS.phase_2,
    reward_id: "reward_mewtwo_event",
  },
  {
    id: "milestone_national_dex_75",
    name: "National Dex 75%",
    description: `Collect ${NATIONAL_DEX_THRESHOLDS.phase_3} unique species`,
    kind: "national_dex_threshold",
    national_threshold: NATIONAL_DEX_THRESHOLDS.phase_3,
    reward_id: "reward_zamazenta_event",
  },
  {
    id: "milestone_national_dex_100",
    name: "National Dex 100%",
    description: "Complete the full National Pokedex with all 1025 unique species",
    kind: "national_dex_threshold",
    national_threshold: NATIONAL_DEX_THRESHOLDS.complete,
    reward_id: "reward_arceus_event",
  },

  // Shiny Collection Milestones
  {
    id: "milestone_shiny_10",
    name: "Shiny Hunter I",
    description: "Have 10 shiny Pokemon in your vault",
    kind: "shiny_count",
    target_count: 10,
    reward_id: "reward_bulbasaur_event",
  },
  {
    id: "milestone_shiny_20",
    name: "Shiny Hunter II",
    description: "Have 20 shiny Pokemon in your vault",
    kind: "shiny_count",
    target_count: 20,
    reward_id: "reward_charmander_event",
  },
  {
    id: "milestone_shiny_30",
    name: "Shiny Hunter III",
    description: "Have 30 shiny Pokemon in your vault",
    kind: "shiny_count",
    target_count: 30,
    reward_id: "reward_gastly_event",
  },
  {
    id: "milestone_shiny_50",
    name: "Shiny Hunter IV",
    description: "Have 50 shiny Pokemon in your vault",
    kind: "shiny_count",
    target_count: 50,
    reward_id: "reward_eevee_event",
  },
  {
    id: "milestone_shiny_100",
    name: "Shiny Hunter V",
    description: "Have 100 shiny Pokemon in your vault",
    kind: "shiny_count",
    target_count: 100,
    reward_id: "reward_lunala_event",
  },
  {
    id: "milestone_shiny_115",
    name: "Shiny Hunter VI",
    description: "Have 115 shiny Pokemon in your vault",
    kind: "shiny_count",
    target_count: 115,
    reward_id: "reward_giratina_event",
  },
  {
    id: "milestone_shiny_130",
    name: "Shiny Hunter VII",
    description: "Have 130 shiny Pokemon in your vault",
    kind: "shiny_count",
    target_count: 130,
    reward_id: "reward_zacian_event",
  },
]

