import type { MilestoneDefinition, RewardDefinition } from "./types"

export const rewards: Record<string, RewardDefinition> = {
  reward_arceus_event: {
    id: "reward_arceus_event",
    name: "Arceus",
    description: "Event reward template",
    species_id: 493,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_celebi_event: {
    id: "reward_celebi_event",
    name: "Celebi",
    description: "Event reward template",
    species_id: 251,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_darkrai_event: {
    id: "reward_darkrai_event",
    name: "Darkrai",
    description: "Event reward template",
    species_id: 491,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_diancie_event: {
    id: "reward_diancie_event",
    name: "Diancie",
    description: "Event reward template",
    species_id: 719,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_genesect_event: {
    id: "reward_genesect_event",
    name: "Genesect",
    description: "Event reward template",
    species_id: 649,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_hoopa_event: {
    id: "reward_hoopa_event",
    name: "Hoopa",
    description: "Event reward template",
    species_id: 720,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_jirachi_event: {
    id: "reward_jirachi_event",
    name: "Jirachi",
    description: "Event reward template",
    species_id: 385,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_keldeo_event: {
    id: "reward_keldeo_event",
    name: "Keldeo",
    description: "Event reward template",
    species_id: 647,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_magearna_event: {
    id: "reward_magearna_event",
    name: "Magearna",
    description: "Event reward template",
    species_id: 801,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_manaphy_event: {
    id: "reward_manaphy_event",
    name: "Manaphy",
    description: "Event reward template",
    species_id: 490,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_marshadow_event: {
    id: "reward_marshadow_event",
    name: "Marshadow",
    description: "Event reward template",
    species_id: 802,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_meloetta_event: {
    id: "reward_meloetta_event",
    name: "Meloetta",
    description: "Event reward template",
    species_id: 648,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_mew_event: {
    id: "reward_mew_event",
    name: "Mew",
    description: "Event reward template",
    species_id: 151,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_pecharunt_event: {
    id: "reward_pecharunt_event",
    name: "Pecharunt",
    description: "Event reward template",
    species_id: 1025,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_phione_event: {
    id: "reward_phione_event",
    name: "Phione",
    description: "Event reward template",
    species_id: 489,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_shaymin_event: {
    id: "reward_shaymin_event",
    name: "Shaymin",
    description: "Event reward template",
    species_id: 492,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_victini_event: {
    id: "reward_victini_event",
    name: "Victini",
    description: "Event reward template",
    species_id: 494,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_volcanion_event: {
    id: "reward_volcanion_event",
    name: "Volcanion",
    description: "Event reward template",
    species_id: 721,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_zarude_event: {
    id: "reward_zarude_event",
    name: "Zarude",
    description: "Event reward template",
    species_id: 893,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_zeraora_event: {
    id: "reward_zeraora_event",
    name: "Zeraora",
    description: "Event reward template",
    species_id: 807,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
}

const kanto_151_species: number[] = [926]

export const milestones: MilestoneDefinition[] = [
  {
    id: "milestone_national_living_151",
    name: "Living Dex 151",
    description: "Have species 1 through 151 present in the vault at the same time",
    kind: "national_living_dex",
    required_species: kanto_151_species,
    reward_id: "reward_victini_event",
  },
  {
    id: "milestone_national_living_493_test",
    name: "Living Dex 493 (Test)",
    description: "Test milestone for Arceus reward output",
    kind: "national_living_dex",
    required_species: kanto_151_species,
    reward_id: "reward_arceus_event",
  },
  {
    id: "milestone_system_smoke_test",
    name: "System Smoke Test",
    description: "Quick milestone to validate progression evaluation and reward grant pipeline",
    kind: "national_living_dex",
    required_species: kanto_151_species,
    reward_id: "reward_celebi_event",
  },
]

