import type { MilestoneDefinition, RewardDefinition } from "./types"
import { getRegionDex, NATIONAL_DEX_THRESHOLDS } from "./dexTracker"

export const rewards: Record<string, RewardDefinition> = {
  reward_arceus_event: {
    id: "reward_arceus_event",
    name: "Arceus",
    description: "Event reward template",
    species_id: 493,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_celebi_event: {
    id: "reward_celebi_event",
    name: "Celebi",
    description: "Event reward template",
    species_id: 251,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_darkrai_event: {
    id: "reward_darkrai_event",
    name: "Darkrai",
    description: "Event reward template",
    species_id: 491,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_diancie_event: {
    id: "reward_diancie_event",
    name: "Diancie",
    description: "Event reward template",
    species_id: 719,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_genesect_event: {
    id: "reward_genesect_event",
    name: "Genesect",
    description: "Event reward template",
    species_id: 649,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_hoopa_event: {
    id: "reward_hoopa_event",
    name: "Hoopa",
    description: "Event reward template",
    species_id: 720,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_jirachi_event: {
    id: "reward_jirachi_event",
    name: "Jirachi",
    description: "Event reward template",
    species_id: 385,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_keldeo_event: {
    id: "reward_keldeo_event",
    name: "Keldeo",
    description: "Event reward template",
    species_id: 647,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_magearna_event: {
    id: "reward_magearna_event",
    name: "Magearna",
    description: "Event reward template",
    species_id: 801,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_manaphy_event: {
    id: "reward_manaphy_event",
    name: "Manaphy",
    description: "Event reward template",
    species_id: 490,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_marshadow_event: {
    id: "reward_marshadow_event",
    name: "Marshadow",
    description: "Event reward template",
    species_id: 802,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_meloetta_event: {
    id: "reward_meloetta_event",
    name: "Meloetta",
    description: "Event reward template",
    species_id: 648,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_mew_event: {
    id: "reward_mew_event",
    name: "Mew",
    description: "Event reward template",
    species_id: 151,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_pecharunt_event: {
    id: "reward_pecharunt_event",
    name: "Pecharunt",
    description: "Event reward template",
    species_id: 1025,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_phione_event: {
    id: "reward_phione_event",
    name: "Phione",
    description: "Event reward template",
    species_id: 489,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_shaymin_event: {
    id: "reward_shaymin_event",
    name: "Shaymin",
    description: "Event reward template",
    species_id: 492,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_victini_event: {
    id: "reward_victini_event",
    name: "Victini",
    description: "Event reward template",
    species_id: 494,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_volcanion_event: {
    id: "reward_volcanion_event",
    name: "Volcanion",
    description: "Event reward template",
    species_id: 721,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_zarude_event: {
    id: "reward_zarude_event",
    name: "Zarude",
    description: "Event reward template",
    species_id: 893,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_zeraora_event: {
    id: "reward_zeraora_event",
    name: "Zeraora",
    description: "Event reward template",
    species_id: 807,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_bulbasaur_event: {
    id: "reward_bulbasaur_event",
    name: "Bulbasaur",
    description: "Event reward template",
    species_id: 1,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_charmander_event: {
    id: "reward_charmander_event",
    name: "Charmander",
    description: "Event reward template",
    species_id: 4,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_eevee_event: {
    id: "reward_eevee_event",
    name: "Eevee",
    description: "Event reward template",
    species_id: 133,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_gastly_event: {
    id: "reward_gastly_event",
    name: "Gastly",
    description: "Event reward template",
    species_id: 92,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_lunala_event: {
    id: "reward_lunala_event",
    name: "Lunala",
    description: "Event reward template",
    species_id: 792,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_porygon_event: {
    id: "reward_porygon_event",
    name: "Porygon",
    description: "Event reward template",
    species_id: 137,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_zacian_event: {
    id: "reward_zacian_event",
    name: "Zacian",
    description: "Event reward template",
    species_id: 888,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  reward_onix_event: {
    id: "reward_onix_event",
    name: "Onix",
    description: "Event reward template",
    species_id: 95,
    is_shiny: false,
    source_tag: "progression_event_reward",
  },
  
}

// Regional dex completion milestones
// These are triggered when a region's pokedex reaches 100% completion
export const milestones: MilestoneDefinition[] = [
  // Regional Dex 100% milestones
  {
    id: "milestone_regional_kanto_100",
    name: "Kanto Pokedex 100%",
    description: `Complete the Kanto regional pokedex (${getRegionDex("kanto").totalSpecies} species)`,
    kind: "regional_dex_100",
    region_id: "kanto",
    reward_id: "reward_mew_event",
  },
  {
    id: "milestone_regional_johto_100",
    name: "Johto Pokedex 100%",
    description: `Complete the Johto regional pokedex (${getRegionDex("johto").totalSpecies} species)`,
    kind: "regional_dex_100",
    region_id: "johto",
    reward_id: "reward_celebi_event",
  },
  {
    id: "milestone_regional_hoenn_100",
    name: "Hoenn Pokedex 100%",
    description: `Complete the Hoenn regional pokedex (${getRegionDex("hoenn").totalSpecies} species)`,
    kind: "regional_dex_100",
    region_id: "hoenn",
    reward_id: "reward_jirachi_event",
  },
  {
    id: "milestone_regional_sinnoh_100",
    name: "Sinnoh Pokedex 100%",
    description: `Complete the Sinnoh regional pokedex (${getRegionDex("sinnoh").totalSpecies} species)`,
    kind: "regional_dex_100",
    region_id: "sinnoh",
    reward_id: "reward_arceus_event",
  },
  {
    id: "milestone_regional_unova_100",
    name: "Unova Pokedex 100%",
    description: `Complete the Unova regional pokedex (${getRegionDex("unova").totalSpecies} species)`,
    kind: "regional_dex_100",
    region_id: "unova",
    reward_id: "reward_victini_event",
  },
  {
    id: "milestone_regional_kalos_100",
    name: "Kalos Pokedex 100%",
    description: `Complete the Kalos regional pokedex (${getRegionDex("kalos").totalSpecies} species)`,
    kind: "regional_dex_100",
    region_id: "kalos",
    reward_id: "reward_diancie_event",
  },
  {
    id: "milestone_regional_alola_100",
    name: "Alola Pokedex 100%",
    description: `Complete the Alola regional pokedex (${getRegionDex("alola").totalSpecies} species)`,
    kind: "regional_dex_100",
    region_id: "alola",
    reward_id: "reward_magearna_event",
  },
  {
    id: "milestone_regional_galar_100",
    name: "Galar Pokedex 100%",
    description: `Complete the Galar regional pokedex (${getRegionDex("galar").totalSpecies} species)`,
    kind: "regional_dex_100",
    region_id: "galar",
    reward_id: "reward_zarude_event",
  },
  {
    id: "milestone_regional_hisui_100",
    name: "Hisui Pokedex 100%",
    description: `Complete the Hisui regional pokedex (${getRegionDex("hisui").totalSpecies} species)`,
    kind: "regional_dex_100",
    region_id: "hisui",
    reward_id: "reward_darkrai_event",
  },
  {
    id: "milestone_regional_paldea_100",
    name: "Paldea Pokedex 100%",
    description: `Complete the Paldea regional pokedex (${getRegionDex("paldea").totalSpecies} species)`,
    kind: "regional_dex_100",
    region_id: "paldea",
    reward_id: "reward_pecharunt_event",
  },

  // National Dex progression milestones
  {
    id: "milestone_national_dex_25",
    name: "National Dex 25%",
    description: `Collect ${NATIONAL_DEX_THRESHOLDS.phase_1} unique species`,
    kind: "national_dex_threshold",
    national_threshold: NATIONAL_DEX_THRESHOLDS.phase_1,
    reward_id: "reward_phione_event",
  },
  {
    id: "milestone_national_dex_50",
    name: "National Dex 50%",
    description: `Collect ${NATIONAL_DEX_THRESHOLDS.phase_2} unique species`,
    kind: "national_dex_threshold",
    national_threshold: NATIONAL_DEX_THRESHOLDS.phase_2,
    reward_id: "reward_manaphy_event",
  },
  {
    id: "milestone_national_dex_75",
    name: "National Dex 75%",
    description: `Collect ${NATIONAL_DEX_THRESHOLDS.phase_3} unique species`,
    kind: "national_dex_threshold",
    national_threshold: NATIONAL_DEX_THRESHOLDS.phase_3,
    reward_id: "reward_shaymin_event",
  },
  {
    id: "milestone_national_dex_100",
    name: "National Dex 100%",
    description: "Complete the full National Pokedex with all 1025 unique species",
    kind: "national_dex_threshold",
    national_threshold: NATIONAL_DEX_THRESHOLDS.complete,
    reward_id: "reward_arceus_event",
  },

  // National Living Dex milestones (for testing)
  {
    id: "milestone_national_living_151",
    name: "Living Dex 151",
    description: "Have species 1 through 151 present in the vault at the same time",
    kind: "national_living_dex",
    required_species: Array.from({ length: 151 }, (_, i) => i + 1),
    reward_id: "reward_victini_event",
  },

  // Test milestones for all rewards (require only species 1 - Bulbasaur)
  {
    id: "test_arceus",
    name: "Test: Arceus",
    description: "Test reward: Arceus",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_arceus_event",
  },
  {
    id: "test_celebi",
    name: "Test: Celebi",
    description: "Test reward: Celebi",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_celebi_event",
  },
  {
    id: "test_darkrai",
    name: "Test: Darkrai",
    description: "Test reward: Darkrai",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_darkrai_event",
  },
  {
    id: "test_diancie",
    name: "Test: Diancie",
    description: "Test reward: Diancie",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_diancie_event",
  },
  {
    id: "test_genesect",
    name: "Test: Genesect",
    description: "Test reward: Genesect",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_genesect_event",
  },
  {
    id: "test_hoopa",
    name: "Test: Hoopa",
    description: "Test reward: Hoopa",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_hoopa_event",
  },
  {
    id: "test_jirachi",
    name: "Test: Jirachi",
    description: "Test reward: Jirachi",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_jirachi_event",
  },
  {
    id: "test_keldeo",
    name: "Test: Keldeo",
    description: "Test reward: Keldeo",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_keldeo_event",
  },
  {
    id: "test_magearna",
    name: "Test: Magearna",
    description: "Test reward: Magearna",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_magearna_event",
  },
  {
    id: "test_manaphy",
    name: "Test: Manaphy",
    description: "Test reward: Manaphy",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_manaphy_event",
  },
  {
    id: "test_marshadow",
    name: "Test: Marshadow",
    description: "Test reward: Marshadow",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_marshadow_event",
  },
  {
    id: "test_meloetta",
    name: "Test: Meloetta",
    description: "Test reward: Meloetta",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_meloetta_event",
  },
  {
    id: "test_mew",
    name: "Test: Mew",
    description: "Test reward: Mew",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_mew_event",
  },
  {
    id: "test_pecharunt",
    name: "Test: Pecharunt",
    description: "Test reward: Pecharunt",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_pecharunt_event",
  },
  {
    id: "test_phione",
    name: "Test: Phione",
    description: "Test reward: Phione",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_phione_event",
  },
  {
    id: "test_shaymin",
    name: "Test: Shaymin",
    description: "Test reward: Shaymin",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_shaymin_event",
  },
  {
    id: "test_victini",
    name: "Test: Victini",
    description: "Test reward: Victini",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_victini_event",
  },
  {
    id: "test_volcanion",
    name: "Test: Volcanion",
    description: "Test reward: Volcanion",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_volcanion_event",
  },
  {
    id: "test_zarude",
    name: "Test: Zarude",
    description: "Test reward: Zarude",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_zarude_event",
  },
  {
    id: "test_zeraora",
    name: "Test: Zeraora",
    description: "Test reward: Zeraora",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_zeraora_event",
  },
  {
    id: "test_bulbasaur",
    name: "Test: Bulbasaur",
    description: "Test reward: Bulbasaur",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_bulbasaur_event",
  },
  {
    id: "test_charmander",
    name: "Test: Charmander",
    description: "Test reward: Charmander",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_charmander_event",
  },
  {
    id: "test_eevee",
    name: "Test: Eevee",
    description: "Test reward: Eevee",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_eevee_event",
  },
  {
    id: "test_gastly",
    name: "Test: Gastly",
    description: "Test reward: Gastly",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_gastly_event",
  },
  {
    id: "test_lunala",
    name: "Test: Lunala",
    description: "Test reward: Lunala",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_lunala_event",
  },
  {
    id: "test_porygon",
    name: "Test: Porygon",
    description: "Test reward: Porygon",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_porygon_event",
  },
  {
    id: "test_zacian",
    name: "Test: Zacian",
    description: "Test reward: Zacian",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_zacian_event",
  },
    {
    id: "test_onix",
    name: "Test: Onix",
    description: "Test reward: Onix",
    kind: "national_living_dex",
    required_species: [1],
    reward_id: "reward_onix_event",
  },
  // Type Mastery test milestones (progressive)
  {
    id: "milestone_type_normal_progressive",
    name: "Normal Type Mastery",
    description: "Progressive milestones for collecting Normal-type Pokémon",
    kind: "type_count_progressive",
    target_type: "Normal",
    levels: [
      { target_count: 1, reward_id: "reward_victini_event" },
      { target_count: 5, reward_id: "reward_mew_event" },
      { target_count: 10, reward_id: "reward_celebi_event" },
    ],
    reward_id: "reward_victini_event",
  },
  {
    id: "milestone_type_psychic_progressive",
    name: "Psychic Type Mastery",
    description: "Progressive milestones for collecting Psychic-type Pokémon",
    kind: "type_count_progressive",
    target_type: "Psychic",
    levels: [
      { target_count: 1, reward_id: "reward_celebi_event" },
      { target_count: 5, reward_id: "reward_mew_event" },
      { target_count: 10, reward_id: "reward_jirachi_event" },
    ],
    reward_id: "reward_celebi_event",
  },

  // Shiny Collection Milestones
  {
    id: "milestone_shiny_1",
    name: "First Shiny",
    description: "Have 1 shiny Pokémon in your vault",
    kind: "shiny_count",
    target_count: 1,
    reward_id: "reward_victini_event",
  },
  {
    id: "milestone_shiny_3",
    name: "Shiny Trio",
    description: "Have 3 shiny Pokémon in your vault",
    kind: "shiny_count",
    target_count: 3,
    reward_id: "reward_celebi_event",
  },
  {
    id: "milestone_shiny_5",
    name: "Shiny Squad",
    description: "Have 5 shiny Pokémon in your vault",
    kind: "shiny_count",
    target_count: 5,
    reward_id: "reward_arceus_event",
  },
]

