use std::fmt::Display;
use crate::substructures::FlagSet;
use serde::{Serialize, Serializer};

#[derive(Default, Debug, Clone, Copy)]
pub struct OpenHomeRibbonSet<const N: usize>(FlagSet<N>);

impl<const N: usize> OpenHomeRibbonSet<N> {
    pub const fn from_bytes(bytes: [u8; N]) -> Self {
        Self(FlagSet::from_bytes(bytes))
    }

    pub fn get_ribbons(&self) -> Vec<OpenHomeRibbon> {
        self.0
            .get_indices()
            .into_iter()
            .map(OpenHomeRibbon::from)
            .collect()
    }

    pub const fn to_bytes(self) -> [u8; N] {
        self.0.to_bytes()
    }
}

impl<const N: usize> Serialize for OpenHomeRibbonSet<N> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        self.get_ribbons().serialize(serializer)
    }
}

#[derive(Debug, Serialize, PartialEq, Eq, Clone, Copy)]
pub enum OpenHomeRibbon {
  Winning,
Victory,
Ability,
GreatAbility,
DoubleAbility,
MultiAbility,
PairAbility,
WorldAbility,
CoolHoenn,
CoolSuperHoenn,
CoolHyperHoenn,
CoolMasterHoenn,
BeautyHoenn,
BeautySuperHoenn,
BeautyHyperHoenn,
BeautyMasterHoenn,
CuteHoenn,
CuteSuperHoenn,
CuteHyperHoenn,
CuteMasterHoenn,
SmartHoenn,
SmartSuperHoenn,
SmartHyperHoenn,
SmartMasterHoenn,
ToughHoenn,
ToughSuperHoenn,
ToughHyperHoenn,
ToughMasterHoenn,
KalosChampion,
Champion,
SinnohChampion,
BestFriends,
Training,
SkillfulBattler,
ExpertBattler,
Effort,
Alert,
Shock,
Downcast,
Careless,
Relax,
Snooze,
Smile,
Gorgeous,
Royal,
GorgeousRoyal,
Artist,
Footprint,
Record,
Legend,
Country,
National,
Earth,
World,
Classic,
Premier,
Event,
Birthday,
Special,
Souvenir,
Wishing,
BattleChampion,
RegionalChampion,
NationalChampion,
WorldChampion,
ContestMemory,
BattleMemory,
HoennChampion,
ContestStar,
CoolnessMaster,
BeautyMaster,
CutenessMaster,
ClevernessMaster,
ToughnessMaster,
AlolaChampion,
BattleRoyalChampion,
BattleTreeGreat,
BattleTreeMaster,
GalarChampion,
TowerMaster,
MasterRank,
LunchtimeMark,
SleepyTimeMark,
DuskMark,
DawnMark,
CloudyMark,
RainyMark,
StormyMark,
SnowyMark,
BlizzardMark,
DryMark,
SandstormMark,
MistyMark,
DestinyMark,
FishingMark,
CurryMark,
UncommonMark,
RareMark,
RowdyMark,
AbsentMindedMark,
JitteryMark,
ExcitedMark,
CharismaticMark,
CalmnessMark,
IntenseMark,
ZonedOutMark,
JoyfulMark,
AngryMark,
SmileyMark,
TearyMark,
UpbeatMark,
PeevedMark,
IntellectualMark,
FerociousMark,
CraftyMark,
ScowlingMark,
KindlyMark,
FlusteredMark,
PumpedUpMark,
ZeroEnergyMark,
PridefulMark,
UnsureMark,
HumbleMark,
ThornyMark,
VigorMark,
SlumpMark,
Hisui,
TwinklingStar,
PaldeaChampion,
JumboMark,
MiniMark,
ItemfinderMark,
PartnerMark,
GourmandMark,
OnceInALifetime,
AlphaMark,
MightiestMark,
TitanMark,
Partner
}

impl OpenHomeRibbon {
    fn get_name(&self) -> &'static str {
        match self {
            OpenHomeRibbon::Winning => "Winning Ribbon",
OpenHomeRibbon::Victory => "Victory Ribbon",
OpenHomeRibbon::Ability => "Ability Ribbon",
OpenHomeRibbon::GreatAbility => "Great Ability Ribbon",
OpenHomeRibbon::DoubleAbility => "Double Ability Ribbon",
OpenHomeRibbon::MultiAbility => "Multi Ability Ribbon",
OpenHomeRibbon::PairAbility => "Pair Ability Ribbon",
OpenHomeRibbon::WorldAbility => "World Ability Ribbon",
OpenHomeRibbon::CoolHoenn => "Cool (Hoenn) Ribbon",
OpenHomeRibbon::CoolSuperHoenn => "Cool Super (Hoenn) Ribbon",
OpenHomeRibbon::CoolHyperHoenn => "Cool Hyper (Hoenn) Ribbon",
OpenHomeRibbon::CoolMasterHoenn => "Cool Master (Hoenn) Ribbon",
OpenHomeRibbon::BeautyHoenn => "Beauty (Hoenn) Ribbon",
OpenHomeRibbon::BeautySuperHoenn => "Beauty Super (Hoenn) Ribbon",
OpenHomeRibbon::BeautyHyperHoenn => "Beauty Hyper (Hoenn) Ribbon",
OpenHomeRibbon::BeautyMasterHoenn => "Beauty Master (Hoenn) Ribbon",
OpenHomeRibbon::CuteHoenn => "Cute (Hoenn) Ribbon",
OpenHomeRibbon::CuteSuperHoenn => "Cute Super (Hoenn) Ribbon",
OpenHomeRibbon::CuteHyperHoenn => "Cute Hyper (Hoenn) Ribbon",
OpenHomeRibbon::CuteMasterHoenn => "Cute Master (Hoenn) Ribbon",
OpenHomeRibbon::SmartHoenn => "Smart (Hoenn) Ribbon",
OpenHomeRibbon::SmartSuperHoenn => "Smart Super (Hoenn) Ribbon",
OpenHomeRibbon::SmartHyperHoenn => "Smart Hyper (Hoenn) Ribbon",
OpenHomeRibbon::SmartMasterHoenn => "Smart Master (Hoenn) Ribbon",
OpenHomeRibbon::ToughHoenn => "Tough (Hoenn) Ribbon",
OpenHomeRibbon::ToughSuperHoenn => "Tough Super (Hoenn) Ribbon",
OpenHomeRibbon::ToughHyperHoenn => "Tough Hyper (Hoenn) Ribbon",
OpenHomeRibbon::ToughMasterHoenn => "Tough Master (Hoenn) Ribbon",
OpenHomeRibbon::KalosChampion => "Kalos Champion Ribbon",
OpenHomeRibbon::Champion => "Champion Ribbon",
OpenHomeRibbon::SinnohChampion => "Sinnoh Champion Ribbon",
OpenHomeRibbon::BestFriends => "Best Friends Ribbon",
OpenHomeRibbon::Training => "Training Ribbon",
OpenHomeRibbon::SkillfulBattler => "Skillful Battler Ribbon",
OpenHomeRibbon::ExpertBattler => "Expert Battler Ribbon",
OpenHomeRibbon::Effort => "Effort Ribbon",
OpenHomeRibbon::Alert => "Alert Ribbon",
OpenHomeRibbon::Shock => "Shock Ribbon",
OpenHomeRibbon::Downcast => "Downcast Ribbon",
OpenHomeRibbon::Careless => "Careless Ribbon",
OpenHomeRibbon::Relax => "Relax Ribbon",
OpenHomeRibbon::Snooze => "Snooze Ribbon",
OpenHomeRibbon::Smile => "Smile Ribbon",
OpenHomeRibbon::Gorgeous => "Gorgeous Ribbon",
OpenHomeRibbon::Royal => "Royal Ribbon",
OpenHomeRibbon::GorgeousRoyal => "Gorgeous Royal Ribbon",
OpenHomeRibbon::Artist => "Artist Ribbon",
OpenHomeRibbon::Footprint => "Footprint Ribbon",
OpenHomeRibbon::Record => "Record Ribbon",
OpenHomeRibbon::Legend => "Legend Ribbon",
OpenHomeRibbon::Country => "Country Ribbon",
OpenHomeRibbon::National => "National Ribbon",
OpenHomeRibbon::Earth => "Earth Ribbon",
OpenHomeRibbon::World => "World Ribbon",
OpenHomeRibbon::Classic => "Classic Ribbon",
OpenHomeRibbon::Premier => "Premier Ribbon",
OpenHomeRibbon::Event => "Event Ribbon",
OpenHomeRibbon::Birthday => "Birthday Ribbon",
OpenHomeRibbon::Special => "Special Ribbon",
OpenHomeRibbon::Souvenir => "Souvenir Ribbon",
OpenHomeRibbon::Wishing => "Wishing Ribbon",
OpenHomeRibbon::BattleChampion => "Battle Champion Ribbon",
OpenHomeRibbon::RegionalChampion => "Regional Champion Ribbon",
OpenHomeRibbon::NationalChampion => "National Champion Ribbon",
OpenHomeRibbon::WorldChampion => "World Champion Ribbon",
OpenHomeRibbon::ContestMemory => "Contest Memory Ribbon",
OpenHomeRibbon::BattleMemory => "Battle Memory Ribbon",
OpenHomeRibbon::HoennChampion => "Hoenn Champion Ribbon",
OpenHomeRibbon::ContestStar => "Contest Star Ribbon",
OpenHomeRibbon::CoolnessMaster => "Coolness Master Ribbon",
OpenHomeRibbon::BeautyMaster => "Beauty Master Ribbon",
OpenHomeRibbon::CutenessMaster => "Cuteness Master Ribbon",
OpenHomeRibbon::ClevernessMaster => "Cleverness Master Ribbon",
OpenHomeRibbon::ToughnessMaster => "Toughness Master Ribbon",
OpenHomeRibbon::AlolaChampion => "Alola Champion Ribbon",
OpenHomeRibbon::BattleRoyalChampion => "Battle Royal Champion Ribbon",
OpenHomeRibbon::BattleTreeGreat => "Battle Tree Great Ribbon",
OpenHomeRibbon::BattleTreeMaster => "Battle Tree Master Ribbon",
OpenHomeRibbon::GalarChampion => "Galar Champion Ribbon",
OpenHomeRibbon::TowerMaster => "Tower Master Ribbon",
OpenHomeRibbon::MasterRank => "Master Rank Ribbon",
OpenHomeRibbon::LunchtimeMark => "Lunchtime Mark",
OpenHomeRibbon::SleepyTimeMark => "Sleepy-Time Mark",
OpenHomeRibbon::DuskMark => "Dusk Mark",
OpenHomeRibbon::DawnMark => "Dawn Mark",
OpenHomeRibbon::CloudyMark => "Cloudy Mark",
OpenHomeRibbon::RainyMark => "Rainy Mark",
OpenHomeRibbon::StormyMark => "Stormy Mark",
OpenHomeRibbon::SnowyMark => "Snowy Mark",
OpenHomeRibbon::BlizzardMark => "Blizzard Mark",
OpenHomeRibbon::DryMark => "Dry Mark",
OpenHomeRibbon::SandstormMark => "Sandstorm Mark",
OpenHomeRibbon::MistyMark => "Misty Mark",
OpenHomeRibbon::DestinyMark => "Destiny Mark",
OpenHomeRibbon::FishingMark => "Fishing Mark",
OpenHomeRibbon::CurryMark => "Curry Mark",
OpenHomeRibbon::UncommonMark => "Uncommon Mark",
OpenHomeRibbon::RareMark => "Rare Mark",
OpenHomeRibbon::RowdyMark => "Rowdy Mark",
OpenHomeRibbon::AbsentMindedMark => "Absent-Minded Mark",
OpenHomeRibbon::JitteryMark => "Jittery Mark",
OpenHomeRibbon::ExcitedMark => "Excited Mark",
OpenHomeRibbon::CharismaticMark => "Charismatic Mark",
OpenHomeRibbon::CalmnessMark => "Calmness Mark",
OpenHomeRibbon::IntenseMark => "Intense Mark",
OpenHomeRibbon::ZonedOutMark => "Zoned-Out Mark",
OpenHomeRibbon::JoyfulMark => "Joyful Mark",
OpenHomeRibbon::AngryMark => "Angry Mark",
OpenHomeRibbon::SmileyMark => "Smiley Mark",
OpenHomeRibbon::TearyMark => "Teary Mark",
OpenHomeRibbon::UpbeatMark => "Upbeat Mark",
OpenHomeRibbon::PeevedMark => "Peeved Mark",
OpenHomeRibbon::IntellectualMark => "Intellectual Mark",
OpenHomeRibbon::FerociousMark => "Ferocious Mark",
OpenHomeRibbon::CraftyMark => "Crafty Mark",
OpenHomeRibbon::ScowlingMark => "Scowling Mark",
OpenHomeRibbon::KindlyMark => "Kindly Mark",
OpenHomeRibbon::FlusteredMark => "Flustered Mark",
OpenHomeRibbon::PumpedUpMark => "Pumped-Up Mark",
OpenHomeRibbon::ZeroEnergyMark => "Zero Energy Mark",
OpenHomeRibbon::PridefulMark => "Prideful Mark",
OpenHomeRibbon::UnsureMark => "Unsure Mark",
OpenHomeRibbon::HumbleMark => "Humble Mark",
OpenHomeRibbon::ThornyMark => "Thorny Mark",
OpenHomeRibbon::VigorMark => "Vigor Mark",
OpenHomeRibbon::SlumpMark => "Slump Mark",
OpenHomeRibbon::Hisui => "Hisui Ribbon",
OpenHomeRibbon::TwinklingStar => "Twinkling Star Ribbon",
OpenHomeRibbon::PaldeaChampion => "Paldea Champion Ribbon",
OpenHomeRibbon::JumboMark => "Jumbo Mark",
OpenHomeRibbon::MiniMark => "Mini Mark",
OpenHomeRibbon::ItemfinderMark => "Itemfinder Mark",
OpenHomeRibbon::PartnerMark => "Partner Mark",
OpenHomeRibbon::GourmandMark => "Gourmand Mark",
OpenHomeRibbon::OnceInALifetime => "Once-in-a-Lifetime Ribbon",
OpenHomeRibbon::AlphaMark => "Alpha Mark",
OpenHomeRibbon::MightiestMark => "Mightiest Mark",
OpenHomeRibbon::TitanMark => "Titan Mark",
OpenHomeRibbon::Partner => "Partner Ribbon",
        }
    }
}

impl Display for OpenHomeRibbon {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.get_name())
    }
}
    
impl From<usize> for OpenHomeRibbon {
    fn from(value: usize) -> Self {
        match value {
            0 => OpenHomeRibbon::Winning,
1 => OpenHomeRibbon::Victory,
2 => OpenHomeRibbon::Ability,
3 => OpenHomeRibbon::GreatAbility,
4 => OpenHomeRibbon::DoubleAbility,
5 => OpenHomeRibbon::MultiAbility,
6 => OpenHomeRibbon::PairAbility,
7 => OpenHomeRibbon::WorldAbility,
8 => OpenHomeRibbon::CoolHoenn,
9 => OpenHomeRibbon::CoolSuperHoenn,
10 => OpenHomeRibbon::CoolHyperHoenn,
11 => OpenHomeRibbon::CoolMasterHoenn,
12 => OpenHomeRibbon::BeautyHoenn,
13 => OpenHomeRibbon::BeautySuperHoenn,
14 => OpenHomeRibbon::BeautyHyperHoenn,
15 => OpenHomeRibbon::BeautyMasterHoenn,
16 => OpenHomeRibbon::CuteHoenn,
17 => OpenHomeRibbon::CuteSuperHoenn,
18 => OpenHomeRibbon::CuteHyperHoenn,
19 => OpenHomeRibbon::CuteMasterHoenn,
20 => OpenHomeRibbon::SmartHoenn,
21 => OpenHomeRibbon::SmartSuperHoenn,
22 => OpenHomeRibbon::SmartHyperHoenn,
23 => OpenHomeRibbon::SmartMasterHoenn,
24 => OpenHomeRibbon::ToughHoenn,
25 => OpenHomeRibbon::ToughSuperHoenn,
26 => OpenHomeRibbon::ToughHyperHoenn,
27 => OpenHomeRibbon::ToughMasterHoenn,
28 => OpenHomeRibbon::KalosChampion,
29 => OpenHomeRibbon::Champion,
30 => OpenHomeRibbon::SinnohChampion,
31 => OpenHomeRibbon::BestFriends,
32 => OpenHomeRibbon::Training,
33 => OpenHomeRibbon::SkillfulBattler,
34 => OpenHomeRibbon::ExpertBattler,
35 => OpenHomeRibbon::Effort,
36 => OpenHomeRibbon::Alert,
37 => OpenHomeRibbon::Shock,
38 => OpenHomeRibbon::Downcast,
39 => OpenHomeRibbon::Careless,
40 => OpenHomeRibbon::Relax,
41 => OpenHomeRibbon::Snooze,
42 => OpenHomeRibbon::Smile,
43 => OpenHomeRibbon::Gorgeous,
44 => OpenHomeRibbon::Royal,
45 => OpenHomeRibbon::GorgeousRoyal,
46 => OpenHomeRibbon::Artist,
47 => OpenHomeRibbon::Footprint,
48 => OpenHomeRibbon::Record,
49 => OpenHomeRibbon::Legend,
50 => OpenHomeRibbon::Country,
51 => OpenHomeRibbon::National,
52 => OpenHomeRibbon::Earth,
53 => OpenHomeRibbon::World,
54 => OpenHomeRibbon::Classic,
55 => OpenHomeRibbon::Premier,
56 => OpenHomeRibbon::Event,
57 => OpenHomeRibbon::Birthday,
58 => OpenHomeRibbon::Special,
59 => OpenHomeRibbon::Souvenir,
60 => OpenHomeRibbon::Wishing,
61 => OpenHomeRibbon::BattleChampion,
62 => OpenHomeRibbon::RegionalChampion,
63 => OpenHomeRibbon::NationalChampion,
64 => OpenHomeRibbon::WorldChampion,
65 => OpenHomeRibbon::ContestMemory,
66 => OpenHomeRibbon::BattleMemory,
67 => OpenHomeRibbon::HoennChampion,
68 => OpenHomeRibbon::ContestStar,
69 => OpenHomeRibbon::CoolnessMaster,
70 => OpenHomeRibbon::BeautyMaster,
71 => OpenHomeRibbon::CutenessMaster,
72 => OpenHomeRibbon::ClevernessMaster,
73 => OpenHomeRibbon::ToughnessMaster,
74 => OpenHomeRibbon::AlolaChampion,
75 => OpenHomeRibbon::BattleRoyalChampion,
76 => OpenHomeRibbon::BattleTreeGreat,
77 => OpenHomeRibbon::BattleTreeMaster,
78 => OpenHomeRibbon::GalarChampion,
79 => OpenHomeRibbon::TowerMaster,
80 => OpenHomeRibbon::MasterRank,
81 => OpenHomeRibbon::LunchtimeMark,
82 => OpenHomeRibbon::SleepyTimeMark,
83 => OpenHomeRibbon::DuskMark,
84 => OpenHomeRibbon::DawnMark,
85 => OpenHomeRibbon::CloudyMark,
86 => OpenHomeRibbon::RainyMark,
87 => OpenHomeRibbon::StormyMark,
88 => OpenHomeRibbon::SnowyMark,
89 => OpenHomeRibbon::BlizzardMark,
90 => OpenHomeRibbon::DryMark,
91 => OpenHomeRibbon::SandstormMark,
92 => OpenHomeRibbon::MistyMark,
93 => OpenHomeRibbon::DestinyMark,
94 => OpenHomeRibbon::FishingMark,
95 => OpenHomeRibbon::CurryMark,
96 => OpenHomeRibbon::UncommonMark,
97 => OpenHomeRibbon::RareMark,
98 => OpenHomeRibbon::RowdyMark,
99 => OpenHomeRibbon::AbsentMindedMark,
100 => OpenHomeRibbon::JitteryMark,
101 => OpenHomeRibbon::ExcitedMark,
102 => OpenHomeRibbon::CharismaticMark,
103 => OpenHomeRibbon::CalmnessMark,
104 => OpenHomeRibbon::IntenseMark,
105 => OpenHomeRibbon::ZonedOutMark,
106 => OpenHomeRibbon::JoyfulMark,
107 => OpenHomeRibbon::AngryMark,
108 => OpenHomeRibbon::SmileyMark,
109 => OpenHomeRibbon::TearyMark,
110 => OpenHomeRibbon::UpbeatMark,
111 => OpenHomeRibbon::PeevedMark,
112 => OpenHomeRibbon::IntellectualMark,
113 => OpenHomeRibbon::FerociousMark,
114 => OpenHomeRibbon::CraftyMark,
115 => OpenHomeRibbon::ScowlingMark,
116 => OpenHomeRibbon::KindlyMark,
117 => OpenHomeRibbon::FlusteredMark,
118 => OpenHomeRibbon::PumpedUpMark,
119 => OpenHomeRibbon::ZeroEnergyMark,
120 => OpenHomeRibbon::PridefulMark,
121 => OpenHomeRibbon::UnsureMark,
122 => OpenHomeRibbon::HumbleMark,
123 => OpenHomeRibbon::ThornyMark,
124 => OpenHomeRibbon::VigorMark,
125 => OpenHomeRibbon::SlumpMark,
126 => OpenHomeRibbon::Hisui,
127 => OpenHomeRibbon::TwinklingStar,
128 => OpenHomeRibbon::PaldeaChampion,
129 => OpenHomeRibbon::JumboMark,
130 => OpenHomeRibbon::MiniMark,
131 => OpenHomeRibbon::ItemfinderMark,
132 => OpenHomeRibbon::PartnerMark,
133 => OpenHomeRibbon::GourmandMark,
134 => OpenHomeRibbon::OnceInALifetime,
135 => OpenHomeRibbon::AlphaMark,
136 => OpenHomeRibbon::MightiestMark,
137 => OpenHomeRibbon::TitanMark,
138 => OpenHomeRibbon::Partner,
            _ => panic!("Invalid value for OpenHomeRibbon: {}", value),
        }
    }
}
