pub static GEN3_CFRU_MOVES: [&str; 1002] = [
    "None",
    "Pound",
    "Karate Chop",
    "Double Slap",
    "Comet Punch",
    "Mega Punch",
    "Pay Day",
    "Fire Punch",
    "Ice Punch",
    "Thunder Punch",
    "Scratch",
    "Vise Grip",
    "Guillotine",
    "Razor Wind",
    "Swords Dance",
    "Cut",
    "Gust",
    "Wing Attack",
    "Whirlwind",
    "Fly",
    "Bind",
    "Slam",
    "Vine Whip",
    "Stomp",
    "Double Kick",
    "Mega Kick",
    "Jump Kick",
    "Rolling Kick",
    "Sand Attack",
    "Headbutt",
    "Horn Attack",
    "Fury Attack",
    "Horn Drill",
    "Tackle",
    "Body Slam",
    "Wrap",
    "Take Down",
    "Thrash",
    "Double-Edge",
    "Tail Whip",
    "Poison Sting",
    "Twineedle",
    "Pin Missile",
    "Leer",
    "Bite",
    "Growl",
    "Roar",
    "Sing",
    "Supersonic",
    "Sonic Boom",
    "Disable",
    "Acid",
    "Ember",
    "Flamethrower",
    "Mist",
    "Water Gun",
    "Hydro Pump",
    "Surf",
    "Ice Beam",
    "Blizzard",
    "Psybeam",
    "Bubble Beam",
    "Aurora Beam",
    "Hyper Beam",
    "Peck",
    "Drill Peck",
    "Submission",
    "Low Kick",
    "Counter",
    "Seismic Toss",
    "Strength",
    "Absorb",
    "Mega Drain",
    "Leech Seed",
    "Growth",
    "Razor Leaf",
    "Solar Beam",
    "Poison Powder",
    "Stun Spore",
    "Sleep Powder",
    "Petal Dance",
    "String Shot",
    "Dragon Rage",
    "Fire Spin",
    "Thunder Shock",
    "Thunderbolt",
    "Thunder Wave",
    "Thunder",
    "Rock Throw",
    "Earthquake",
    "Soul Robbery", // RR
    "Dig",
    "Toxic",
    "Confusion",
    "Psychic",
    "Hypnosis",
    "Meditate",
    "Agility",
    "Quick Attack",
    "Rage",
    "Teleport",
    "Night Shade",
    "Mimic",
    "Screech",
    "Double Team",
    "Recover",
    "Harden",
    "Minimize",
    "Smokescreen",
    "Confuse Ray",
    "Withdraw",
    "Defense Curl",
    "Barrier",
    "Light Screen",
    "Haze",
    "Reflect",
    "Focus Energy",
    "Bide",
    "Metronome",
    "Mirror Move",
    "Self-Destruct",
    "Egg Bomb",
    "Lick",
    "Smog",
    "Sludge",
    "Bone Club",
    "Fire Blast",
    "Waterfall",
    "Clamp",
    "Swift",
    "Skull Bash",
    "Spike Cannon",
    "Constrict",
    "Amnesia",
    "Kinesis",
    "Soft-Boiled",
    "High Jump Kick",
    "Glare",
    "Dream Eater",
    "Poison Gas",
    "Barrage",
    "Leech Life",
    "Lovely Kiss",
    "Sky Attack",
    "Transform",
    "Bubble",
    "Dizzy Punch",
    "Spore",
    "Flash",
    "Psywave",
    "Splash",
    "Acid Armor",
    "Crabhammer",
    "Explosion",
    "Fury Swipes",
    "Bonemerang",
    "Rest",
    "Rock Slide",
    "Hyper Fang",
    "Sharpen",
    "Dark Hole",
    "Tri Attack",
    "Super Fang",
    "Slash",
    "Substitute",
    "Struggle",
    "Sketch",
    "Triple Kick",
    "Thief",
    "Spider Web",
    "Mind Reader",
    "Nightmare",
    "Flame Wheel",
    "Snore",
    "Curse",
    "Flail",
    "Conversion 2",
    "Aeroblast",
    "Cotton Spore",
    "Reversal",
    "Spite",
    "Powder Snow",
    "Protect",
    "Mach Punch",
    "Scary Face",
    "Feint Attack",
    "Sweet Kiss",
    "Belly Drum",
    "Sludge Bomb",
    "Mud-Slap",
    "Octazooka",
    "Spikes",
    "Zap Cannon",
    "Foresight",
    "Destiny Bond",
    "Perish Song",
    "Icy Wind",
    "Detect",
    "Bone Rush",
    "Lock-On",
    "Outrage",
    "Sandstorm",
    "Giga Drain",
    "Endure",
    "Charm",
    "Rollout",
    "False Swipe",
    "Swagger",
    "Milk Drink",
    "Spark",
    "Fury Cutter",
    "Steel Wing",
    "Mean Look",
    "Attract",
    "Sleep Talk",
    "Heal Bell",
    "Return",
    "Present",
    "Frustration",
    "Safeguard",
    "Pain Split",
    "Sacred Fire",
    "Magnitude",
    "Dynamic Punch",
    "Megahorn",
    "Dragon Breath",
    "Baton Pass",
    "Encore",
    "Pursuit",
    "Rapid Spin",
    "Sweet Scent",
    "Iron Tail",
    "Metal Claw",
    "Vital Throw",
    "Morning Sun",
    "Synthesis",
    "Moonlight",
    "Hidden Power",
    "Cross Chop",
    "Twister",
    "Rain Dance",
    "Sunny Day",
    "Crunch",
    "Mirror Coat",
    "Psych Up",
    "Extreme Speed",
    "Ancient Power",
    "Shadow Ball",
    "Future Sight",
    "Rock Smash",
    "Whirlpool",
    "Beat Up",
    "Fake Out",
    "Uproar",
    "Stockpile",
    "Spit Up",
    "Swallow",
    "Heat Wave",
    "Snowscape",
    "Torment",
    "Flatter",
    "Will-O-Wisp",
    "Memento",
    "Facade",
    "Focus Punch",
    "Smelling Salts",
    "Follow Me",
    "Nature Power",
    "Charge",
    "Taunt",
    "Helping Hand",
    "Trick",
    "Role Play",
    "Wish",
    "Assist",
    "Ingrain",
    "Superpower",
    "Magic Coat",
    "Recycle",
    "Revenge",
    "Brick Break",
    "Yawn",
    "Knock Off",
    "Endeavor",
    "Eruption",
    "Skill Swap",
    "Imprison",
    "Refresh",
    "Grudge",
    "Snatch",
    "Secret Power",
    "Dive",
    "Arm Thrust",
    "Camouflage",
    "Tail Glow",
    "Luster Purge",
    "Mist Ball",
    "Feather Dance",
    "Teeter Dance",
    "Blaze Kick",
    "Mud Sport",
    "Ice Ball",
    "Needle Arm",
    "Slack Off",
    "Hyper Voice",
    "Poison Fang",
    "Crush Claw",
    "Blast Burn",
    "Hydro Cannon",
    "Meteor Mash",
    "Astonish",
    "Weather Ball",
    "Aromatherapy",
    "Fake Tears",
    "Air Cutter",
    "Overheat",
    "Odor Sleuth",
    "Rock Tomb",
    "Silver Wind",
    "Metal Sound",
    "Grass Whistle",
    "Tickle",
    "Cosmic Power",
    "Water Spout",
    "Signal Beam",
    "Shadow Punch",
    "Extrasensory",
    "Sky Uppercut",
    "Sand Tomb",
    "Sheer Cold",
    "Muddy Water",
    "Bullet Seed",
    "Aerial Ace",
    "Icicle Spear",
    "Iron Defense",
    "Block",
    "Howl",
    "Dragon Claw",
    "Frenzy Plant",
    "Bulk Up",
    "Bounce",
    "Mud Shot",
    "Poison Tail",
    "Covet",
    "Volt Tackle",
    "Magical Leaf",
    "Water Sport",
    "Calm Mind",
    "Leaf Blade",
    "Dragon Dance",
    "Rock Blast",
    "Shock Wave",
    "Water Pulse",
    "Doom Desire",
    "Psycho Boost",
    "Leech Life",
    "Air Slash",
    "Aqua Jet",
    "Aqua Tail",
    "Aura Sphere",
    "Avalanche",
    "Brave Bird",
    "Bug Buzz",
    "Bullet Punch",
    "Charge Beam",
    "Close Combat",
    "Cross Poison",
    "Dark Pulse",
    "Discharge",
    "Draco Meteor",
    "Dragon Pulse",
    "Drain Punch",
    "Earth Power",
    "Energy Ball",
    "Focus Blast",
    "Force Palm",
    "Giga Impact",
    "Grass Knot",
    "Gunk Shot",
    "Hammer Arm",
    "Head Smash",
    "Ice Shard",
    "Iron Head",
    "Lava Plume",
    "Magnet Bomb",
    "Mud Bomb",
    "Nasty Plot",
    "Night Slash",
    "Ominous Wind",
    "Power Gem",
    "Power Whip",
    "Psycho Cut",
    "Rock Climb",
    "Rock Polish",
    "Rock Wrecker",
    "Roost",
    "Seed Bomb",
    "Shadow Claw",
    "Shadow Sneak",
    "Vacuum Wave",
    "X-Scissor",
    "Zen Headbutt",
    "Switcheroo",
    "Drill Run",
    "Bulldoze",
    "Electroweb",
    "Flame Charge",
    "Frost Breath",
    "Heart Stamp",
    "Hone Claws",
    "Horn Leech",
    "Coil",
    "Hurricane",
    "Icicle Crash",
    "Work Up",
    "Quiver Dance",
    "Leaf Tornado",
    "Low Sweep",
    "Snarl",
    "Struggle Bug",
    "Steamroller",
    "Storm Throw",
    "Venoshock",
    "Wild Charge",
    "Poison Jab",
    "Acid Spray",
    "Fiery Dance",
    "Clear Smog",
    "Leaf Storm",
    "Stone Edge",
    "Payback",
    "Fire Fang",
    "Ice Fang",
    "Thunder Fang",
    "Flare Blitz",
    "Inferno",
    "Hex",
    "Dual Chop",
    "Double Hit",
    "Cotton Guard",
    "Acrobatics",
    "Flame Burst",
    "U-turn",
    "Volt Switch",
    "Dragon Tail",
    "Circle Throw",
    "Mirror Shot",
    "Wood Hammer",
    "Heal Pulse",
    "Flash Cannon",
    "Bug Bite",
    "Pluck",
    "Shell Smash",
    "Rage Powder",
    "Wake-Up Slap",
    "Razor Shell",
    "Copycat",
    "Miracle Eye",
    "Sucker Punch",
    "Scald",
    "Brine",
    "Fairy Wind",
    "Baby-Doll Eyes",
    "Play Rough",
    "Moonblast",
    "Draining Kiss",
    "Dazzling Gleam",
    "Disarming Voice",
    "Stealth Rock",
    "Toxic Spikes",
    "Healing Wish",
    "Lunar Dance",
    "Tailwind",
    "Boomburst",
    "Incinerate",
    "Worry Seed",
    "Gastro Acid",
    "Geomancy",
    "Flower Shield",
    "Rototiller",
    "Shift Gear",
    "Sticky Web",
    "Stored Power",
    "Acupressure",
    "Punishment",
    "Assurance",
    "Dragon Rush",
    "Dark Void",
    "Feint",
    "Phantom Force",
    "Petal Blizzard",
    "Play Nice",
    "Roar of Time",
    "Spacial Rend",
    "Magma Storm",
    "Final Gambit",
    "Shadow Force",
    "Nuzzle",
    "Retaliate",
    "Metal Bash",
    "Judgment",
    "Freeze-Dry",
    "Psyshock",
    "Round",
    "Tail Slap",
    "Gear Grind",
    "Natural Gift",
    "Chip Away",
    "Smack Down",
    "Hyperspace Hole",
    "Gyro Ball",
    "Hyperspace Fury",
    "Attack Order",
    "Defend Order",
    "Heal Order",
    "Captivate",
    "Defog",
    "Origin Pulse",
    "Precipice Blades",
    "Guard Swap",
    "Steam Eruption",
    "Metal Burst",
    "Me First",
    "Power Swap",
    "Power Trick",
    "Psycho Shift",
    "Wring Out",
    "King's Shield", // RR
    "Psystrike",
    "Autotomize",
    "Diamond Storm",
    "Sludge Wave",
    "Heavy Slam",
    "Synchronoise",
    "Electro Ball",
    "Foul Play",
    "Entrainment",
    "Night Daze",
    "Echoed Voice",
    "Land's Wrath", // RR
    "Oblivion Wing",
    "Heart Swap",
    "Aqua Fang",
    "Sacred Sword",
    "Heat Crash",
    "Head Charge",
    "Techno Blast",
    "Relic Song",
    "Secret Sword",
    "Glaciate",
    "Bolt Strike",
    "Blue Flare",
    "Freeze Shock",
    "Ice Burn",
    "V-create",
    "Fusion Flare",
    "Fusion Bolt",
    "Fell Stinger",
    "Noble Roar",
    "Dragon Ascent",
    "Parting Shot",
    "Topsy-Turvy",
    "Core Enforcer",
    "Chatter",
    "Confide",
    "Water Shuriken",
    "Mystical Fire",
    "Spiky Shield",
    "Eerie Impulse",
    "Hold Back",
    "Infestation",
    "Power-Up Punch",
    "Thousand Arrows",
    "Thousand Waves",
    "Parabolic Charge",
    "Searing Shot",
    "Seed Flare",
    "Accelerock",
    "Anchor Shot",
    "Aurora Veil",
    "Baneful Bunker",
    "Beak Blast",
    "Brutal Swing",
    "Burn Up",
    "Clanging Scales",
    "Darkest Lariat",
    "Dragon Hammer",
    "Fire Lash",
    "First Impression",
    "Fleur Cannon",
    "Floral Healing",
    "Gear Up",
    "High Horsepower",
    "Ice Hammer",
    "Laser Focus",
    "Leafage",
    "Liquidation",
    "Lunge",
    "Moongeist Beam",
    "Multi-Attack",
    "Nature's Madness",
    "Pollen Puff",
    "Power Trip",
    "Prismatic Laser",
    "Psychic Fangs",
    "Purify",
    "Revelation Dance",
    "Shadow Bone",
    "Shell Trap",
    "Shore Up",
    "Smart Strike",
    "Solar Blade",
    "Sparkling Aria",
    "Spectral Thief",
    "Speed Swap",
    "Spirit Shackle",
    "Spotlight",
    "Stomping Tantrum",
    "Strength Sap",
    "Sunsteel Ram",
    "Tearful Look",
    "Throat Chop",
    "Toxic Thread",
    "Trop Kick",
    "Zing Zap",
    "Electric Terrain",
    "Grassy Terrain",
    "Misty Terrain",
    "Psychic Terrain",
    "Grass Pledge",
    "Fire Pledge",
    "Water Pledge",
    "Trick Room",
    "Magic Room",
    "Wonder Room",
    "Crafty Shield",
    "Mat Block",
    "Quick Guard",
    "Wide Guard",
    "Aqua Ring",
    "Aromatic Mist",
    "Belch",
    "Bestow",
    "Fling",
    "Flying Press",
    "Gravity",
    "Guard Split",
    "Heal Block",
    "Ion Deluge",
    "Lucky Chant",
    "Magnet Rise",
    "Magnetic Flux",
    "Powder",
    "Power Split",
    "Reflect Type",
    "Simple Beam",
    "Soak",
    "Telekinesis",
    "Trick-or-Treat",
    "Venom Drench",
    "Forest's Curse", // RR
    "Mind Blown",
    "Photon Geyser",
    "Plasma Fists",
    "Electrify",
    "Embargo",
    "Fairy Lock",
    "Light of Ruin",
    "Trump Card",
    "After You",
    "Instruct",
    "Quash",
    "Happy Hour",
    "Double Iron Bash",
    "Last Resort",
    "Sky Drop",
    "Celebrate",
    "Hold Hands",
    "Dynamax Cannon",
    "Snipe Shot",
    "Jaw Lock",
    "Stuff Cheeks",
    "No Retreat",
    "Tar Shot",
    "Magic Powder",
    "Dragon Darts",
    "Teatime",
    "Octolock",
    "Bolt Beak",
    "Fishious Rend",
    "Court Change",
    "Clangorous Soul",
    "Body Press",
    "Decorate",
    "Drum Beating",
    "Snap Trap",
    "Pyro Ball",
    "Behemoth Blade",
    "Behemoth Bash",
    "Aura Wheel",
    "Breaking Swipe",
    "Branch Poke",
    "Overdrive",
    "Apple Acid",
    "Grav Apple",
    "Spirit Break",
    "Strange Steam",
    "Life Dew",
    "Obstruct",
    "False Surrender",
    "Meteor Assault",
    "Eternabeam",
    "Steel Beam",
    "Expanding Force",
    "Steel Roller",
    "Scale Shot",
    "Meteor Beam",
    "Shell Side Arm",
    "Misty Explosion",
    "Grassy Glide",
    "Rising Voltage",
    "Terrain Pulse",
    "Skitter Smack",
    "Burning Jealousy",
    "Lash Out",
    "Poltergeist",
    "Corrosive Gas",
    "Coaching",
    "Flip Turn",
    "Triple Axel",
    "Dual Wingbeat",
    "Scorching Sands",
    "Jungle Healing",
    "Wicked Blow",
    "Surging Strikes",
    "Freezing Glare",
    "Thunderous Kick",
    "Fiery Wrath",
    "Thunder Cage",
    "Dragon Energy",
    "Astral Barrage",
    "Glacial Lance",
    "Eerie Spell",
    "Zippy Zap",
    "Sappy Seed",
    "Freezy Frost",
    "Sparkly Swirl",
    "Bouncy Bubble",
    "Sonic Slash",
    "DracoBarrage",
    "Stone Axe",
    "Headlong Rush",
    "Victory Dance",
    "Infernal Parade",
    "Ceaseless Edge",
    "Triple Arrows",
    "Barb Barrage",
    "Chloroblast",
    "Bitter Malice",
    "Esper Wing",
    "Dire Claw",
    "Mountain Gale",
    "Psyshield Bash",
    "Mystical Power",
    "Wave Crash",
    "Flower Trick",
    "Torch Song",
    "Aqua Step",
    "Hyper Drill",
    "Armor Cannon",
    "Bitter Blade",
    "Aqua Cutter",
    "Rage Fist",
    "Glaive Rush",
    "Last Respects",
    "Shed Tail",
    "Jet Punch",
    "Spin Out",
    "Collision Course",
    "Electro Drift",
    "Revival Blessing",
    "Gigaton Hammer",
    "Raging Bull",
    "Twin Beam",
    "Kowtow Cleave",
    "Double Shock",
    "Trailblaze",
    "Pounce",
    "Make It Rain",
    "Population Bomb",
    "Lunar Blessing",
    "Take Heart",
    "Silk Trap",
    "Axe Kick",
    "Lumina Crash",
    "Ice Spinner",
    "Salt Cure",
    "Triple Dive",
    "Mortal Spin",
    "Fillet Away",
    "Chilly Reception",
    "Chilling Water",
    "Comeuppance",
    "Tidy Up",
    "Ruination",
    "Psyblade",
    "Hydro Steam",
    "Bleakwind Storm",
    "Wildbolt Storm",
    "Sandsear Storm",
    "Springtide Storm",
    "Blood Moon",
    "Matcha Gotcha",
    "Ivy Cudgel",
    "Electro Shot",
    "Thunderclap",
    "Tachyon Cutter",
    "Psychic Noise",
    "Upper Hand",
    "Fickle Beam",
    "Burning Bulwark",
    "Placeholder",
    "Mighty Cleave",
    "Hard Press",
    "Dragon Cheer",
    "Alluring Voice",
    "Temper Flare",
    "Supercell Slam",
    "Malignant Chain",
    "Placeholder",
    "Placeholder",
    "Placeholder",
    "Placeholder",
    "Placeholder",
    "Placeholder",
    "Placeholder",
    "Placeholder",
    "Placeholder",
    "Placeholder",
    "Placeholder",
    "Placeholder",
    "Placeholder",
    "Placeholder",
    "Placeholder",
    "Placeholder",
    "Placeholder",
    "Placeholder",
    "Placeholder",
    "Z-Move 1",
    "Z-Move 2",
    "Z-Move 3",
    "Z-Move 4",
    "Z-Move 5",
    "Z-Move 6",
    "Z-Move 7",
    "Z-Move 8",
    "Z-Move 9",
    "Z-Move 10",
    "Z-Move 11",
    "Z-Move 12",
    "Z-Move 13",
    "Z-Move 14",
    "Z-Move 15",
    "Z-Move 16",
    "Z-Move 17",
    "Z-Move 18",
    "Z-Move 19",
    "Z-Move 20",
    "Z-Move 21",
    "Z-Move 22",
    "Z-Move 23",
    "Z-Move 24",
    "Z-Move 25",
    "Z-Move 26",
    "Z-Move 27",
    "Z-Move 28",
    "Z-Move 29",
    "Z-Move 30",
    "Z-Move 31",
    "Z-Move 32",
    "Z-Move 33",
    "Z-Move 34",
    "Z-Move 35",
    "Z-Move 36",
    "Z-Move 37",
    "Z-Move 38",
    "Z-Move 39",
    "Z-Move 40",
    "Z-Move 41",
    "Z-Move 42",
    "Z-Move 43",
    "Z-Move 44",
    "Z-Move 45",
    "Z-Move 46",
    "Z-Move 47",
    "Z-Move 48",
    "Z-Move 49",
    "Z-Move 50",
    "Z-Move 51",
    "Z-Move 52",
    "Z-Move 53",
    "Guard",
    "Strike",
    "Strike",
    "Knuckle",
    "Knuckle",
    "Airstream",
    "Airstream",
    "Ooze",
    "Ooze",
    "Quake",
    "Quake",
    "Rockfall",
    "Rockfall",
    "Flutterby",
    "Flutterby",
    "Phantasm",
    "Phantasm",
    "Steelspike",
    "Steelspike",
    "Flare",
    "Flare",
    "Geyser",
    "Geyser",
    "Overgrowth",
    "Overgrowth",
    "Lightning",
    "Lightning",
    "Mindstorm",
    "Mindstorm",
    "Hailstorm",
    "Hailstorm",
    "Wyrmwind",
    "Wyrmwind",
    "Darkness",
    "Darkness",
    "Starfall",
    "Starfall",
    "Vine Lash",
    "Vine Lash",
    "Wildfire",
    "Wildfire",
    "Cannonade",
    "Cannonade",
    "Befuddle",
    "Befuddle",
    "Voltcrash",
    "Voltcrash",
    "Goldrush",
    "Goldrush",
    "Chistrike",
    "Chistrike",
    "Terror",
    "Terror",
    "Foamburst",
    "Foamburst",
    "Resonance",
    "Resonance",
    "Cuddle",
    "Cuddle",
    "Replenish",
    "Replenish",
    "Malodor",
    "Malodor",
    "Meltdown",
    "Meltdown",
    "Drum Solo",
    "Drum Solo",
    "Fireball",
    "Fireball",
    "Hydrosnipe",
    "Hydrosnipe",
    "Windrage",
    "Windrage",
    "Gravitas",
    "Gravitas",
    "Stonesurge",
    "Stonesurge",
    "Volcalith",
    "Volcalith",
    "Tartness",
    "Tartness",
    "Sweetness",
    "Sweetness",
    "Sandblast",
    "Sandblast",
    "Stunshock",
    "Stunshock",
    "Centiferno",
    "Centiferno",
    "Smite",
    "Smite",
    "Snooze",
    "Snooze",
    "Finale",
    "Finale",
    "Steelsurge",
    "Steelsurge",
    "Depletion",
    "Depletion",
    "One Blow",
    "One Blow",
];

mod cfru_to_national_map;
mod national_to_cfru;

use crate::pkm::{Error, MoveErrorSource, Result};
use crate::resources::ALL_MOVES;

use cfru_to_national_map::CFRU_TO_NATIONAL_MAP;
use national_to_cfru::NATIONAL_TO_CFRU_MAP;

pub fn from_gen3_cfru_move_index(rr_index: usize) -> Result<u16> {
    if rr_index == 0 {
        return Ok(0);
    }

    if let Some(&name) = GEN3_CFRU_MOVES.get(rr_index) {
        CFRU_TO_NATIONAL_MAP
            .get(name)
            .copied()
            .ok_or(Error::MoveError {
                value: rr_index as u16,
                source: MoveErrorSource::CFRUIndex,
            })
    } else {
        Err(Error::MoveError {
            value: rr_index as u16,
            source: MoveErrorSource::CFRUIndex,
        })
    }
}

pub fn to_gen3_cfru_move_index(national_move_id: usize) -> Result<u16> {
    if national_move_id == 0 {
        return Ok(0);
    }

    if let Some(&meta) = ALL_MOVES.get(national_move_id) {
        NATIONAL_TO_CFRU_MAP
            .get(meta.name())
            .and_then(|list| list.first().copied())
            .ok_or(Error::MoveError {
                value: national_move_id as u16,
                source: MoveErrorSource::NationalIndex,
            })
    } else {
        Err(Error::MoveError {
            value: national_move_id as u16,
            source: MoveErrorSource::NationalIndex,
        })
    }
}
