[package]
name = "openhome-cli"
version = "0.1.0"
authors = ["Andrew Benington"]
edition = "2024"

[dependencies]
toml = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
num = "0.4.3"
wasm-bindgen = "0.2"
js-sys = "0.3.77"
serde-wasm-bindgen = "0.6.5"

[lib]
name = "pkm_rs"
path = "src/lib.rs"
crate-type = ["cdylib"]
