const LGPELocations = {
  0: [
    "——————",
    "Mystery Zone",
    "Faraway place",
    "Route 1",
    "Route 2",
    "Route 3",
    "Route 4",
    "Route 5",
    "Route 6",
    "Route 7",
    "Route 8",
    "Route 9",
    "Route 10",
    "Route 11",
    "Route 12",
    "Route 13",
    "Route 14",
    "Route 15",
    "Route 16",
    "Route 17",
    "Route 18",
    "Route 19",
    "Route 20",
    "Route 21",
    "Route 22",
    "Route 23",
    "Route 24",
    "Route 25",
    "Pallet Town",
    "Viridian City",
    "Pewter City",
    "Cerulean City",
    "Lavender Town",
    "Vermilion City",
    "Celadon City",
    "Fuchsia City",
    "Cinnabar Island",
    "Indigo Plateau",
    "Saffron City",
    "Viridian Forest",
    "Mt. Moon",
    "Rock Tunnel",
    "Power Plant",
    "Diglett’s Cave",
    "Seafoam Islands",
    "Victory Road",
    "Cerulean Cave",
    "Pokémon Tower",
    "S.S. Anne",
    "Team Rocket Hideout",
    "GO Park complex",
    "Pokémon Mansion",
    "Silph Co.",
    "Pokémon League",
  ],
  30000: [
    "",
    "a Link Trade",
    "a Link Trade",
    "the Kanto region",
    "the Johto region",
    "the Hoenn region",
    "the Sinnoh region",
    "a distant land",
    "——————",
    "the Unova region",
    "the Kalos region",
    "Pokémon Link",
    "Pokémon GO",
    "the Kanto region",
    "the Hoenn region",
    "the Alola region",
    "Poké Pelago",
    "the Johto region",
  ],
  40000: [
    "",
    "a lovely place",
    "a faraway place",
    "a Pokémon movie",
    "2018 Pokémon Movie",
    "2019 Pokémon Movie",
    "2020 Pokémon Movie",
    "2021 Pokémon Movie",
    "2022 Pokémon Movie",
    "2023 Pokémon Movie",
    "the Pokémon animated show",
    "a Pokémon Center",
    "Pokémon Center Tohoku",
    "a WCS",
    "WCS 2018",
    "WCS 2019",
    "WCS 2020",
    "WCS 2021",
    "WCS 2022",
    "WCS 2023",
    "Worlds",
    "2018 Worlds",
    "2019 Worlds",
    "2020 Worlds",
    "2021 Worlds",
    "2022 Worlds",
    "2023 Worlds",
    "a VGE",
    "VGE 2018",
    "VGE 2019",
    "VGE 2020",
    "VGE 2021",
    "VGE 2022",
    "VGE 2023",
    "a Pokémon event",
    "a Battle Competition",
    "a game event",
    "the Pokémon Daisuki Club",
    "a Pokémon TV program",
    "a concert",
    "an online present",
    "the PGL",
    "a 2018 Pokémon event",
    "a 2019 Pokémon event",
    "a 2020 Pokémon event",
    "a 2021 Pokémon event",
    "a 2022 Pokémon event",
    "a 2023 Pokémon event",
    "a Pokémon event",
    "a 2018 Pokémon event",
    "a 2019 Pokémon event",
    "a 2020 Pokémon event",
    "a 2021 Pokémon event",
    "a 2022 Pokémon event",
    "a 2023 Pokémon event",
    "PokéPark",
    "PokéPark 2018",
    "PokéPark 2019",
    "PokéPark 2020",
    "PokéPark 2021",
    "PokéPark 2022",
    "PokéPark 2023",
    "an event site",
    "GAME FREAK",
    "a stadium",
    "VGC",
    "the VGC 2018",
    "the VGC 2019",
    "the VGC 2020",
    "the VGC 2021",
    "the VGC 2022",
    "the VGC 2023",
    "a Virtual Console game",
    "Pokémon GO",
    "Pokémon Bank",
    "a Pokémon shop",
    "a demo version",
    "Poké Ball Plus",
  ],
};

export default LGPELocations;
