const SwShLocations = {
  0: [
    "——————",
    "",
    "Mystery Zone",
    "",
    "Faraway place",
    "",
    "Postwick",
    "",
    "Slumbering Weald",
    "",
    "",
    "",
    "Route 1",
    "",
    "Wedgehurst",
    "",
    "Wedgehurst Station",
    "",
    "Route 2",
    "",
    "Motostoke",
    "",
    "Motostoke Station",
    "",
    "Motostoke Stadium",
    "",
    "",
    "",
    "Route 3",
    "",
    "Galar Mine",
    "",
    "Route 4",
    "",
    "Turffield",
    "",
    "Turffield Stadium",
    "",
    "",
    "",
    "Route 5",
    "",
    "",
    "",
    "Hulbury",
    "",
    "Hulbury Station",
    "",
    "Hulbury Stadium",
    "",
    "",
    "",
    "Motostoke Outskirts",
    "",
    "Galar Mine No. 2",
    "",
    "Hammerlocke",
    "",
    "Hammerlocke Station",
    "",
    "Hammerlocke Stadium",
    "",
    "",
    "",
    "Energy Plant",
    "",
    "Tower Summit",
    "",
    "Route 6",
    "",
    "Stow-on-Side",
    "",
    "Stow-on-Side Stadium",
    "",
    "",
    "",
    "Glimwood Tangle",
    "",
    "Ballonlea",
    "",
    "Ballonlea Stadium",
    "",
    "",
    "",
    "Route 7",
    "",
    "Route 8",
    "",
    "Route 8",
    "Steamdrift Way",
    "Route 9",
    "",
    "Route 9",
    "Circhester Bay",
    "Route 9",
    "Outer Spikemuth",
    "Circhester",
    "",
    "Circhester Stadium",
    "",
    "",
    "",
    "Spikemuth",
    "",
    "Route 9 Tunnel",
    "",
    "Route 10",
    "",
    "White Hill Station",
    "",
    "Wyndon",
    "",
    "Wyndon Station",
    "",
    "Wyndon Stadium",
    "Pokémon League HQ",
    "Wyndon Stadium",
    "Locker Room",
    "Wyndon Stadium",
    "",
    "Meetup Spot",
    "Wild Area",
    "Rolling Fields",
    "Wild Area",
    "Dappled Grove",
    "Wild Area",
    "Watchtower Ruins",
    "Wild Area",
    "East Lake Axewell",
    "Wild Area",
    "West Lake Axewell",
    "Wild Area",
    "Axew’s Eye",
    "Wild Area",
    "South Lake Miloch",
    "Wild Area",
    "Giant’s Seat",
    "Wild Area",
    "North Lake Miloch",
    "Wild Area",
    "Motostoke Riverbank",
    "Wild Area",
    "Bridge Field",
    "Wild Area",
    "Stony Wilderness",
    "Wild Area",
    "Dusty Bowl",
    "Wild Area",
    "Giant’s Mirror",
    "Wild Area",
    "Hammerlocke Hills",
    "Wild Area",
    "Giant’s Cap",
    "Wild Area",
    "Lake of Outrage",
    "Wild Area",
    "Wild Area Station",
    "",
    "Battle Tower",
    "",
    "Rose Tower",
    "",
    "Pokémon Den",
    "",
    "Fields of Honor",
    "Isle of Armor",
    "Soothing Wetlands",
    "Isle of Armor",
    "Forest of Focus",
    "Isle of Armor",
    "Challenge Beach",
    "Isle of Armor",
    "Brawlers’ Cave",
    "Isle of Armor",
    "Challenge Road",
    "Isle of Armor",
    "Courageous Cavern",
    "Isle of Armor",
    "Loop Lagoon",
    "Isle of Armor",
    "Training Lowlands",
    "Isle of Armor",
    "Warm-Up Tunnel",
    "Isle of Armor",
    "Potbottom Desert",
    "Isle of Armor",
    "Workout Sea",
    "Isle of Armor",
    "Stepping-Stone Sea",
    "Isle of Armor",
    "Insular Sea",
    "Isle of Armor",
    "Honeycalm Sea",
    "Isle of Armor",
    "Honeycalm Island",
    "Isle of Armor",
    "Master Dojo",
    "",
    "Tower of Darkness",
    "",
    "Tower of Waters",
    "",
    "Armor Station",
    "",
    "Slippery Slope",
    "Crown Tundra",
    "Freezington",
    "Crown Tundra",
    "Frostpoint Field",
    "Crown Tundra",
    "Giant’s Bed",
    "Crown Tundra",
    "Old Cemetery",
    "Crown Tundra",
    "Snowslide Slope",
    "Crown Tundra",
    "Tunnel to the Top",
    "Crown Tundra",
    "Path to the Peak",
    "Crown Tundra",
    "Crown Shrine",
    "Crown Tundra",
    "Giant’s Foot",
    "Crown Tundra",
    "Roaring-Sea Caves",
    "Crown Tundra",
    "Frigid Sea",
    "Crown Tundra",
    "Three-Point Pass",
    "Crown Tundra",
    "Ballimere Lake",
    "Crown Tundra",
    "Lakeside Cave",
    "Crown Tundra",
    "Dyna Tree Hill",
    "Crown Tundra",
    "Rock Peak Ruins",
    "",
    "Iceberg Ruins",
    "",
    "Iron Ruins",
    "",
    "Split-Decision Ruins",
    "",
    "Max Lair",
    "",
    "Crown Tundra Station",
  ],
  30000: [
    "",
    "a Link Trade",
    "a Link Trade",
    "the Kanto region",
    "the Johto region",
    "the Hoenn region",
    "the Sinnoh region",
    "a distant land",
    "——————",
    "the Unova region",
    "the Kalos region",
    "Pokémon Link",
    "Pokémon GO",
    "the Kanto region",
    "the Hoenn region",
    "the Alola region",
    "Poké Pelago",
    "the Johto region",
    "Pokémon HOME",
    "the Kanto region",
  ],
  40000: [
    "",
    "a lovely place",
    "a faraway place",
    "a Pokémon movie",
    "[~ 3]",
    "a 2019 Pokémon movie",
    "a 2020 Pokémon movie",
    "a 2021 Pokémon movie",
    "a 2022 Pokémon movie",
    "a 2023 Pokémon movie",
    "a 2024 Pokémon movie",
    "the Pokémon animated show",
    "a Pokémon Center",
    "Pokémon Center Tohoku",
    "a WCS",
    "[~ 14]",
    "WCS 2019",
    "WCS 2020",
    "WCS 2021",
    "WCS 2022",
    "WCS 2023",
    "WCS 2024",
    "Worlds",
    "[~ 22]",
    "2019 Worlds",
    "2020 Worlds",
    "2021 Worlds",
    "2022 Worlds",
    "2023 Worlds",
    "2024 Worlds",
    "a VGE",
    "[~ 30]",
    "VGE 2019",
    "VGE 2020",
    "VGE 2021",
    "VGE 2022",
    "VGE 2023",
    "VGE 2024",
    "a Pokémon event",
    "a Battle Competition",
    "a game event",
    "the Pokémon Daisuki Club",
    "a Pokémon TV program",
    "a concert",
    "an online present",
    "the PGL",
    "[~ 45]",
    "a 2019 Pokémon event",
    "a 2020 Pokémon event",
    "a 2021 Pokémon event",
    "a 2022 Pokémon event",
    "a 2023 Pokémon event",
    "a 2024 Pokémon event",
    "a Pokémon event",
    "[~ 53]",
    "a 2019 Pokémon event",
    "a 2020 Pokémon event",
    "a 2021 Pokémon event",
    "a 2022 Pokémon event",
    "a 2023 Pokémon event",
    "a 2024 Pokémon event",
    "PokéPark",
    "[~ 61]",
    "PokéPark 2019",
    "PokéPark 2020",
    "PokéPark 2021",
    "PokéPark 2022",
    "PokéPark 2023",
    "PokéPark 2024",
    "an event site",
    "GAME FREAK",
    "a stadium",
    "a VGC event",
    "[~ 72]",
    "the VGC 2019",
    "the VGC 2020",
    "the VGC 2021",
    "the VGC 2022",
    "the VGC 2023",
    "the VGC 2024",
    "a Virtual Console game",
    "Pokémon GO",
    "Pokémon Bank",
    "a Pokémon shop",
    "a demo version",
    "the Poké Ball Plus",
    "Pokémon HOME",
    "[~ 86]",
    "[~ 87]",
    "[~ 88]",
    "[~ 89]",
    "[~ 90]",
    "[~ 91]",
    "[~ 92]",
    "[~ 93]",
    "[~ 94]",
    "[~ 95]",
    "[~ 96]",
    "[~ 97]",
    "[~ 98]",
    "[~ 99]",
    "[~ 100]",
    "[~ 101]",
    "[~ 102]",
    "[~ 103]",
    "[~ 104]",
    "[~ 105]",
    "[~ 106]",
    "[~ 107]",
    "[~ 108]",
    "[~ 109]",
    "[~ 110]",
    "[~ 111]",
    "[~ 112]",
  ],
  60000: [
    " 	",
    "a stranger",
    "a Nursery worker",
    "a treasure hunter",
    "an old hot-springs visitor",
  ],
};
export default SwShLocations;
