// Code generated by sqlc. DO NOT EDIT.

import Database from 'better-sqlite3'

export const speciesGetAllQuery = `-- name: SpeciesGetAll :many
SELECT national_dex, name, level_up_type FROM species`

export interface SpeciesGetAllRow {
  nationalDex: number
  name: any
  levelUpType: any
}

export async function speciesGetAll(database: Database): Promise<SpeciesGetAllRow[]> {
  const stmt = database.prepare(speciesGetAllQuery)
  const result = await stmt.all()
  return result as SpeciesGetAllRow[]
}

export const formGetByNationalDexQuery = `-- name: FormGetByNationalDex :many
SELECT national_dex, form_index, name, display_name, type1, type2, base_hp, base_attack, base_defense, base_special_attack, base_special_defense, base_speed, ability1, ability2, ability_hidden, egg_group1, egg_group2, gender_ratio, height_decimeters, weight_hectograms, is_base_form, is_mega, is_gmax, is_battle_only, is_sublegendary, is_restricted_legendary, is_ultra_beast, is_paradox, is_mythical, regional, introduced_gen, sprite_name, sprite_row, sprite_col FROM form
WHERE national_dex = :p1`

export interface FormGetByNationalDexArgs {
  nationalDex: number
}

type SqliteBool = 0 | 1

export interface FormGetByNationalDexRow {
  nationalDex: number
  formIndex: number
  name: any
  displayName: any
  type1: any
  type2: any | null
  baseHp: number
  baseAttack: number
  baseDefense: number
  baseSpecialAttack: number
  baseSpecialDefense: number
  baseSpeed: number
  ability1: number
  ability2: number | null
  abilityHidden: number | null
  eggGroup1: any
  eggGroup2: any | null
  genderRatio: any | null
  heightDecimeters: number
  weightHectograms: number
  isBaseForm: SqliteBool
  isMega: SqliteBool
  isGmax: SqliteBool
  isBattleOnly: SqliteBool
  isSublegendary: SqliteBool
  isRestrictedLegendary: SqliteBool
  isUltraBeast: SqliteBool
  isParadox: SqliteBool
  isMythical: SqliteBool
  regional: any | null
  introducedGen: number
  spriteName: any
  spriteRow: number
  spriteCol: number
}

export async function formGetByNationalDex(
  database: Database,
  nationalDex: number
): Promise<FormGetByNationalDexRow[]> {
  const stmt = database.prepare(formGetByNationalDexQuery)
  const result = await stmt.all({ p1: nationalDex })
  return result as FormGetByNationalDexRow[]
}

export const evolutionsGetByPrevoQuery = `-- name: EvolutionsGetByPrevo :many
SELECT evo_national_dex, evo_form_index, prevo_national_dex, prevo_form_index FROM evolution
WHERE prevo_national_dex = :p1
  AND prevo_form_index = :p2`

export interface EvolutionsGetByPrevoArgs {
  prevoNationalDex: number
  prevoFormIndex: number
}

export interface EvolutionsGetByPrevoRow {
  evoNationalDex: number
  evoFormIndex: number
  prevoNationalDex: number
  prevoFormIndex: number
}

export async function evolutionsGetByPrevo(
  database: Database,
  args: EvolutionsGetByPrevoArgs
): Promise<EvolutionsGetByPrevoRow[]> {
  const stmt = database.prepare(evolutionsGetByPrevoQuery)
  const result = await stmt.all({ p1: args.prevoNationalDex, p2: args.prevoFormIndex })
  return result as EvolutionsGetByPrevoRow[]
}

export const evolutionsGetByEvoQuery = `-- name: EvolutionsGetByEvo :one
SELECT evo_national_dex, evo_form_index, prevo_national_dex, prevo_form_index FROM evolution
WHERE evo_national_dex = :p1
  AND evo_form_index = :p2`

export interface EvolutionsGetByEvoArgs {
  evoNationalDex: number
  evoFormIndex: number
}

export interface EvolutionsGetByEvoRow {
  evoNationalDex: number
  evoFormIndex: number
  prevoNationalDex: number
  prevoFormIndex: number
}

export async function evolutionsGetByEvo(
  database: Database,
  args: EvolutionsGetByEvoArgs
): Promise<EvolutionsGetByEvoRow | null> {
  const stmt = database.prepare(evolutionsGetByEvoQuery)
  const result = await stmt.get({ p1: args.evoNationalDex, p2: args.evoFormIndex })
  if (result == undefined) {
    return null
  }
  return result as EvolutionsGetByEvoRow
}
