const Gen3CFRUItems = [
  'None',
  'Master Ball',
  'Ultra Ball',
  'Great Ball',
  'Poke Ball',
  'Safari Ball',
  'Net Ball',
  'Dive Ball',
  'Nest Ball',
  'Repeat Ball',
  'Timer Ball',
  'Luxury Ball',
  'Premier Ball',
  'Potion',
  'Antidote',
  'Burn Heal',
  'Ice Heal',
  'Awakening',
  'Paralyz Heal',
  'Full Restore',
  'Max Potion',
  'Hyper Potion',
  'Super Potion',
  'Full Heal',
  'Revive',
  'Max Revive',
  'Fresh Water',
  'Soda Pop',
  'Lemonade',
  'Moomoo Milk',
  'EnergyPowder',
  'Energy Root',
  'Heal Powder',
  'Revival Herb',
  'Ether',
  'Max Ether',
  'Elixir',
  'Max Elixir',
  'Lava Cookie',
  'Blue Flute',
  'Yellow Flute',
  'Red Flute',
  'Black Flute',
  'White Flute',
  'Berry Juice',
  'Sacred Ash',
  'Shoal Salt',
  'Shoal Shell',
  'Red Shard',
  'Blue Shard',
  'Yellow Shard',
  'Green Shard',
  'RageCandyBar',
  'Old Gateau',
  'Casteliacone',
  'Dream Patch',
  'Shalour Sable',
  'Health Wing',
  'Muscle Wing',
  'Resist Wing',
  'Genius Wing',
  'Clever Wing',
  'Swift Wing',
  'HP Up',
  'Protein',
  'Iron',
  'Carbos',
  'Calcium',
  'Rare Candy',
  'PP Up',
  'Zinc',
  'PP Max',
  'Ability Pill',
  'Guard Spec.',
  'Dire Hit',
  'X Attack',
  'X Defend',
  'X Speed',
  'X Accuracy',
  'X Sp. Atk',
  'Poke Doll',
  'Fluffy Tail',
  'Big Malasada',
  'Super Repel',
  'Max Repel',
  'Escape Rope',
  'Repel',
  'Link Cable',
  'Protector',
  'Electirizer',
  'Magmarizer',
  'Dubious Disc',
  'Reaper Cloth',
  'Sun Stone',
  'Moon Stone',
  'Fire Stone',
  'ThunderStone',
  'Water Stone',
  'Leaf Stone',
  'Shiny Stone',
  'Dusk Stone',
  'Dawn Stone',
  'Ice Stone t',
  'TinyMushroom',
  'Big Mushroom',
  'BalmMushroom',
  'Pearl',
  'Big Pearl',
  'Stardust',
  'Star Piece',
  'Nugget',
  'Heart Scale',
  'Rare Bone',
  'Pearl String',
  'Comet Shard',
  'Big Nugget',
  'Honey weet',
  'Pretty Wing',
  'Oval Stone',
  'Razor Claw',
  'Razor Fang',
  'Orange Mail',
  'Harbor Mail',
  'Glitter Mail',
  'Mech Mail',
  'Wood Mail',
  'Wave Mail',
  'Bead Mail',
  'Shadow Mail',
  'Tropic Mail',
  'Dream Mail',
  'Fab Mail',
  'Retro Mail',
  'Cheri Berry',
  'Chesto Berry',
  'Pecha Berry',
  'Rawst Berry',
  'Aspear Berry',
  'Leppa Berry',
  'Oran Berry',
  'Persim Berry',
  'Lum Berry',
  'Sitrus Berry',
  'Figy Berry',
  'Wiki Berry',
  'Mago Berry',
  'Aguav Berry',
  'Iapapa Berry',
  'Razz Berry',
  'Bluk Berry',
  'Nanab Berry',
  'Wepear Berry',
  'Pinap Berry',
  'Pomeg Berry',
  'Kelpsy Berry',
  'Qualot Berry',
  'Hondew Berry',
  'Grepa Berry',
  'Tamato Berry',
  'Cornn Berry',
  'Magost Berry',
  'Rabuta Berry',
  'Nomel Berry',
  'Spelon Berry',
  'Pamtre Berry',
  'Watmel Berry',
  'Durin Berry',
  'Belue Berry',
  'Liechi Berry',
  'Ganlon Berry',
  'Salac Berry',
  'Petaya Berry',
  'Apicot Berry',
  'Lansat Berry',
  'Starf Berry',
  'Enigma Berry',
  'Prism Scale',
  'Sachet',
  'Whip Dream',
  'BrightPowder',
  'White Herb',
  'Macho Brace',
  'Exp. Share',
  'Quick Claw',
  'Soothe Bell',
  'Mental Herb',
  'Choice Band',
  "King's Rock",
  'Silver Powder',
  'Amulet Coin',
  'Cleanse Tag',
  'Soul Dew',
  'Deep Sea Tooth',
  'Deep Sea Scale',
  'Smoke Ball',
  'Everstone',
  'Focus Band',
  'Lucky Egg',
  'Scope Lens',
  'Metal Coat',
  'Leftovers',
  'Dragon Scale',
  'Light Ball',
  'Soft Sand',
  'Hard Stone',
  'Miracle Seed',
  'Black Glasses',
  'Black Belt',
  'Magnet',
  'Mystic Water',
  'Sharp Beak',
  'Poison Barb',
  'Never-Melt Ice',
  'Spell Tag',
  'Twisted Spoon',
  'Charcoal',
  'Dragon Fang',
  'Silk Scarf',
  'Upgrade carf',
  'Shell Bell',
  'Sea Incense',
  'Lax Incense',
  'Lucky Punch',
  'Metal Powder',
  'Thick Club',
  'Leek Stick',
  'Straw. Sweet',
  'Berry Sweet',
  'Love Sweet',
  'Clover Sweet',
  'Flower Sweet',
  'Ribbon Sweet',
  'Star Sweet',
  'Sweet Apple',
  'Tart Apple',
  'Cracked Pot',
  'Chipped Pot',
  'Galar Cuff',
  'Galar Crown',
  'Cherish Ball',
  'Dusk Ball',
  'Heal Ball',
  'Quick Ball',
  'Fast Ball',
  'Level Ball',
  'Lure Ball',
  'Heavy Ball',
  'Love Ball',
  'Friend Ball',
  'Moon Ball',
  'Sport Ball',
  'Beast Ball',
  'Dream Ball',
  'Park Ball',
  'Red Scarf',
  'Blue Scarf',
  'Pink Scarf',
  'Green Scarf',
  'Yellow Scarf',
  'Mach Bike',
  'Coin Case',
  'Itemfinder',
  'Old Rod',
  'Good Rod',
  'Super Rod',
  'S.S. Ticket',
  'Contest Pass',
  'Z-Power Ring',
  'Wailmer Pail',
  'Devon Goods',
  'Soot Sack',
  'Basement Key',
  'Acro Bike',
  'Pokeblock CASE',
  'Letter',
  'Eon Ticket',
  'Red Orb',
  'Blue Orb',
  'Scanner',
  'Go-Goggles',
  'Meteorite',
  'RM. 1 Key',
  'RM. 2 Key',
  'RM. 4 Key',
  'RM. 6 Key',
  'Storage Key',
  'Root Fossil',
  'Claw Fossil',
  'Devon Scope',
  'TM01',
  'TM02',
  'TM03',
  'TM04',
  'TM05',
  'TM06',
  'TM07',
  'TM08',
  'TM09',
  'TM10',
  'TM11',
  'TM12',
  'TM13',
  'TM14',
  'TM15',
  'TM16',
  'TM17',
  'TM18',
  'TM19',
  'TM20',
  'TM21',
  'TM22',
  'TM23',
  'TM24',
  'TM25',
  'TM26',
  'TM27',
  'TM28',
  'TM29',
  'TM30',
  'TM31',
  'TM32',
  'TM33',
  'TM34',
  'TM35',
  'TM36',
  'TM37',
  'TM38',
  'TM39',
  'TM40',
  'TM41',
  'TM42',
  'TM43',
  'TM44',
  'TM45',
  'TM46',
  'TM47',
  'TM48',
  'TM49',
  'TM50',
  'HM01',
  'HM02',
  'HM03',
  'HM04',
  'HM05',
  'HM06',
  'HM07',
  'HM08',
  'Dynamax Band',
  'Gold Teeth',
  "Oak's Parcel",
  'Poke Flute',
  'Secret Key',
  'Bike Voucher',
  'Mega Ring',
  'Old Amber',
  'Card Key',
  'Lift Key',
  'Helix Fossil',
  'Dome Fossil',
  'Silph Scope',
  'Bicycle',
  'Town Map',
  'Stat Scanner',
  'Poke Rider',
  'TM Case',
  'Berry Pouch',
  'Teachy TV',
  'Tri-Pass',
  'Rainbow Pass',
  'Tea',
  'Mystic Ticke',
  'Aurora Ticke',
  'Locater Dev',
  'Ruby',
  'Sapphire',
  '-DONT USE-',
  'TM51',
  'TM52',
  'TM53',
  'TM54',
  'TM55',
  'TM56',
  'TM57',
  'TM58',
  'TM59',
  'TM60',
  'TM61',
  'TM62',
  'TM63',
  'TM64',
  'TM65',
  'TM66',
  'TM67',
  'TM68',
  'TM69',
  'TM70',
  'TM71',
  'TM72',
  'TM73',
  'TM74',
  'TM75',
  'TM76',
  'TM77',
  'TM78',
  'TM79',
  'TM80',
  'TM81',
  'TM82',
  'TM83',
  'TM84',
  'TM85',
  'TM86',
  'TM87',
  'TM88',
  'TM89',
  'TM90',
  'TM91',
  'TM92',
  'TM93',
  'TM94',
  'TM95',
  'TM96',
  'TM97',
  'TM98',
  'TM99',
  'TM100',
  'TM101',
  'TM102',
  'TM103',
  'TM104',
  'TM105',
  'TM106',
  'TM107',
  'TM108',
  'TM109',
  'TM110',
  'TM111',
  'TM112',
  'TM113',
  'TM114',
  'TM115',
  'TM116',
  'TM117',
  'TM118',
  'TM119',
  'TM120',
  'Occa Berry',
  'Passho Berry',
  'Wacan Berry',
  'Rindo Berry',
  'Yache Berry',
  'Chople Berry',
  'Kebia Berry',
  'Shuca Berry',
  'Coba Berry',
  'Payapa Berry',
  'Tanga Berry',
  'Charti Berry',
  'Kasib Berry',
  'Haban Berry',
  'Colbur Berry',
  'Babiri Berry',
  'Chilan Berry',
  'Micle Berry',
  'Custap Berry',
  'Jacoba Berry',
  'Rowap Berry',
  'Roseli Berry',
  'Kee Berry',
  'Marang Berry',
  'Oval Charm',
  'Shiny Charm',
  'Rainbow Wing',
  'Silver Wing',
  'Magma Stone',
  'Light Stone',
  'Dark Stone',
  'Sun Flute',
  'Moon Flute',
  'Gracidea',
  'DNA Splicers',
  'Reveal Glass',
  'PrisonBottle',
  'N-Solarizer',
  'Necrozmizer',
  'Rusty Sword',
  'Rusty Shield',
  'Adamant Orb',
  'Lustrous Orb',
  'Griseous Orb',
  'Fist Plate',
  'Sky Plate',
  'Toxic Plate',
  'Earth Plate',
  'Stone Plate',
  'Insect Plate',
  'Spooky Plate',
  'Iron Plate',
  'Flame Plate',
  'Splash Plate',
  'Meadow Plate',
  'Zap Plate',
  'Mind Plate',
  'Icicle Plate',
  'Draco Plate',
  'Dread Plate',
  'Pixie Plate',
  'Fighting Memory',
  'Flying Memory',
  'Poison Memory',
  'Ground Memory',
  'Rock Memory',
  'Bug Memory',
  'Ghost Memory',
  'Steel Memory',
  'Fire Memory',
  'Water Memory',
  'Grass Memory',
  'Electr Memory',
  'Psychic Memory',
  'Ice Memory',
  'Dragon Memory',
  'Dark Memory',
  'Fairy Memory',
  'Burn Drive',
  'Douse Drive',
  'Shock Drive',
  'Chill Drive',
  'Red Nectar',
  'YellowNectar',
  'Pink Nectar',
  'PurpleNectar',
  'Necrozium Z',
  'Venusaurite',
  'Charizardite X',
  'Charizardite Y',
  'Blastoisnite',
  'Beedrillite',
  'Pidgeotite',
  'Alakazite',
  'Slowbronite',
  'Gengarite',
  'Kangaskanite',
  'Pinsirite',
  'Gyaradosite',
  'Aerodactlite',
  'Mewtwonite X',
  'Mewtwonite Y',
  'Ampharosite',
  'Steelixite',
  'Scizorite',
  'Heracronite',
  'Houndoomnite',
  'Tyranitarite',
  'Sceptilite',
  'Blazikenite',
  'Swampertite',
  'Gardevoirite',
  'Sablenite',
  'Mawilite',
  'Aggronite',
  'Medichamite',
  'Manectite',
  'Sharpedonite',
  'Cameruptite',
  'Altarianite',
  'Banettite',
  'Absolite',
  'Glalitite',
  'Salamencite',
  'Metagrossite',
  'Latiasite',
  'Latiosite',
  'Lopunnite',
  'Garchompite',
  'Lucarionite',
  'Abomasite',
  'Galladite',
  'Audinite',
  'Diancite',
  'Normalium Z',
  'Fightinium Z',
  'Flyinium Z',
  'Poisonium Z',
  'Groundium Z',
  'Rockium Z',
  'Buginium Z',
  'Ghostium Z',
  'Steelium Z',
  'Firium Z',
  'Waterium Z',
  'Grassium Z',
  'Electrium Z',
  'Psychium Z',
  'Icium Z',
  'Dragonium Z',
  'Darkinium Z',
  'Fairium Z',
  'Alorichium Z',
  'Decidium Z',
  'Eevium Z',
  'Incinium Z',
  'Kommonium Z',
  'Lunalium Z',
  'Lycanium Z',
  'Marshadium Z',
  'Mewnium Z',
  'Mimikium Z Z',
  'Pikanium Z',
  'Pikshunium Z',
  'Primarium Z',
  'Snorlium Z',
  'Solganium Z',
  'Tapunium Z',
  'Boost Energy',
  'Loaded Dice',
  'Clear Amulet',
  'Ability Shield',
  'Mirror Herb',
  'Upgrade',
  'Electirizer',
  'Cornerstone Mask',
  'Hearthflame Mask',
  'Wellspring Mask',
  'Teal Mask',
  'Burnt Seed',
  'Magmarizer',
  'Relic Crown',
  'Skull Fossil',
  'Armor Fossil',
  'Cover Fossil',
  'Plume Fossil',
  'Jaw Fossil',
  'Sail Fossil',
  'Bird Fossil',
  'Fish Fossil',
  'Drake Fossil',
  'Dino Fossil',
  'Odd Keystone',
  'Bottle Cap',
  'Gold Bottle Cap',
  'Wish Piece',
  'Power Bracer',
  'Power Belt',
  'Power Lens',
  'Power Band',
  'Power Anklet',
  'Power Weight',
  'Luck Incense',
  'Full Incense',
  'Odd Incense',
  'Pure Incense',
  'Rock Incense',
  'Rose Incense',
  'Wave Incense',
  'Normal Gem',
  'Fighting Gem',
  'Flying Gem',
  'Poison Gem',
  'Ground Gem',
  'Rock Gem',
  'Bug Gem',
  'Ghost Gem',
  'Steel Gem',
  'Fire Gem',
  'Water Gem',
  'Grass Gem',
  'Electric Gem',
  'Psychic Gem',
  'Ice Gem',
  'Dragon Gem',
  'Dark Gem',
  'Fairy Gem',
  'Wide Lens',
  'Muscle Band',
  'Wise Glasses',
  'Expert Belt',
  'Light Clay',
  'Life Orb',
  'Power Herb',
  'Toxic Orb',
  'Flame Orb',
  'Quick Powder',
  'Focus Sash',
  'Zoom Lens',
  'Metronome',
  'Iron Ball',
  'Lagging Tail',
  'Destiny Knot',
  'Black Sludge',
  'Icy Rock',
  'Smooth Rock',
  'Heat Rock',
  'Damp Rock',
  'Grip Claw',
  'Choice Scarf',
  'Choice Specs',
  'Sticky Barb',
  'Shed Shell',
  'Big Root',
  'Eviolite',
  'Float Stone',
  'Rocky Helmet',
  'Air Balloon',
  'Red Card',
  'Ring Target',
  'Binding Band',
  'Absorb Bulb',
  'Cell Battery',
  'Eject Button',
  'Weakness Policy',
  'Assault Vest',
  'Luminous Moss',
  'Snowball',
  'Safe Goggles',
  'Adrenal Orb',
  'Terrain Extender',
  'Protect Pads',
  'Electric Seed',
  'Grassy Seed',
  'Misty Seed',
  'Psychic Seed',
  'Eject Pack',
  'Room Service',
  'Blunder Policy',
  'Heavy-Duty Boots',
  'Utility Umbrella',
  'Throat Spray',
  'Machampite',
  'Laprasite',
  'Butterfrite',
  'Garbodorite',
  'Snorlaxite',
  'Kinglerite',
  'Toxtricitite',
  'Coalossite',
  'Duraludite',
  'Drednawite',
  'Copperajite',
  'Applite',
  'Orbeetlite',
  'Grimmsnite',
  'Medicine',
  'Centiskite',
  'Sandacondite',
  'Alcremite',
  'Eter.Max Orb',
  'Punch Glove',
  'Covert Cloak',
  'Free Space22',
]

export function ItemGen3CFRUToString(index: number): string {
  if (index < 0 || index >= Gen3CFRUItems.length) {
    return `Index ${index} out of range`
  }
  return Gen3CFRUItems[index]
}

export function ItemGen3CFRUFromString(itemName: string): number {
  return Gen3CFRUItems.findIndex((item) => item === itemName)
}
