name: Build
on: [push, pull_request]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 20
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: publish
        env:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release

  build_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 20
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: publish
        env:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          apple_id: ${{ secrets.APPLE_ID }}
          apple_id_pass: ${{ secrets.APPLE_ID_PASS }}
        run: npm run release

  build_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 20
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: publish
        env:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
