name: Type check, lint, and run tests

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main
      - update-workflows

jobs:
  type_check_lint_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install PNPM
        uses: pnpm/action-setup@v6

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target, ./pkm_rs -> target, ./pkm_rs_derive -> target, ./pkm_rs_resources -> target, ./pkm_rs_types -> target, . -> target'

      - name: Install Tauri dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install wasm-pack and nextest
        uses: taiki-e/install-action@v2
        with:
          tool: wasm-pack,nextest@0.9.140

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Build WASM
        run: pnpm run wasm-compile-dev

      - name: Type Check
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint:ci

      - name: Run Tests
        run: pnpm test:ci
