name: Type Check and Lint

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main
      - update-workflows

jobs:
  type_check_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install PNPM
        uses: pnpm/action-setup@v6

      - name: Setup Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target, ./openhome_core -> target, ./pkm_rs -> target, ./pkm_rs_derive -> target, ./pkm_rs_resources -> target, ./pkm_rs_types -> target, . -> target'

      - name: Install wasm-pack
        uses: taiki-e/install-action@v2
        with:
          tool: wasm-pack

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Build WASM
        run: pnpm run wasm-compile-dev

      - name: Type Check
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint:ci
